### PR TITLE
add add_attributes macro

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
This macro does the following
```julia
 julia> @macroexpand 
           @add_attributes series struct Legend
                title::String = "default title"
           end
quote
    struct Legend
        title::String
    end
    begin
        _series_defaults[:legend_title] = "default title"
    end
end
```
I think it would be nice to add the non-underscore aliases also

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
I added non_underscore and plural aliases and (hopefully) improved the alias generation in general. Might qualify for a minor release

**Comment by daschw** [comment]
I'm not sure, I follow completely. Where would this new macro be used? In Plots or by Plots users?

**Comment by BeastyBlacksmith** [comment]
That is intended for internal usage to ease the organization of attributes (I plan to use it for the Legend overhaul)

**Comment by daschw** [comment]
OK, thanks for the explanation!

**Pull request merged**
