### PR TITLE
Add submodule PlotMeasures (fix #821)

### LINKED ISSUE #821: Warning from exporting single character identifiers
```julia
h = 1; w = 2
using Plots
```
>WARNING: using Plots.w in module Main conflicts with an existing identifier.
WARNING: using Plots.h in module Main conflicts with an existing identifier.

### PR DESCRIPTION
**Pull request by mkborregaard**

### CODE REVIEW

**Comment by juliohm** [comment]
@mkborregaard can you please restart the build on Travis? I don't see any problem in merging this PR to fix that issue with `h` and `w`.

**Comment by mkborregaard** [comment]
Oh, there were a number of issues - I believe I've fixed them now, though.

**Comment by mkborregaard** [comment]
@juliohm A great help for getting this merged would be to identify those places in the docs (mainly the examples, probably), that would need to be changed (by including `using Plots.PlotMeasures`) to reflect this?

**Comment by juliohm** [comment]
@mkborregaard will the plot examples fail when the documentation is built? I can try to fix the build errors if it is something that can be easily tracked.

**Comment by mkborregaard** [comment]
Some will fail, but we don't need help with identifying those, of course.

**Pull request merged**
