### PR TITLE
Line legend marker for ribbons in GR (fix #896)

### LINKED ISSUE #896: GR Legend Marker for Ribbons
I believe https://github.com/JuliaPlots/Plots.jl/pull/885 changed the markers for ribbons (it used to just show a line).  Should a line also be part of the marker here?

screen shot 2017-06-06 at 10 51 14 am

### PR DESCRIPTION
**Pull request by daschw**
Resets the GR legend marker for plots with ribbons to the behaviour before #885.
```julia
using Plots; gr()
rib1, rib2, rib3, rib4 = 0.1, (0.1, 0.2), 0.1 * rand(10), (0.1 * rand(10), 0.2 * rand(10))
plot([plot(rand(10), ribbon = rib, fillalpha = 0.5) for rib in (rib1, rib2, rib3, rib4)]...)
```
produced these legend markers:
ribbon_old

Now only lines are drawn again:
ribbon_new

### CODE REVIEW

**Comment by joshday** [comment]
Thanks for working on this!  Is there a way to get the color in the legend to match the line color?  It looks like it's using the alpha color.

**Comment by daschw** [comment]
I don't think it is, but I agree it looks like so.
How about this?
```julia
using Plots; gr()
y, rib = rand(10), rand(10)
plot(
    plot(y, ribbon = rib),
    plot(y, ribbon = rib, fillalpha = 0.5),
    plot(y, ribbon = rib, fillcolor = 2),
    plot(y, ribbon = rib, fillalpha = 0.5, fillcolor = 2),
    )
```

gr_ribbon_new

**Comment by daschw** [comment]
No, you were right. It's really using the `fillalpha` somehow. I don't know how to fix this, though. It seems like `gr_set_line(...)` used to accept an alpha argument, but does not any more. @jheinen probably knows more about this.

**Comment by daschw** [comment]
I also changed the legend marker for path with fillrange. Here are the legend markers for different series types after this PR:

```julia
using Plots; gr()
y, rib = rand(10), rand(10)
plot(
    bar(y, fillalpha = 0.5, title = "Bar / Shape"),
    plot(y, title = "Path"),
    plot(y, ribbon = rib, fillcolor = 2, title = "Path with ribbon"),
    plot(y, fillrange = -rand(10), fillalpha = 0.5, fillcolor = 2, title = "Path with fillrange"),
    )
```

gr_markers

**Comment by jheinen** [comment]
The transparency should be set to 1 (in the legend part, around line 1042) - at least for the text output, e.g.
```julia
            if sp[:legendtitle] != nothing
                GR.settextalign(GR.TEXT_HALIGN_CENTER, GR.TEXT_VALIGN_HALF)
                gr_set_textcolor(sp[:foreground_color_legend])
                GR.settransparency(1)
                gr_text(xpos - 0.03 + 0.5*w, ypos, string(sp[:legendtitle]))
                ypos -= dy
            end
```

**Comment by jheinen** [comment]
... probably also for the lines, markers and fill areas - but that's a matter of taste

**Comment by jheinen** [comment]
@daschw : I think, only the surrounding rectangle and the text should be drawn without any transparency (=> 1). Lines, markers etc. should be drawn with the same attributes as the series. What do you think?

**Comment by daschw** [comment]
I agree and I'm on it. Thanks for the hint with `GR.settransparency()`!

**Comment by daschw** [comment]
Now we have
gr_markers_new

**Pull request merged**
