### PR TITLE
Use show instead of writemime for eps

### PR DESCRIPTION
**Pull request by anriseth**

### CODE REVIEW

**Comment by mkborregaard** [comment]
Hi, what's the rationale behind the change?

**Comment by anriseth** [comment]
writemime was deprecated in Julia 0.4(or 0.5?), and was been replaced by
show. I guess  nobody saves anything as EPS, seeing that there have been no
complaints since 0.6 came out.

**Comment by anriseth** [comment]
To add to that: writemime does not exist on 0.6.

**Comment by mkborregaard** [comment]
ha ha, thanks @anriseth !

**Pull request merged**
