### PR TITLE
Implement plotattributes with defaults. Fixes "-->" in series recipes.

### LINKED ISSUE #1639: `-->` ignored in series recipes
I noticed this as I was testing through all of StatPlots (it makes the ea_histogram recipe fail), but I also get it now even on very old (~1 year) versions of RecipesBase and Plots, and running on 0.6.3. If all users experience this, it is a big problem for the recipe ecosystem, so it is a priority. It is not 0.7-related.

```julia
@recipe function g(::Type{Val{:testhist}}, x, y, z)
        markercolor := :red
        seriestype := :scatter
        ()
end

@recipe function f(::Type{Val{:testhist2}}, x, y, z)
        markercolor --> :red
         seriestype := :scatter
         ()
end

plot(rand(10,2), st = [:testhist :testhist2], layout = 2)
```

skaermbillede 2018-08-12 kl 16 55 26

### PR DESCRIPTION
**Pull request by yha**
Fixes #1639 as suggested in https://github.com/JuliaPlots/Plots.jl/pull/1698#issuecomment-420973969.
Requires JuliaPlots/RecipesBase.jl#60.

### CODE REVIEW

**Comment by daschw** [comment]
Wow, this looks great @yha. Did you check if the tests pass locally? Does this have an impact on performance?

**Comment by mkborregaard** [comment]
@yha I've got something I'd like you to check before merging (adresses your "TODO" in your code). Let me try to get an mwe working.

**Comment by yha** [comment]
@daschw Yes, tests pass locally (with the `RecipesBase` PR). I didn't test the impact on performance.

**Comment by daschw** [comment]
@mkborregaard Did you check what you wanted to check?

**Comment by mkborregaard** [comment]
No I had a really weird bug in a complex recipe, and I wanted to see if this fixed it. Let me see if I can recreate an mwe

**Comment by mkborregaard** [comment]
Yeah sorry I'm having some Pkg issues that mean I can't check out this branch locally to test. But @yha could you check this MWE? https://github.com/JuliaPlots/Plots.jl/issues/2383
Maybe relevant for this line https://github.com/JuliaPlots/Plots.jl/blob/366d598ff0602c6dfb6745f2959d7407cdba4b64/src/args.jl#L1405

**Comment by yha** [comment]
I can reproduce the bug on this branch as well.
I don't think this line has anything to do with it: printing `plotattributes_in` at the start of this method I find that it's called only once, with
```
plotattributes_in = Dict{Symbol,Any}(:plot_object => Plot{Plots.GRBackend() n=2},:smooth => false)
```
The bug still happens if I modify the code to delete merged attributes, and/or to only merge attributes also in `keys(_plot_defaults)` as before.

**Comment by mkborregaard** [comment]
OK, thanks for checking. :+1: to me for merging if we the Travis failures are unrelated.

**Comment by yha** [comment]
> if the Travis failures are unrelated

Checks fail here because JuliaPlots/RecipesBase.jl#60 is not yet merged

**Comment by mkborregaard** [comment]
Right - I just merged both, tagged v 0.8 of RecipesBased and added a compat for it here on master.

**Pull request merged**
