### PR TITLE
fix plotly incongruity

### PR DESCRIPTION
**Pull request by t-bltg**
Maybe fix https://github.com/JuliaPlots/Plots.jl/issues/4583.

I don't like doing this (exceptions to the already complicated load / requires mechanism).

Can you test that it works @BeastyBlacksmith ?

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
```julia
julia> using Plots; plotly(); plot(rand(10))
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
┌ Warning: backend `GR` is not installed.
└ @ Plots ~/.julia/dev/Plots/src/backends.jl:33
[ Info: GR
[ Info: Precompiling PlotlyKaleido [f2990250-8cf9-495f-b13a-cce12b45703c]
```
This works. I'm a bit irritated by that warnong though

**Comment by BeastyBlacksmith** [comment]
we might want to add a simple test with the ploty backend, that creates a html-file

**Comment by BeastyBlacksmith** [comment]
I mean
```┌ Warning: backend `GR` is not installed.
└ @ Plots ~/.julia/dev/Plots/src/backends.jl:33
```

**Comment by t-bltg** [comment]
> we might want to add a simple test with the ploty backend, that creates a html-file

As I said, I'm not `plotly` competent at all, so if you have a test idea ...

**Comment by t-bltg** [comment]
> Warning: backend `GR` is not installed.

How can that happen ? `GR` is a hard depedency.

**Comment by BeastyBlacksmith** [comment]
> > Warning: backend `GR` is not installed.
> 
> How can that happen ? `GR` is a hard depedency of `Plots`, maybe run `instantiate` ?

Hmm.. I had this, but it doesn't show up on CI. Must be my system then.

**Comment by BeastyBlacksmith** [comment]
> I mean
> 
> ```
> ┌ Warning: backend `GR` is not installed.
> └ @ Plots ~/.julia/dev/Plots/src/backends.jl:33
> ```

FWIW, I've seen that warning popping up in multiple occasions now, also on other peoples machines. It's working afterwards nevertheless, but it is irritating.

Secondly, I happened to notice that you can't use the plotlybase functionality if you haven't PlotlyKaleido installed, which ideally shouldn't be.

**Comment by t-bltg** [comment]
> FWIW, I've seen that warning popping up in multiple occasions now, also on other peoples machines. It's working afterwards nevertheless, but it is irritating.

Maybe an environment stack issues. Could help if we had a reproducer.

**Pull request merged**
