### PR TITLE
Infinite objects (fix #1422)

### LINKED ISSUE #1297: `abline` shouldn't update limits
I think the intent of `abline`, like `hline` and `vline` is to plot a line that spans the plot, but that doesn't update the plot limits beyond what's "necessary". 

```julia
using Plots
@gif for c  = ["plot()", "plot(x->10*sin(x))", "Plots.abline!(10,0)"]
  eval(parse(c))
  title!(c)
end
```
out

In this case, I think the limits should stay the same after the sinusoid is plotted.

In any case, is there a way to force the limits to stay the same? Or better yet, give a list of invisible points that should be used to update the limits (and if this list is empty, then don't update the limits?) I'm interested in drawing lines that extend beyond the limits, so that when the graph is panned or zoomed, the line appears to extend forever.

### LINKED ISSUE #1422: Plotting a polygon with infinite vertices does not plot the polygon
e.g.
```
plot([1, 2, 2, 1], [Inf, Inf, 6, 5], seriestype=:shape, ylim=(-10,10))
```

It should clip the filled polygon to the viewing area.

### PR DESCRIPTION
**Pull request by daschw**
This supercedes #1316 and implements `hline`, `vline` and `Plots.abline` that update automatically with changing axis limits. This is done via a new seriestype `:straightline` which is characterized by two points. The final points to be connected by the `:straightline` are calculated by the new `Plots.straightline_data(series)` in the backend code based on the axes limits of all series.
Similarly, the function `Plots.shape_data(series)` is introduced and called in the backend code to replace infinite values with values far outside the axes limits.
Below you find all the plots produced by executing the following code snippet:
```julia
using Plots
plot(Shape([-Inf, Inf, Inf, -Inf, -Inf], [-Inf, -Inf, 0, 0, -Inf]))
scatter!(randn(10), randn(10))
hline!([0.5])
Plots.abline!(-0.3, 1)
vline!(-5:2.5:5)
ylims!((-5, 5))
```
infinte_1
infinte_2
infinte_3
infinte_4
infinte_5
infinte_6

**NOTE** that these are not really infinite objects: When zooming out the plot area e.g. in Plotly, these objects do not get updated. Maybe it would make sense to have the lines go 10 or 100 times the axes lenghts beyond the axes limits, so people could zoom for a while before reaching the lines' limits?

### CODE REVIEW

**Comment by daschw** [comment]
Plotly still does not correctly update, because series are added individually - not the entire plot is updated. However, I extended the data 100 times beyond the axes limits and the behaviour with this definitely is an improvement to the status quo. GR, PyPlot, PGFPlots, etc. update correctly.

**Comment by piever** [comment]
See also: #1374

**Comment by daschw** [comment]
I added a `hspan` and `vspan` recipe now:
```julia
hspan(1:10)
plot!(randn(20))
vspan!([5, 11])
```
hvspan

**Comment by goretkin** [comment]
Really cool! Is there a way to draw an infinite ray (only extends infinitely in one direction), or does that require a new series type?

**Pull request merged**
