### PR TITLE
Specified some docstrings

### PR DESCRIPTION
**Pull request by mkborregaard**
I've written some docstrings for most exported functions, with the intention of strengthening the REPL help, and to create a markdown API page with all Plots functions in the online docs. 

I've still got some to go, but opening the PR now and welcome comments.

### CODE REVIEW

**Comment by mkborregaard** [comment]
I'll go ahead and merge this unless someone have comments on the docstrings. E.g. are the one-line docstrings sufficient for Documenter, or do you need the multiline ones with the function definition?

**Comment by daschw** [comment]
Sorry, I don't have any experience with Documenter either.

**Comment by mkborregaard** [comment]
I have this hope in me that @ChrisRackauckas will find the time to take care of the gory Documenter setup - then I am happy to do the grunt work on editing docstrings and such 🙏

**Comment by ChrisRackauckas** [comment]
I'll get around to it.

**Comment by mkborregaard** [comment]
Awesome. When you do, please let me know if I need to change somethings about how docstrings are specified. There are currently several methods - maybe would be good to align. Is it easiest for you if i go ahead and merge here?

**Comment by ChrisRackauckas** [comment]
Yes, these should all work fine.

**Pull request merged**
