### PR TITLE
Twiny

### PR DESCRIPTION
**Pull request by mmikhasenko**
adds `twiny()` function that is analogous to `twinx()`
Close https://github.com/JuliaPlots/Plots.jl/issues/2579

### CODE REVIEW

**Comment by isentropic** [comment]
I think we can merge this right away if we have the accompanying docs. Since `twinx`is not even oficially documented, would you please add a new subsection under http://docs.juliaplots.org/latest/layouts/#Adding-Subplots-incrementally and document a brief usage of `twinx, twiny`? Once the corresponing PR with docs lands to PlotDocs repo we can merge both right away.

**Comment by BeastyBlacksmith** [comment]
I am actually a bit hesitant here, because `twinx` is causing a lot of trouble (which may be why it is undocumented so far). I'd prefer having the "providing additional scales" sorted out before adding more of them

**Comment by isentropic** [comment]
That's fair, let's hold on this then

**Comment by mmikhasenko** [comment]
@BeastyBlacksmith 
Are issues with `twinx` collected somewhere?
 - I noticed that it does not work correctly with `pgfplotsx()`, particularly with the `heatmap`

**Comment by BeastyBlacksmith** [comment]
https://github.com/JuliaPlots/Plots.jl/issues?q=is%3Aissue+is%3Aopen+twinx

**Comment by t-bltg** [comment]
Superseded by https://github.com/JuliaPlots/Plots.jl/pull/4488.

**Pull request closed without merging**
