### PR TITLE
implement the recipe_pipeline

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
This is how the new plot call chain would then look like

### CODE REVIEW

**Comment by mkborregaard** [comment]
Travis says there's some dependency stuff

**Comment by BeastyBlacksmith** [comment]
Might be the same issue we have on master?

**Comment by mkborregaard** [comment]
probably

**Comment by BeastyBlacksmith** [comment]
Kristoffer Carlsson (Slack)
Maybe a new version got released that is compatible with your compat but incompatible with one of the test dependencies?

**Comment by mkborregaard** [comment]
I think it's VisualRegressionTests

**Comment by daschw** [comment]
Looks good to me.

**Comment by daschw** [comment]
How do we deal with `_typeAliases` here in this approach?

**Comment by SebastianM-C** [comment]
I also tried to implement the ideas started here at https://github.com/JuliaPlots/Plots.jl/pull/2460
@daschw Regarding the `_typeAliases` I used the approach proposed by @mkborregaard with a kwarg that gets passed from the consumer package.

**Comment by daschw** [comment]
I'll merge this into Michael's branch so we have a common foundation to start from tomorrow.

**Pull request merged**
