### PR TITLE
Colorbar takes font style from Y Axis

### PR DESCRIPTION
**Pull request by AnkurD**
Added some examples for different font types
Source Code Pro:
source_code_pro
Noto Sans:
noto_sans
DejaVu Serif
dejavu_serif

### CODE REVIEW

**Comment by daschw** [comment]
Looks good!
Just FYI: You could have also pushed these changes to the master branch you were using in https://github.com/JuliaPlots/Plots.jl/pull/1098

Since this PR changes the appearance of some test plots, the tests will probably not pass. The next steps would be to install VisualRegressionTests.jl and clone PlotReferenceImages.jl and run the tests locally (https://juliaplots.github.io/contributing/#testing). For some images (in this case the ones with colorbars) you will be prompted a comparison of the old and the new image, and a dialog asking whether to replace the old image with the new one. If you don't see any regression in the new image you can replace the old one. Once you have replaced the images and the tests pass locally you can add the new images (git add), commit and submit a PR to PlotReferenceImages.jl. In that PR please reference this PR. This will ensure that the Plots tests will pass in future.

This probably sounds a little complicated, so if you need any support, just ask here!

**Comment by AnkurD** [comment]
Ah so I did actually make the PR to PlotReferenceImages before I submitted this one, see here: https://github.com/JuliaPlots/PlotReferenceImages.jl/pull/15

**Comment by daschw** [comment]
Ok, great, I did not see this.

**Comment by mkborregaard** [comment]
@AnkurD would you be willing to have a look at implementing this for GR and PlotlyJS if possible? (I couldn't tell if it would be).

**Comment by AnkurD** [comment]
I will do my best to implement this for GR and PlotlyJS as well. It might take a couple weeks as I am about to travel, but I'm glad to still help.

**Comment by mkborregaard** [comment]
awesome!

**Pull request merged**
