### PR TITLE
gr: optimize 'heatmap' logic

### PR DESCRIPTION
**Pull request by jheinen**

### CODE REVIEW

**Comment by yha** [comment]
I think this is superseded by #2299.
Is there a reason to use `GR.cellarray` rather than `GR.drawimage` (which also supports alpha values)?

**Comment by daschw** [comment]
This PR, in the end, only defined a function `is_equally_spaced` that is not used anywhere and probably equivalent to `is_uniformly_spaced` in #2299?

**Comment by jheinen** [comment]
Sorry, my mistake.

**Comment by daschw** [comment]
Don't worry. Should we revert this, or just remove `is_equally_spaced` in a new PR?

**Pull request merged**
