### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by daschw**

### CODE REVIEW

**Comment by daschw** [comment]
Travis tests pass :tada:
Credits to @tkf 's work in #1689!

**Comment by tkf** [comment]
Awesome!!!

**Comment by mkborregaard** [comment]
Wuuuuuuut :tada: 💖

**Comment by mkborregaard** [comment]
(and to @juliohm 's work on VisualRegressionTests)

**Comment by daschw** [comment]
Appveyor is failing because of test image 8 but that is unrelated to the test machinery.

**Pull request merged**
