### PR TITLE
Fix for "segmented" attributes with NaNs

### LINKED ISSUE #3258: [BUG] Scatter plots silently plot wrong data when NaNs are present
## Details

When you plot an XY scatter plot with additional dimensions of data in markers or colors, any NaNs in the XY data will shift the markers and colors and cause Plots to display incorrect data.

I hope this gets immediate attention because I think this is a super serious problem. I very nearly submitted a paper with completely messed up results because of this.

Demo (correct): note that the third circle is large and green.

```
julia> scatter([1,2,3], [3,2,1], markersize=[30,10,30], c=[1,2,3], xlims=(0,4), ylims=(0,4), legend=false)
```
newplot (2)

Now change a coordinate for circle 2 to NaN and note what happens with circle 3.

```
julia> scatter([1,2,3], [3,NaN,1], markersize=[30,10,30], c=[1,2,3], xlims=(0,4), ylims=(0,4), legend=false)
```
newplot (3)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   X  |     |
pyplot       |     |     | X
plotly       |   X  |     |
plotlyjs     |     |     | X
pgfplotsx    |     |     | X
inspectdr    |     |     | X

### Versions

Plots.jl version:  1.10.2
Backend  version (`]st -m`):
Output of `versioninfo()`:
```
julia> versioninfo()
Julia Version 1.6.0-beta1.0
Commit b84990e1ac (2021-01-08 12:42 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = "C:\Program Files\Microsoft VS Code\Code.exe"
  JULIA_NUM_THREADS = 4
  JULIA_PKG_DEVDIR = C:/Stuff
```

### PR DESCRIPTION
**Pull request by yha**
Fixes indexing into attributes that vary by series or data point, so that it is not affected by `NaN` values.
Some examples that previously produced either a `BoundsError` or silently wrong output:
```
plot(plot([2 3; 3 4; 1 NaN; 2 1; 4 2], c=:plasma, fill_z=[1 3], fillrange=0, fillalpha=0.5),
   plot([2 3; 3 4; 1 NaN; 2 1; 4 2], c=:plasma, fill_z=1:5, fillrange=0, fillalpha=0.5),
   scatter([1 2; NaN 3; 4 5], marker_z = [1 2]),
   scatter([1 2; NaN 3; 4 5], marker_z =[1 1; 2 2; 3 3]),
   plot([1 2; 2 3; 4 5], line_z=[1 1; 3 4; 5 6]),
   plot([[1,2,NaN,4,5] 2:6], line_z=[1 2]), 
   legend=false)
```
image

Fixes #3258 (maybe also #2959?).
Breaks the current [reference image 48](http://docs.juliaplots.org/latest/generated/gr/#gr-ref48), but I don't think the current behavior is documented other than in this reference image. As I mentioned in https://github.com/JuliaPlots/Plots.jl/issues/3258#issuecomment-785390216, I think this fix is important enough to break it.

### CODE REVIEW

**Comment by daschw** [comment]
In general, I'd also find this more consistent. However, I'm not sure if this "just" is a bugfix or breaking.
Consider e.g.
```julia
x = [1, 3, 2, NaN, 4, 6, 5, NaN, 0, 1, 1, 0]
y = [2, 2, 3, NaN, 0, 1, 0, NaN, 0, 0, 1, 1]

plot(x, y, st=:shape, fillcolor=[:red, :blue, :green])
plot(x, y, st=:shape, fill_z=1:3)
```
This PR changes
fillcolor_old

to
fillcolor_new

and
fill_z_old

to
fill_z_new

same results for
```julia
xs = [[1, 3, 2], [4, 6, 5], [0, 1, 1, 0]]
ys = [[2, 2, 3], [0, 1, 0], [0, 0, 1, 1]]
shapes = Shape.(xs, ys)

plot(Shape.(xs, ys), fillcolor=[:red, :blue, :green])
plot(Shape.(xs, ys), fill_z=1:3)
```
I wonder if we can keep the old behavior somehow with the changes in this PR (and still be consistent). I can be quite handy. I used it sometimes for plotting shapefile maps and coloring countries according to some values.

**Comment by mkborregaard** [comment]
I agree @daschw , this is a (not necessarily desirable) behaviour change rather than a fix.

**Comment by yha** [comment]
@daschw, I would say that the "before" plots in your first example are definitely a bug. I think that it's extremely surprising that the way indexes in attributes correspond to indexes in data depends in any way on the contents rather than types and shapes. Real data is eventually going to contain `NaN`s which are "real", and not there intentionally to separate segments.
(incidentally, this is more insidious than the cycling behavior of attributes because a) it can crop up after shapes have been debugged, and b) output are less likely to seem obviously wrong: cycled attributes create repetitive patterns in the plots that usually stand out)

The second example is more compelling, and not something I've tested. It's not consistent with the behavior of a plain `plot(xs, ys,...)` (with or without `st=:shape`), but also doesn't seem worth changing, so I'll fix the PR to preserve the behavior for this case.

To deal with the breakage, perhaps we can add a "soft deprecation", i.e. a warning when sizes of "segmenting" attributes don't match, and an extra warning when `NaN`s are present?

**Comment by yha** [comment]
I fixed the `AVec{Shape}` recipe to give the same output as before.
I also added a warning on attribute length mismatch + a hint when the data contains `NaN`s (which is where the output changes with this PR).
```
x = [1, 3, 2, NaN, 4, 6, 5, NaN, 0, 1, 1, 0]
y = [2, 2, 3, NaN, 0, 1, 0, NaN, 0, 0, 1, 1]

plot(x, y, st=:shape, fillcolor=[:red, :blue, :green])
```
gives
```
┌ Warning: Indices Base.OneTo(3) of attribute `fillcolor` does not match data indices 1:12.
└ @ Plots c:\Users\sternlab\.julia\dev\Plots\src\utils.jl:106
┌ Info: Data contains NaNs or missing values, and indices of `fillcolor` vector do not match data indices.
│ If you intend elements of `fillcolor` to apply to individual NaN-separated segements in the data,
│ pass each segment in a separate vector instead, and use a row vector for `fillcolor`. Legend entries 
│ may be suppressed by passing an empty label.
│ For example,
└     plot([1:2,1:3], [[4,5],[3,4,5]], label=["y" ""], fillcolor=[1 2])
```
An alternative would be to merge these message and show them only when the data has `NaN`s. 
My rationale for choosing to display the warning on any dimension mismatch (even when data does not have `NaN`s) was that the current behavior in this case is very messy anyway: e.g. on GR `plot(1:3,1:5)` and `scatter(1:5, marker_z=1:2)` error, `scatter(1:3, 1:5)` truncates `y`, and `scatter(1:5, c=["blue","red"])` cycles.

**Comment by mkborregaard** [comment]
Hmm, I'm being swayed by the good arguments here, sorry for making noise.

**Review by daschw — APPROVED** [review]
Nice, I'm for these changes. Note that this also fixes #3000 and #3117

**Pull request merged**
