### PR TITLE
Update appveyor.yml

### PR DESCRIPTION
**Pull request by jverzani**
add testing on v0.6 with 32 and 64 bit.

### CODE REVIEW

**Comment by jverzani** [comment]
I can do the same for travis and for PlotUtils.jl if that would be helpful.

**Comment by mkborregaard** [comment]
Great! Travis should be up-to-date (I really hope) but PlotUtils'd be nice.

**Comment by mortenpi** [comment]
Perhaps an Appveyor badge should be added into the README too?

**Comment by jverzani** [comment]
Sure, what acct? This one seems to have been used in the past: `
https://ci.appveyor.com/project/tbreloff/plots-jl`, but I would think there
should be an `https://ci.appveyor.com/project/JuliaPlots/plots-jl`.

**Comment by mkborregaard** [comment]
We're just using the tbreloff one

**Comment by ChrisRackauckas** [comment]
>Sure, what acct? This one seems to have been used in the past: `
https://ci.appveyor.com/project/tbreloff/plots-jl`, but I would think there
should be an `https://ci.appveyor.com/project/JuliaPlots/plots-jl`.

You can't set AppVeyor to orgs. It has to be to a personal account.

**Comment by jverzani** [comment]
I checked in a change, but I'm not sure why appveyor hasn't run in the past 7 months. Is there something that needs to be initiated within the repo?

**Comment by mortenpi** [comment]
You need a webhook in the repo. Appveyor creates it when you create a new Appveyor project. I am guessing it has been deleted or disabled.

**Comment by mkborregaard** [comment]
Thanks @jverzani ! I've activated the webhook for Plots and PlotUtils. @mortenpi agreed, a badge in the readme would be cool :-)

**Pull request merged**
