### PR TITLE
add line_z and marker_z example

### PR DESCRIPTION
**Pull request by rdeits**
From discussion with @mkborregaard on gitter

### CODE REVIEW

**Comment by rdeits** [comment]
Looks like I need to update the reference images as well?

**Comment by mkborregaard** [comment]
Great! Yes that's right, you do that by cloning PlotReferenceImages.jl, running Plots' tests manually in an interactive REPL session, then PR the result back to  PlotReferenceImages.jl referring to this.

**Comment by rdeits** [comment]
Ok, done: https://github.com/JuliaPlots/PlotReferenceImages.jl/pull/23

**Comment by rdeits** [comment]
BTW: one inconvenient part of this process was having to manually install the test requirements for Plots in order to run it interactively and get the reference image popups. Perhaps an environment variable would be more use-friendly than checking `isinteractive()` ?

**Comment by mkborregaard** [comment]
Yeah, good point, this could definitely be a lot smoother. If you've got a concrete idea a PR would def be welcome.

**Pull request merged**
