### PR TITLE
Initial implementation for HDF5 plots.

### PR DESCRIPTION
**Pull request by ma-laforge**
Works surprisingly well, with a few limitations

- SeriesAnnotations & GridLayout support known to be missing.

### Write to .hdf5 file:
```
p = plot(...)
Plots.hdf5plot_write(p, "plotsave.hdf5")
```

### Read from .hdf5 file:
```
pyplot() #Must first select backend
pread = Plots.hdf5plot_read("plotsave.hdf5")
display(pread)
```

### CODE REVIEW

**Comment by ma-laforge** [comment]
## Fun test (Plots.jl samples): Violin plot

```
using Plots
using StatPlots #For 25 & 30

hdf5() #Select HDF5-Plots "backend"
TMPFILE = "myplot.hdf5"
idx = 30 #Which "example" plot to display

ex = Plots._examples[idx]
srand(1234) #Make consistent "random" plots.
plotvector = map(eval, ex.exprs)
curplot = plotvector[1]

#Write to HDF5:
Plots.hdf5plot_write(curplot, TMPFILE)

#Read back from HDF5:
#*****************************************************
inspectdr()
p = Plots.hdf5plot_read(TMPFILE)
display(p)

pyplot()
p = Plots.hdf5plot_read(TMPFILE)
display(p)

gr()
p = Plots.hdf5plot_read(TMPFILE)
display(p)

#...
```

**Comment by ma-laforge** [comment]
### HDF5 for Debugging & More

I look at saving a plot to HDF5 as the "binary equivalent" of saving to ASCII.

The HDF5 plot output is "user-readable" - and could be used to re-create a plot even if your program is not really compatible with this particular HDF5 file format.

**HOW?**

Simply download the free HDF5 viewer available on the HDF Group's website:
https://support.hdfgroup.org/products/java/hdfview/

Said viewer will allow you to peruse the structure of the plot file using a convenient tree view widget.

Presumably, Plots.jl developers could use this viewer to help debug issues with new plot features.

It is much easier to inspect plot structures with HDF5view than current Julia debugging tools I am aware of.

**Comment by mkborregaard** [comment]
This is super cool. It strikes me that it may play really nicely together with the design @tbreloff is trying to push at the `reorg` branch, where the Plots/backend interface is more fully modular - have you had a look at that?

**Comment by ma-laforge** [comment]
I was not aware of the `reorg` branch yet.

I took a peek (comparing with `master`):
It appears that @tbreloff is replacing `FixedSizeArrays` with `StaticArrays` - and is changing how modules are loaded.

@mkborregaard:

I am not certain how HDF5 plots will be affected.  Is there a roadmap for the `reorg` branch?

Are you suggesting using HDF5 plots for debugging of new features, or are you giving me a heads up of upcomming changes to the data structures?

**Comment by mkborregaard** [comment]
The `reorg` branch is intended as the new design of Plots for julia-0.6. @tbreloff started it up but it has been quiet for a little while. It is a reorganisation that makes Plots more fully modular, where each backend lives in its own package. That means you only have to install the backends you want, and also makes it easier for people to take ownership for maintaining a single backend. If I understand the plans right, the idea is then that the main Plots package will always produce the exact same object, regardless of what backend is selected, and then pass that to the downstream package (now the Plots object contains the backend-specific object). I just thought it'd be a cool idea to use HDF5 to save this object.

**Comment by tbreloff** [comment]
To expand, the reorg branch's main goal is to be more compatible with 0.6
precompilation. This means reducing the use of eval by moving backend code
into independent modules that can be separately precompiled.

Another nice benefit (in addition to what Mike said) is that we can add
backend-specific dependecies and custom install steps to each backend
package.

The reorg branch is not, however, meant to do the "PlotSpec" redesign.
(Search the issues for PlotSpec for more info) I expect that to happen
independently, if anyone takes on the challenge.

Anyone can help with the reorg branch. Just look at the changes I made for
GR, along with the new PlotsGR.jl package, and make similar changes for the
other backends.

Please... if you're willing to help, step up to the plate and contribute.

**Comment by ma-laforge** [comment]
I was curious about the purpose of that PlotsGR.jl package...

Ok, I got a good idea what the `reorg` branch does.

I took a similar multi-package approach with my own plotting api (not nearly as extensive as Plots.jl).

FYI: I don't see myself tackling this issue at the moment: I have not yet migrated to 0.6.  I am still waiting on a easy-setup Julia package to be deployed... Then I have a bunch of other migrations to do.

### Important comment
Though I find Julia precompilation does like the multi-package approach better, I find it is quite annoying to keep the core library (Plots.jl), and the backend libraries (ex: PlotsGR.jl) in sync.

Conceptually, there is nothing more difficult with this approach, but syncing up 7+ tightly coupled modules is quite annoying.

I really wish Julia supported multi-module git repositories.

...I wonder what was the reason behind this one-module-per-repository architecture...

### PS

The HDF5 plots backend might\*\* not actually need to be a separate backend...

But this allowed me to add the functionnality without adding HDF5 as a dependency.

\*\*I say "might" because I am not quite certain if the `Plot{}` object hierarchy changes depending on the backend.  The intent of HDF5 plots is to save a backend-agnostic plot information to an `.hdf5` file.

**Comment by mkborregaard** [comment]
I *think* that the only backend-specific element is the .o object. There are plans to change that (as Tom said, look for PlotSpec in the issues). I agree it would be cool to save the backend-agnostic plot information, which is the exact reason I thought this would work best with the PlotSpec refactoring.
BTW, would it be possible save to this (subset of hdf5) format instead: https://github.com/simonster/JLD2.jl ?

**Comment by ma-laforge** [comment]
> @mkborregaard: I think that the only backend-specific element is the .o object.

I think so too.... But that makes me wonder why Plots.jl specializes the plot objects (ex: `Plot{PyPlotBackend}`).

Why not simply have a concrete `Plot` object and dispatch functions on `myfunction(::Type{PyPlotBackend}, plt::Plot)` instead?

The .o is of type `Any` either way.

You could even keep things a bit less verbose by passing an object reference to the backend instead of the type:
```
	#Now you must pass an backend object instead of the type itself:
	function myfunction(::PyPlotBackend, plt::Plot)
		...
	end
```


### All I could find on PlotSpec (https://github.com/JuliaPlots/Plots.jl/issues/390)

> @tbreloff: With that said, I have been wanting to store user inputs separate from a fully processed Plot object, and it's likely that your concept would be
appropriate for that. So you'd serialize a PlotSpec, not a Plot.

Not a trivial thing to implement.  This takes alot of knowledge on the internals of Plots.jl - and also insight on the magic going on inside.  I only use a small subset of plots at the moment.  PlotSpec seems to touch a bit of everything  - and will likely require some significant re-structuring.

...Though I might be able to help with some tasks, I would not be a good lead on this at the moment.

### Not sure on the intent of PlotSpec

Plots.jl already has a seperation of "What to plot" (the Plot object) vs "What the backend needs (contained in Plot.o).

This PlotSpec thing sounds alot like how metafiles are defined:

Instead of describing how the image is composed (has a circle of radius 5, and a square of ...) - one describes ***how to draw*** the image (*draw* a circle of radius 5, and *draw* a square of ...).

So instead of saying I "open" a metafile drawing, you are supposed to say I am "playing" a metafile onto a canvas.

I don't really know what's the advantage of this particular software/mental model.

**Comment by ma-laforge** [comment]
I tried using `JLD` at first (It appears that `JLD2` is simply a pure-Julia implementation).

### Issues with `JLD`:

  1. `JLD` is meant to persist objects to `.hdf5` files.  Though this is an ok stop-gap solution for saving plots, we eventually want to move away from being tightly coupled to a particular object hierarchy.
    - Instead, we should (eventually) be trying to specify a file format that has version info.  That way, `.hdfplots` `v1` files could still be read by the `.hdf5plots` `v2` readers.  A well-defined file format is essential if users are ever going to archive their plots for periods longer than a few months (across release cycles).
  2. Outputs I was able to generate using `JLD` were not what I would describe as "human readable".  There were many temporary "groups" and entries that were hard to decipher by a normal human.
    - The intent of `HDF5 Plots` is for someone with a simple `HDF5` viewer to be able to reverse-engineer a reader - if need be.  In other words, the `.hdf5plots` file format should be the binary equivalent of "***saving to ASCII***".

**Comment by mkborregaard** [comment]
I think for PlotSpec this requires @tbreloff to comment on what his plans and ideas are. @tbreloff , if you would at some point write a specification for what would need to happen that would make it a lot easier for someone to come and take the lead on this refactor.

@ma-laforge About JLD2 I don't have a lot of experience with it, but I understood it to be simply a subset of the hdf5 specification - and furthermore I think it will become the future standard data format for all julia data objects. That's why I thought it could be nice to use that, to align across the ecosystem. Are you sure JLD2 has the same issues as you point out for JLD?

**Comment by ma-laforge** [comment]
> @mkborregaard: About JLD2 [...] I think it will become the future standard data format for all julia data objects. [...] Are you sure JLD2 has the same issues as you point out for JLD?

Not sure.  I was not aware of `JLD2 `- it is not yet an official package.  Also: it appears to be compatible with Juila v0.6 only.  I am not yet building for 0.6.  At least not until I get a easy-to-install distribution.

FYI: The following is a screen shot of the HDF5 files written using JLD vs HDF5-plots output.  I created the JLD output by appending the following commands to the code I posted in the second comment of this very PR:

```
using JLD, HDF5
jldopen("test.jld", "w") do file
    g = g_create(file, "plot") # create a group
    g["attr"] = curplot.attr
end
```

jldvshdf5plots

The output on the left is the `JLD` output - and the one on the right (nested) is the `HDF5-plots` output.

I am all for using the standardized JLD/JLD2 library... but I think you'll agree that the output from JLD is unaccpetable if your goal is for HDF5-plots files to act as the "***binary equivalent of saving to ASCII***".

I will gladly use JLD/JLD2 if the output becomes "human friendly".  I would much rather not have to write specific code just to persist a data structure to file.  It is quite a pain.

**Comment by mkborregaard** [comment]
Good point, I agree the HDF5 version is much nicer there. Not sure how JLD2 would work. 
I think this functionality is nice I'd support merging this PR to Plots, but I lack the skills to give it a good review - this is a job for more able people like @tbreloff or @pkofod :-)

**Comment by mkborregaard** [comment]
@ma-laforge I think this is cool and would be ready to merge, if you think it is ready? But would you be willing to keep an eye out for JLD2 and see if that could provide a way to supercede this functionality?

**Comment by ma-laforge** [comment]
Yes: I think it is ready to merge.  At the very least, it should not break anything else - given that it is implemented as a separate backend.

I am definitely willing to replace my own code with something more standardized - particularly if it makes the output file more human readable.

I will keep an eye out for JLD2.  Hopefully it will satisfy the needs of the "binary, readable, single-plot-file" format in the near future.

**Comment by mkborregaard** [comment]
Nice. I don't think the normal test/example system for Plots backends will apply to this, but can you write some tests that will ensure the integrity of the produced objects? And add a description on PlotDocs under the backends tab?

**Pull request merged**
