### PR TITLE
make plotlyjs use html in ijulia

### PR DESCRIPTION
**Pull request by piever**
Fixes [comment](https://github.com/JuliaPlots/Plots.jl/pull/1399#issuecomment-368182008)

### CODE REVIEW

**Comment by piever** [comment]
Second commit seems to fix `plotly` as well. @daschw @mkborregaard maybe give this a go to see if everything works for you as well, this jupyter notebook stuf seems very easy to get wrong...

**Comment by daschw** [comment]
Both plotly and plotlyjs work for me. To be able to save as pdf the user has to specify `fmt = :svg` now so they have to decide between this and interactivity.
Thanks so much for this super fast fix @piever !

**Comment by mkborregaard** [comment]
Awesome!

**Comment by massemanet** [comment]
this fix works fine for me. apologies for breaking plotly.

**Pull request merged**
