### PR TITLE
add ability to specify legend placement to gr backend

### PR DESCRIPTION
**Pull request by wfrgra**

### CODE REVIEW

**Comment by mkborregaard** [comment]
@jheinen did you mention that you planned to base this functionality on GR's `location` keyword instead? How does this relate to that idea?

**Comment by jheinen** [comment]
Yes. we are implementing a "complete" convenience layer. But, this will still take some time ... In a first step (and as a quick solution for `Plots.jl`), you should merge your commit ...

**Comment by mkborregaard** [comment]
Great, will you merge this when it's ready? :-)

**Comment by jheinen** [comment]
Yes. This will allow us to use the same code base for different wrappers (Julia, Python) and environments (console, browser). But it'll take some further development ...

**Comment by jheinen** [comment]
... and that's why the JS wrapper takes some more time than expected :-(

**Comment by mkborregaard** [comment]
thanks, @wfrgra !

**Pull request merged**
