### PR TITLE
basic improvement for pyplot colorbars, WIP

### PR DESCRIPTION
**Pull request by isentropic**

### CODE REVIEW

**Comment by isentropic** [comment]
```
 plot(1:10, marker_z = 10 .^ (1:10), st=:scatter, label="", colorbar_scale=:log10, msw=0, clim=(1, 1e20))
```

image

**Comment by isentropic** [comment]
@BeastyBlacksmith some tests not passing in pgfplotsx backend do you know if it is backend specific?

**Comment by BeastyBlacksmith** [comment]
No, you introduced a method ambiguity here
```
 MethodError: get_linecolor(::RecipesPipeline.DefaultsDict, ::Int64, ::Int64, ::Int64) is ambiguous. Candidates:
    get_linecolor(series, cmin::Real, cmax::Real, i::Int64) in Plots at /home/runner/work/Plots.jl/Plots.jl/src/utils.jl:479
    get_linecolor(series, clims, i::Int64, scale) in Plots at /home/runner/work/Plots.jl/Plots.jl/src/utils.jl:496
  Possible fix, define
    get_linecolor(::Any, ::Real, ::Int64, ::Int64)
```

**Comment by isentropic** [comment]
Is it normal that nightly builds are not successful?

**Comment by BeastyBlacksmith** [comment]
Its not uncommon, in most cases because Gtk is broken

**Comment by t-bltg** [comment]
Superseded by https://github.com/JuliaPlots/Plots.jl/pull/4542.

**Pull request closed without merging**
