### PR TITLE
Update to newer Images

### PR DESCRIPTION
**Pull request by timholy**
The deprecations were in place for 6 months but are now being removed. This may prevent some failures (not tested locally).

https://github.com/JuliaLang/METADATA.jl/pull/10251

### CODE REVIEW

**Comment by timholy** [comment]
Hmm, looks like the second commit may conflict with #970. Let's merge that and then I can fix the depwarns.

**Comment by timholy** [comment]
I made this independent of #970.

**Comment by timholy** [comment]
CC @SimonDanisch

**Comment by SimonDanisch** [comment]
Oh, somehow didn't get this cc.... I guess it's a bit unclear who should approve such changes, so I still haven't merged my PR yet. @mkborregaard, @daschw @tbreloff, should I just go ahead and merge things?

**Comment by daschw** [comment]
Yes, I think this can be merged.

**Comment by mkborregaard** [comment]
@SimonDanisch Yes, you can freely merge anything into glvisualize.jl :-) We'd all just defer to your judgment anyway.

**Pull request merged**
