### PR TITLE
pyplot hexbin

### PR DESCRIPTION
**Pull request by isentropic**
Fixing https://github.com/JuliaPlots/Plots.jl/issues/2491
Currently after my accidental direct commit https://github.com/JuliaPlots/Plots.jl/commit/28ebc0ccd893f39ab9518d181ef8c3852ab02454  this works:

```
 hexbin(rand(1000), rand(1000), thickness_scaling=2, bins=(5,8))
```
Note, color is wrong
image

However, specifying color directly helps
```
hexbin(rand(1000), rand(1000), thickness_scaling=2, bins=(5,8), c=:blues)
```
image

Additionally, `clims` are not calculated correctly too.
I cannot find `hexbin` recipe to try to understand how it gets processed in the `recipes.jl`

### CODE REVIEW

**Comment by daschw** [comment]
I am not familiar with hexbin. What should the color be, a gradient?

**Comment by daschw** [comment]
There is no recipe, pylot is the only backend that supports it. I think you could fix the colors by adding the method `RecipesPipeline.is_surface(::Type{Val{:hexbin}}) = true`.

**Comment by isentropic** [comment]
> 
> 
> I am not familiar with hexbin. What should the color be, a gradient?

it is almost same as 2d histogram, but binned into hexagons

**Comment by isentropic** [comment]
I think this is ready to be merged.
```
hexbin(rand(1000), rand(1000), thickness_scaling=2, bins=(15,6), linewidth=1)
```
image

This is still at the early stage, as there is no support for `clims` as binning is not trivial. Heck even, the number of bins is not intuitive to understand, but it now at least plots something for anyone who is interested in hexbins. It looks pretty but definitely not easy to implement from scratch, from recipes.

**Pull request merged**
