### PR TITLE
conserve extra_kwargs

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
Fix https://github.com/JuliaPlots/Plots.jl/issues/2884

### CODE REVIEW

**Comment by korsbo** [comment]
Hi, now I get an even earlier error 
```julia
julia> plot(x->x, -1:1; add = raw"\node at (0,0.5) {\huge hi};", extra_kwargs = :subplot)                                           Error showing value of type Plots.Plot{Plots.PGFPlotsXBackend}: 
                                                                ERROR: ArgumentError: No tex function available for data of type Dict{Symbol,Any}. Define one by overloading print_tex(io::IO, data::T) where T is the type of the data to dispatch on.                                                                                 Stacktrace:                                                                                                                          [1] print_tex(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Dict{Symbol,Any}) at /home/niklas/.julia/packages/PGFPlotsX/rS8LC/src/PGFPlotsX.jl:101                                                                                                                          [2] print_tex(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Dict{Symbol,Any}, ::PGFPlotsX.Axis) at /home/niklas/.julia/packages/PGFPlotsX/rS8LC/src/PGFPlotsX.jl:42                                                                                                         [3] (::PGFPlotsX.var"#53#54"{PGFPlotsX.Axis,Array{Any,1}})(::Base.GenericIOBuffer{Array{UInt8,1}}) at /home/niklas/.julia/packages/PGFPlotsX/rS8LC/src/axislike.jl:38                                                                                                   [4] print_indent(::PGFPlotsX.var"#53#54"{PGFPlotsX.Axis,Array{Any,1}}, ::IOStream) at /home/niklas/.julia/packages/PGFPlotsX/rS8LC/src/utilities.jl:29                                                                                                                  [5] print_tex at /home/niklas/.julia/packages/PGFPlotsX/rS8LC/src/axislike.jl:36 [inlined]                                          [6] print_tex(::IOStream, ::PGFPlotsX.Axis, ::PGFPlotsX.TikzPicture) at /home/niklas/.julia/packages/PGFPlotsX/rS8LC/src/PGFPlotsX.jl:42                                                                                                                                [7] print_tex(::IOStream, ::PGFPlotsX.TikzPicture) at /home/niklas/.julia/packages/PGFPlotsX/rS8LC/src/tikzpicture.jl:28            [8] print_tex(::IOStream, ::PGFPlotsX.TikzPicture, ::PGFPlotsX.TikzDocument) at /home/niklas/.julia/packages/PGFPlotsX/rS8LC/src/PGFPlotsX.jl:42                                                                                                                        [9] print_tex(::IOStream, ::PGFPlotsX.TikzDocument; include_preamble::Bool) at /home/niklas/.julia/packages/PGFPlotsX/rS8LC/src/tikzdocument.jl:145                                                                                                                     [10] #savetex#69 at /home/niklas/.julia/packages/PGFPlotsX/rS8LC/src/tikzdocument.jl:121 [inlined]                                  [11] #67 at /home/niklas/.julia/packages/PGFPlotsX/rS8LC/src/tikzdocument.jl:104 [inlined]                                          [12] open(::PGFPlotsX.var"#67#68"{Bool,PGFPlotsX.TikzDocument}, ::String, ::Vararg{String,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./io.jl:298                                                                      [13] open at ./io.jl:296 [inlined]       
...              
```

**Comment by korsbo** [comment]
The formatting is terrible, but my terminal has decided to act up today...

**Comment by BeastyBlacksmith** [comment]
Should be fixed now 😅

**Comment by korsbo** [comment]
Thanks, for fixing this and for making the the already great Julia ecosystem better!

**Pull request merged**
