### PR TITLE
Legends documentation and some todos

### PR DESCRIPTION
**Pull request by isentropic**
Closes: https://github.com/JuliaPlots/Plots.jl/issues/2207
I'll add a `good first issue` for plotly legends once this gets merged. I believe [this](https://github.com/JuliaPlots/Plots.jl/blob/c2df99cc6600f7fc0c6564d98fc3473c1c77519f/src/backends/plotly.jl#L340) should implemented properly as in [here](https://github.com/JuliaPlots/Plots.jl/blob/c2df99cc6600f7fc0c6564d98fc3473c1c77519f/src/backends/gr.jl#L567)

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
I don't see the benefit of adding todo comments to the code over opening an issue.
Also the GR legend implementation has quite a few bugs.
Non-exhaustive list:
#2377, #2369, 2330, #2202, #1776, #1589

**Comment by isentropic** [comment]
Removed the `todo` comment

**Comment by BeastyBlacksmith** [comment]
Thats fine, I just would't take it as a _proper_ reference implementation.

**Comment by isentropic** [comment]
> Thats fine, I just would't take it as a _proper_ reference implementation.

I'll then open `good first issue` without referencing the gr implementation. Improving [this](https://github.com/JuliaPlots/Plots.jl/blob/c2df99cc6600f7fc0c6564d98fc3473c1c77519f/src/backends/plotly.jl#L340) be straightforward for a new contributor

**Comment by isentropic** [comment]
I believe [this](https://github.com/JuliaPlots/Plots.jl/blob/c2df99cc6600f7fc0c6564d98fc3473c1c77519f/src/backends/pgfplotsx.jl#L666) is a better example. @BeastyBlacksmith 

I also have a question now, why does `pgfplotx` default to `outertopright` I thought about doing the same with `plotly` but then, as all other backends default to `topright` (within) the plot, I decided that it should default to `topright`

PS.
I'm impressed how well `pgfplotsx` handles colorbar positioning and margins, something I could not really achieve in https://github.com/JuliaPlots/Plots.jl/pull/2772

**Comment by BeastyBlacksmith** [comment]
The actual default value for legend positioning is `:best`, which leaves room for interpretation.
You might know that `pyplot` for example places the legend where the most white space is when it would hide data.
So `:outertopright` is what seemed `best` to me, when implementing the backend, which is not always ideal as some examples in the documentation show.

**Comment by isentropic** [comment]
Perhaps then, plotly should fallback to outerright as best too. I thought best really means topright unless the backend has a better idea

**Comment by isentropic** [comment]
> The actual default value for legend positioning is `:best`, which leaves room for interpretation.
> You might know that `pyplot` for example places the legend where the most white space is when it would hide data.
> So `:outertopright` is what seemed `best` to me, when implementing the backend, which is not always ideal as some examples in the documentation show.

I believe that `pgfplotsx()` should default to `topright` to match GR. https://github.com/JuliaPlots/Plots.jl/blob/709a8a96093b512693b8703d195b5a5da0636a13/src/backends/gr.jl#L571

topright still takes around 10% of the plotarea so it should not be a problem. If a user desires they can manually position the legend
@BeastyBlacksmith

**Pull request merged**
