### PR TITLE
Allow relative positioning of annotations

### PR DESCRIPTION
**Pull request by t-bltg**
Allow using `pct` for relative positioning of annotations.

Note that this also fixes https://github.com/JuliaPlots/Plots.jl/issues/2728#issuecomment-875432563, but NOT https://github.com/JuliaPlots/Plots.jl/issues/3633.

~~Before going forward with this, I think we should discuss https://github.com/JuliaPlots/Plots.jl/issues/3635 (I would prefer writing `3Plots.pct` instead of `.03Plots.pct`).~~

Fix https://github.com/JuliaPlots/Plots.jl/issues/2728.

MWE
----
```julia
using Plots; gr()
using Random; Random.seed!(1234)

main() = begin
  p = plot(
    plot(rand(10) .* 15, aspect_ratio=:equal),
    plot(rand(10) .* 10, aspect_ratio=:equal),
    legend=false, layout=grid(1, 2), frame=:box
  )
  annotate!(sp=1, (.03, .95), text("Cats&Dogs", :left))
  annotate!(sp=2, (.03, .95), text("Cats&Dogs", :left))
  png("annotate")
end

main()
```

Output
----
annotate

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
I'd prefer not to expose `Plots.pct` to the user, this makes using it in recipes hard

**Comment by t-bltg** [comment]
> I'd prefer not to expose `Plots.pct` to the user, this makes using it in recipes hard

How ?

**Comment by BeastyBlacksmith** [comment]
> How ?

You dispatch on some type in Base or RecipesBase first in this case maybe `Tuple{<:Number, <:Number}` if it unambiguous.

**Comment by t-bltg** [comment]
> I'd prefer not to expose Plots.pct to the user, this makes using it in recipes hard

I'm not following you: there is no change in exposing `pct` here. It remains un-exported.

> You dispatch on some type in Base or RecipesBase first in this case maybe `Tuple{<:Number, <:Number}` if it unambiguous.

There is no dispatch in `RecipesBase` nor `Base` here: dispatching occurs in `Plots.jl/src/compnents.jl`, in `locate_annotation`, which is perfectly unambiguous here.

**Comment by BeastyBlacksmith** [comment]
> > I'd prefer not to expose Plots.pct to the user, this makes using it in recipes hard
> 
> I'm not following you: there is no change in exposing `pct` here. It remains un-exported.

You are right with that, but a user is required to use `Plots.pct` for this feature. And since recipes are required to work without loading Plots, this feature cannot be used in recipes. Thats why you need a different user facing type for the call.

For example 
```julia
annotate!(sp=1, (.03, .95), text("Cats&Dogs", :left))
```

**Comment by t-bltg** [comment]
> And since recipes are required to work without loading Plots, this feature cannot be used in recipes. Thats why you need a different user facing type for the call.

Thanks for the explanation, that makes sense.

I've reworked the PR to work with `Tuple`, and simplified `process_annotation`, and updated the [MWE](https://github.com/JuliaPlots/Plots.jl/pull/3634#issue-686183860): let's see if this does break `Plots` or if the CI passes.

**Comment by BeastyBlacksmith** [comment]
Would be good to add a test for this otherwise LGTM

**Review by BeastyBlacksmith — APPROVED** [review]

**Comment by mmikhasenko** [comment]
Many thanks, this extremely useful feature!

**Comment by drandran12** [comment]
Is there a way we could implement the same feature for 3 dimensional plots?

**Comment by BeastyBlacksmith** [comment]
Its usually better to open a feature request issue rather than comment on a closed PR, since this will get lost more easily

**Comment by SteffenMuehle** [comment]
Alright, will do!

**Pull request merged**
