### PR TITLE
initial port of `pyplot` to `pythonplot`

### PR DESCRIPTION
**Pull request by t-bltg**
Fix https://github.com/JuliaPlots/Plots.jl/issues/4181.
Fix https://github.com/JuliaPlots/Plots.jl/issues/3580.

Supersedes https://github.com/JuliaPlots/Plots.jl/pull/3620.

Needs https://github.com/JuliaPlots/Plots.jl/pull/4558, https://github.com/JuliaPlots/Plots.jl/pull/4548.

@stevengj, it would be great to have a first registered release of `PythonPlot` in the `general` registry in order to be able to test and enhance this.
I'm too lazy to modify `ci` to `dev` `PythonPlot` :smiley: .

```julia
using Plots
pythonplot()

# no failing examples
map(i -> Plots.test_examples(i; disp=true), 1:length(Plots._examples));

# all examples now look correct, w.r.t. docs.juliaplots.org/stable/gallery/pyplot
map(i -> png(Plots.test_examples(i), "pp-" * lpad(i, 2, '0')), 1:length(Plots._examples));
```

### CODE REVIEW

**Comment by t-bltg** [comment]
A note on performance:
```julia
using Plots

foreach(_ -> @time(map(i -> Plots.test_examples(:pythonplot, i), 1:length(Plots._examples))), 1:2)
 # ...
 62.069181 seconds (8.05 M allocations: 453.226 MiB, 0.66% gc time, 5.20% compilation time)

foreach(_ -> @time(map(i -> Plots.test_examples(:pyplot, i), 1:length(Plots._examples))), 1:2)
  # ...

```

**Comment by t-bltg** [comment]
> I'll try to remember to register PythonPlot this weekend.

Thanks !

> How does this affect the time-to-first-plot? 

There is room for improvement. With the transition to `Prefences.jl` mechanism (hopefully soon ?) we should be able to precompile `Plots` for a chosen backend (not only `GR`), so that would help a lot.

```julia
using Plots

@time pyplot()
 16.649075 seconds (19.01 M allocations: 1.072 GiB, 3.22% gc time, 89.08% compilation time: 43% of which was recompilation)
@time display(plot(1:2))
 15.000071 seconds (20.71 M allocations: 1.078 GiB, 4.42% gc time, 93.85% compilation time: 15% of which was recompilation)
```

```julia
using Plots
@time pythonplot()
 22.544933 seconds (24.63 M allocations: 1.376 GiB, 2.98% gc time, 86.94% compilation time: 55% of which was recompilation)
@time display(plot(1:2))
 15.776150 seconds (21.62 M allocations: 1.120 GiB, 3.99% gc time, 94.55% compilation time: 15% of which was recompilation)
```

**Comment by t-bltg** [comment]
@stevengj, so that you don't forget :slightly_smiling_face:

**Comment by stevengj** [comment]
https://github.com/JuliaRegistries/General/pull/73033

**Comment by t-bltg** [comment]
Here is are new measurements, after the discussion in https://github.com/cjdoris/PythonCall.jl/issues/45:

```julia
julia> using Plots
julia> @time pyplot();
 16.139387 seconds (18.85 M allocations: 1.063 GiB, 3.85% gc time, 89.03% compilation time: 44% of which was recompilation)
julia> @time display(plot(1:2))
 15.438185 seconds (21.25 M allocations: 1.108 GiB, 6.98% gc time, 94.30% compilation time: 15% of which was recompilation)
```

==> `PyPlot` / `PyCall` ttfp: `~31.5s`

```julia
julia> using Plots
julia> @time pythonplot();
 16.612395 seconds (15.54 M allocations: 944.050 MiB, 2.86% gc time, 84.67% compilation time: 31% of which was recompilation)
julia> @time display(plot(1:2))
 14.738200 seconds (16.74 M allocations: 882.437 MiB, 6.26% gc time, 94.05% compilation time: 8% of which was recompilation)
```

==> `PythonPlot` / `PythonCall` ttfp: `~31.3s`

Slight improvement :tada: .

**Pull request merged**
