### PR TITLE
Changes to get glvisualize backend running on v0.7

### PR DESCRIPTION
**Pull request by lwabeke**
Only tested basic line plot, scatter, heatmap and contour

Now seems to work both in Repl and from IJulia.

### CODE REVIEW

**Comment by mkborregaard** [comment]
It shouldn't add a dep on GLWindow. All those packages would have to be eval-imported when activating the backend.

**Comment by SimonDanisch** [comment]
I've seen you opened commits at GLWindow/GLVisualize/GLAbstraction... Did you see that I deprecated GLVisualize in favor of [Makie](https://github.com/JuliaPlots/Makie.jl) ?
Sorry if this isn't very visible...
Also Makie has it's own version of [GLAbstraction & GLVisualize](https://github.com/JuliaPlots/Makie.jl/tree/master/src/glbackend) in it. So maybe the easiest way to get the GLVisualize backend up to date would be - to use a Makie backend :P

**Comment by mkborregaard** [comment]
@SimonDanisch is it time to deprecate the glvisualize backend to Plots altogether?

**Comment by SimonDanisch** [comment]
>is it time to deprecate the glvisualize backend to Plots altogether?

Let's do such things at Vizcon :)

**Comment by lwabeke** [comment]
I missed the Makie notice initially (only saw it after having made all the changes), but also don't see thre Makie backend for the Plots library.

**Comment by daschw** [comment]
[Makie](https://github.com/JuliaPlots/Makie.jl) is a different package, not a Plots backend. It will most likely be the Plots successor and also support different backends. Plots will no longer support the glvisualize backend.

**Comment by mkborregaard** [comment]
That backend has now been formally deprecated. Sorry @lwabeke

**Pull request closed without merging**
