### PR TITLE
allow to set the theme in PLOTS_DEFAULTS

### PR DESCRIPTION
**Pull request by daschw**

### CODE REVIEW

**Comment by mkborregaard** [comment]
Awesome. Should we think about what to do when a PLOTS_DEFAULTS entry collides with one in the theme?

**Comment by daschw** [comment]
The theme entries are overwritten by the `PLOTS_DEFAULTS` entries.
However, once the user calls `theme(thm)`, all `PLOTS_DEFAULTS` entries that are also specified by `thm` are overwritten.
I think that makes sense.

**Comment by mkborregaard** [comment]
Cool.

**Comment by mkborregaard** [comment]
But does that mean that mean that which Plots defaults will be overridden here depends on the order in which they are located in the PLOTS_DEFAULT Dict here? Because of the call to `theme()`?

**Comment by daschw** [comment]
No, first `theme(PLOTS_DEFAULTS[:theme])` is called and then all the other elements from `PLOTS_DEFAULTS` are applied.

**Comment by mkborregaard** [comment]
billede

ehh.

**Comment by mkborregaard** [comment]
Sorry :joy:

**Comment by daschw** [comment]
> However, once the user calls theme(thm), all PLOTS_DEFAULTS entries that are also specified by thm are overwritten.

The question, if this makes sense. (?) But that's not really related to this PR.

**Comment by mkborregaard** [comment]
I think it does

**Pull request merged**
