### PR TITLE
Reduce load time for Plots and GR backend

### PR DESCRIPTION
**Pull request by oschulz**
Before (first iteration includes precompilation):

```
$ for i in 1 2 3; do julia -e '@time using Plots; @time gr()'; echo ""; done
 21.354106 seconds (7.32 M allocations: 399.074 MiB, 0.86% gc time)
  1.634413 seconds (3.83 M allocations: 182.663 MiB, 2.60% gc time)

  3.228041 seconds (6.66 M allocations: 366.071 MiB, 4.46% gc time)
  1.648726 seconds (3.83 M allocations: 182.680 MiB, 3.02% gc time)

  3.227100 seconds (6.66 M allocations: 366.071 MiB, 4.47% gc time)
  1.650179 seconds (3.83 M allocations: 182.680 MiB, 3.01% gc time)
```

After, together with JuliaPlots/PlotUtils.jl#52:

```
$ for i in 1 2 3; do julia -e '@time using Plots; @time gr()'; echo ""; done
 20.168409 seconds (5.59 M allocations: 310.754 MiB, 0.84% gc time)
  0.172687 seconds (100.31 k allocations: 4.962 MiB)

  2.634659 seconds (4.93 M allocations: 277.299 MiB, 4.97% gc time)
  0.171456 seconds (100.30 k allocations: 4.957 MiB)

  2.633986 seconds (4.93 M allocations: 277.301 MiB, 4.97% gc time)
  0.174178 seconds (100.30 k allocations: 4.957 MiB)
```

Time to first plot is still horrible, but at least it makes loading Plots and selecting the backend at the top of one's script/notebook a bit less painful.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Bump. Any reason not to rebase and merge this?

**Comment by oschulz** [comment]
I've been using this for a while now, should be fine to merge. I'll also get back on JuliaPlots/PlotUtils.jl#52 and implement the change @JeffBezanson suggested.

**Comment by mkborregaard** [comment]
Great - would you mind rebasing and resolving the conflicts so we can merge?

**Comment by oschulz** [comment]
Will do.

**Comment by mkborregaard** [comment]
ready to merge this once it's been rebased - @oschulz :-)

**Comment by oschulz** [comment]
Rebase done - was a non-trivial merge, there were several conflicts, I hope I didn't break anything.

**Comment by oschulz** [comment]
If this gets merged, JuliaPlots/PlotUtils.jl#52 should be merged to.

**Comment by mkborregaard** [comment]
But it's safe to merge the PlotUtils PR without this?

**Comment by oschulz** [comment]
Yes, JuliaPlots/PlotUtils.jl#52 is independent (but contributes a bit to the faster load time).

**Pull request merged**
