### PR TITLE
gr: add support for user fonts

### PR DESCRIPTION
**Pull request by jheinen**

### CODE REVIEW

**Comment by t-bltg** [comment]
Does GR have a font cache mechanism ?
`gr_set_font` is called a lot and `GR.loadfont` might be costly (I haven't checked) ?

**Comment by jheinen** [comment]
Yes, there is a font cache mechanism in GR. This MR only adds support for additional/other fonts in the user's or the system-wide font directories - `GR.loadfont()` is only called once in this case and the font dictionary is extended.

**Review by t-bltg — APPROVED** [review]

**Comment by BeastyBlacksmith** [comment]
Do we need to bump compat or would this also work with GR v0.69.5?

**Comment by jheinen** [comment]
> Do we need to bump compat or would this also work with GR v0.69.5?

No, the `GR.loadfont` function was already introduced in version 0.64.3.

**Pull request merged**
