### PR TITLE
RecipesBase change: all recipes usable from RecipesBase

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by mkborregaard** [comment]
To all open PRs: Due to the change to 0.6 it appears that all PRs will have to be rebased onto master (and conflicts resolved) for Travis tests to run.

**Comment by mkborregaard** [comment]
Did you rebase this too?

**Comment by ChrisRackauckas** [comment]
Yes.

**Comment by mkborregaard** [comment]
Right - the tests fail because of the interconnected PRs. I'm gonna trust the integrity and merge them all - be ready for some fire-stopping if it blows up :-)

**Pull request merged**
