### PR TITLE
gr: use correct colorbar() routine

### PR DESCRIPTION
**Pull request by jheinen**

### CODE REVIEW

**Comment by mkborregaard** [comment]
@jheinen , the color bar scale appears to always scale from 0 to 1, instead of the actual values in the data.

**Comment by mkborregaard** [comment]
Plotlyjs:
skaermbillede 2017-05-08 kl 13 54 09
GR:
skaermbillede 2017-05-08 kl 13 54 28

**Comment by jheinen** [comment]
@mkborregaard : Is this a heatmap plot? I'm asking because there seem to be different methods in `Plots.jl` to draw the colorbar, either as a series of discrete low-level `GR` functions or by using the `GR.colorbar()` method.

**Comment by mkborregaard** [comment]
yes, that is a heatmap

**Comment by jheinen** [comment]
Ok, I'll check that this evening - I'm currently GMT-7 ...

**Comment by mkborregaard** [comment]
Awesome!

**Pull request merged**
