### PR TITLE
Proposes a 3D quiver

### PR DESCRIPTION
**Pull request by kellertuer**
This PR introduces a quiver functionality (at least partially, see below) for 3D quivers, cf. #319.

This extension can be seen by looking at
```julia
using Plots
x = [1.0, 2.0, 3.0]
y = [0.0, 1.0, 0.0]
z = [1.0, 0.0, 0.0]
u = [1.0, 1.0, 1.0]
v = [0.5, 0.5, 0.5]
w = [0.0, 0.0, 1.0]
s = quiver(x,y,z, quiver=(u,v,w))
```

which was previously a little strange (took `x` and `z` but `u` and `w`, first and last quiver component)
pre

and now it correctly looks like
post

Works/tested with
* GR
* PyPlot

## Questions
* What would be the best way to hack an arrow in 3D to make it work e.g. with `Plotly`?
* Which tests are required here?

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
That is a really good addition. I don't know about plotly, but as a test it would be sufficient to add an example at the end of the examples array here https://github.com/JuliaPlots/Plots.jl/blob/master/src/examples.jl, add the number to the excludes of the backends where it doesn't work and then do a PR against PlotReferenceImages to add the reference image for the GR backend.

**Comment by kellertuer** [comment]
Thanks, I have to check how one can add things to that list, but then I'll do that for sure.

**Comment by kellertuer** [comment]
Uh, nice! I was just starting to test and got lost in GR arrow head sizes and (maybe) missing scaling of quivers, when I wanted to add a 2D example (found a bug in my code, too). Will update/merge that here, then.

**Comment by daschw** [comment]
I'm sorry about that commit mess above. I added a new test example. I hope that's fine.
```julia
using Plots

ϕs = range(-π, π, length=50)
θs = range(0, π, length=25)
θqs = range(1, π-1, length=25)

x = vec([sin(θ) * cos(ϕ) for (ϕ, θ) in Iterators.product(ϕs, θs)])
y = vec([sin(θ) * sin(ϕ) for (ϕ, θ) in Iterators.product(ϕs, θs)])
z = vec([cos(θ) for (ϕ, θ) in Iterators.product(ϕs, θs)])

u = 0.1 * vec([sin(θ) * cos(ϕ) for (ϕ, θ) in Iterators.product(ϕs, θqs)])
v = 0.1 * vec([sin(θ) * sin(ϕ) for (ϕ, θ) in Iterators.product(ϕs, θqs)])
w = 0.1 * vec([cos(θ) for (ϕ, θ) in Iterators.product(ϕs, θqs)])

quiver(x,y,z, quiver=(u,v,w))
```
quiver3

**Comment by kellertuer** [comment]
oh, what a neat example!

**Comment by kellertuer** [comment]
I was thinking about adding a 2D quiver example, too, but got lost since this
```
using Plots
xr = range(-π, π, length=41)
yr = range(-π, π, length=41)

X = vec([ x for x ∈ xr, y ∈ yr])
Y = vec([ y for x ∈ xr, y ∈ yr])
U = vec([ 0.12*sin(x)*cos(y) for x ∈ xr, y ∈ yr])
V = vec([ 0.12*cos(x)*sin(y) for x ∈ xr, y ∈ yr])

s = quiver(X, Y, quiver=(U,V))
```
has huge arrowheads in `GR`.
And maybe for another PR one could also introduce an auto-down/up-scaling option of the vectors (I think both peplos and Matlab do this)

**Comment by daschw** [comment]
I think we can also investigate the arrowhead size issue and the 2D example in another issue/PR.

**Comment by daschw** [comment]
I like the auto-scaling idea.

**Comment by kellertuer** [comment]
Ok, sure.
For auto-scaling I have an idea, I will think about it and propose something maybe next week – something along the lines of „scale down to the longest vector being as long as the smallest distance of domain points.“

**Comment by daschw** [comment]
Thanks for your contribution @kellertuer !

**Pull request merged**
