### PR TITLE
Change cycle => _cycle

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
There is a Base function named `cycle` which this is not. This makes the code rather confusing, especially since `Base.cycle` is used in other places. Additionally, this is then imported in other libraries, meaning it's an important function. This changes the name of this function to `_cycle` instead of shadowing the Base function to improve code clarity.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Yes, though it's breaking to StatPlots which explicitly imports it, so that PR would need to follow.

**Comment by mkborregaard** [comment]
good point - let's make sure the merges are simultaneous and followed by a concerted release.

**Comment by mkborregaard** [comment]
To all open PRs: Due to the change to 0.6 it appears that all PRs will have to be rebased onto master (and conflicts resolved) for Travis tests to run.

**Comment by mkborregaard** [comment]
and this?

**Comment by ChrisRackauckas** [comment]
Yes.

**Pull request merged**
