### PR TITLE
add recipes for time periods

### PR DESCRIPTION
**Pull request by wfrgra**
Could be improved by applying the recipes to the Period supertype if that works in recipes. I couldn't figure out the syntax.

### CODE REVIEW

**Comment by daschw** [comment]
How about
```julia
@recipe f(::Type{P}, t::P) where P <: Dates.Period = (t -> Dates.value(t), t -> string(P(t)))
```
instead?

**Comment by wfrgra** [comment]
Much nicer, cheers

**Comment by daschw** [comment]
Are you still planning to update this PR, @wfrgra ?

**Comment by asinghvi17** [comment]
bump

**Pull request merged**
