### PR TITLE
fix gr_display (close #2026)

### LINKED ISSUE #2026: "i not defined" in `gr_display` function
Hello, I encounter an error "i not defined" when building doc using `Plots` (v0.25.0) and track it down here:

https://github.com/JuliaPlots/Plots.jl/blob/f742ae4c8850b6d9d665df84f06226882c33be47/src/backends/gr.jl#L858-L866

Should `i` in line 863 be replaced with `legendi`?

Thanks!

### PR DESCRIPTION
**Pull request by shipengcheng1230**
Refer: https://github.com/JuliaPlots/Plots.jl/issues/2026

### CODE REVIEW

**Comment by daschw** [comment]
Awesome, thanks!

**Comment by NHDaly** [comment]
Thanks for fixing this! :)

**Comment by NHDaly** [comment]
Can we tag a release with this fix? (It's currently broken on the released version.)

**Comment by daschw** [comment]
https://github.com/JuliaRegistries/General/pull/719

**Pull request merged**
