### PR TITLE
Change dep to julia 0.7 and add Dates to Require

### PR DESCRIPTION
**Pull request by mkborregaard**

### CODE REVIEW

**Comment by daschw** [comment]
Are you sure dates belongs in require?

**Comment by mkborregaard** [comment]
Oh was that too fast? I'm still learning the new package manager (struggled a lot with it this morning, and e.g. ended up committing directly to master by accident). It was just my julia session that told me that this was a problem.

**Comment by daschw** [comment]
AFAIK standard library packages like Dates don't belong to REQUIRE. Maybe @fredrikekre can confirm?

**Comment by mkborregaard** [comment]
I'll take it out. I should have read the manual before acting.

**Comment by fredrikekre** [comment]
Dates should not be in there, now this will reference the old Dates package from Julia 0.3 or something.

**Comment by daschw** [comment]
Thanks!

**Comment by mkborregaard** [comment]
Thanks. There was a warning when loading Plots on a fresh install that was a bit hard to interpret. I'll take it out.

**Pull request merged**
