### PR TITLE
work around CI caching issues

### PR DESCRIPTION
**Pull request by simeonschaub**

### CODE REVIEW

**Comment by simeonschaub** [comment]
Alternatively, we might want to try @giordano's suggestion in https://github.com/julia-actions/cache/issues/42#issuecomment-1374495622 and just downgrade instead of removing caching alltogether

**Comment by t-bltg** [comment]
@simeonschaub, do you want a wipeout of caches in https://github.com/JuliaPlots/Plots.jl/actions/caches ?

**Comment by simeonschaub** [comment]
Yes, let's try that

**Comment by t-bltg** [comment]
> Yes, let's try that

Done.

**Comment by simeonschaub** [comment]
@t-bltg could you rerun CI once the first run finishes? We should make sure that caching works properly now

**Comment by t-bltg** [comment]
I've opened a dummy PR at https://github.com/JuliaPlots/Plots.jl/pull/4625.

**Comment by giordano** [comment]
I'm not sure cache is hit on different branches/PR until it's in the default branch.

**Comment by t-bltg** [comment]
Re-running failing ci in https://github.com/JuliaPlots/Plots.jl/pull/4615 now.

**Comment by simeonschaub** [comment]
Sorry, I meant rerunning CI just on this branch, but as @giordano says, this might not actually do anything. I propose that we just merge this if CI passes and then verify by creating a PR on top of that new master branch

**Comment by t-bltg** [comment]
Deleting the cache seems to have worked:

https://github.com/JuliaPlots/Plots.jl/actions/runs/3859523069/jobs/6579133488 (failing)
vs
https://github.com/JuliaPlots/Plots.jl/actions/runs/3859523069/jobs/6584314006 (running)

**Comment by simeonschaub** [comment]
Yes, but I believe that's just due to it now not using any cache at all. Once another cache is created with julia-actions/cache v1.2 on master again, I'd expect those jobs to fail as before, so we should merge this before any other commits are merged into the main branch.

**Comment by simeonschaub** [comment]
Looks like this worked. Should be good to merge, but immediately before merging we should delete the caches again, because it looks like those other retriggered jobs created new caches.

**Comment by t-bltg** [comment]
In the end I don't think this PR is necessary.
I've re-run some failing jobs on previous commits in master using new cache files, and we'll see if ci fails again or not.

**Comment by simeonschaub** [comment]
If you look in the CI logs, those are all not hitting any existing caches though. So just rerunning a bunch of failed jobs without a plan is a bit counter-productive right now, because it doesn't trigger the original issue and just creates more potentially corrupt cache files for later jobs

**Comment by t-bltg** [comment]
> If you look in the CI logs, those are all not hitting any existing caches though

https://github.com/JuliaPlots/Plots.jl/pull/4626 hits caches correctly.

**Pull request closed without merging**
