### PR TITLE
Update series args using plot!

### LINKED ISSUE #2851: [FR] Way to modify series labels after plot creation.
Currently labels have to be added at the same time the series data is plotted. Other attributes like titles and axis labels can be added and modified after the fact. I would like to be able to add and modify the legend after plot creation also. 

Ideally, this would be done in the same way as other attributes like `plot!(labels=stringarrayoflabels)`, but a new function like `labels!(stringarrayoflabels)` could work too.

This would be most helpful to me when a plot is created within a function, but I want to be able to pretty it up outside of the function to avoid passing a lot of variables back and forth.

### PR DESCRIPTION
**Pull request by Diaga**
Fixes #2851 as well.

```julia
begin
    default(titlefont = (20, "times"), legendfontsize = 18, guidefont = (18, :darkgreen), tickfont = (12, :orange), guide = "x", framestyle = :zerolines, yminorgrid = true)
    plot([sin, cos], -2π, 2π, label = ["sin(θ)" "cos(θ)"], title = "Trigonometric Functions", xlabel = "θ", linewidth = 2, legend = :outerbottom)
    plot!(label=["cos(θ)" "sin(θ)"], arrow=(:closed, 2.0))
end
```

Before:
2851-before

After: (Notice changed legend labels and arrows)
2851-after

### CODE REVIEW

**Comment by Diaga** [comment]
May need documentation somewhere, if it should be merged.

**Comment by BeastyBlacksmith** [comment]
Would be nice to add some tests.
This doesn't address the case mentioned in https://github.com/JuliaPlots/Plots.jl/issues/2741, does it?

**Comment by Diaga** [comment]
Was tricky setting up LaTeX. No, it does not address #2741. 
Previously, series args could not be modified using ```plot!``` after initial plot creation. This PR allows updating of series.

**Comment by BeastyBlacksmith** [comment]
Just linking my PR for a few cases that one has to consider: https://github.com/MLH-Fellowship/Plots.jl/pull/26

**Pull request closed without merging**
