### PR TITLE
Fix img axes

### PR DESCRIPTION
**Pull request by t-bltg**
Fix https://github.com/JuliaPlots/Plots.jl/issues/4087.

```julia
using Plots

png(plot(Gray.(randn(10,15))), "foo")
```
foo

### CODE REVIEW

**Comment by t-bltg** [comment]
@sefffal, I assumed that the labels will suit you, the alternatives are.

- label vertices 0:15 (chosen here)
- labels vertices 1:16
- labels cells 1:15

Labelling `n` cells centers is strictly equivalent to labelling `n+1` vertices, so this was the easiest fix. But if that doesn't suit you, we should find a way to label cell centers as with plotly(to me this is only a matter of personal taste), if that's even possible (not sure it's doable easily).

**Comment by sefffal** [comment]
Thanks @t-bltg for looking at this!
My preference would definitely be to label the cell centres, 1:15. At least for most applications in astronomy we like to think of the indices as pointing to the centres of the pixels.
But if there is another convention that is more widely used, I can work around whatever you choose. Thank you!

**Comment by t-bltg** [comment]
Thanks for your reply.

What we could do right now is fix the current which is obviously wrong with `0:15`, but keep https://github.com/JuliaPlots/Plots.jl/issues/4087 opened until someone finds a more decent solution or a hack for centering ticks.

**Comment by t-bltg** [comment]
@BeastyBlacksmith, whats is your opinion on this ? There is no point opening a PR in https://github.com/JuliaPlots/PlotReferenceImages.jl if this is not the fix which is going to get in.

**Comment by sefffal** [comment]
A second reason to prefer labeling cells starting at 1 is that it matches nicely with Julia indexing. For example, you can access the cell at position 1,1 just by accessing `arr[1,1]`. Since Julia uses 1 based indexing I think this is more natural.

As an aside, how does this work for heatmaps? Can the tick positioning code from there be used for images as well?

**Comment by t-bltg** [comment]
> As an aside, how does this work for heatmaps? Can the tick positioning code from there be used for images as well?

Looks like heatmap is centered at least for `GR`: https://docs.juliaplots.org/stable/generated/gr/#gr-ref43

**Comment by BeastyBlacksmith** [comment]
I think we should make this consistent with heatmap

**Comment by t-bltg** [comment]
```julia
using Plots
img = randn(10, 15)
png(plot(Gray.(img), xticks=1:15, yticks=1:10), "foo")
```

hm_img_2

@sefffal, @BeastyBlacksmith, ok now ?

**Comment by sefffal** [comment]
Beautiful!

**Pull request merged**
