### PR TITLE
RFC: Use existing colorbar axis if it already exists (for PyPlot)

### LINKED ISSUE #412: Colorbars inside plot areas
When I run the following code...

``` julia
using Plots
y = cumsum(randn(100,3))
scatter(y, zcolor=y)
```

...I see a colorbar for the first series outside the plot area, and two colorbars for the other two series superimposed inside the plot area:
colorbar1
I was expecting the three series to share a single colorbar placed outside the plot area. Thinking I could keep the first series's colorbar on and disable the others, I added `colorbar=[true false false]`, but the plot output did not change.

When I add `layout=2`, the first two colorbars are placed outside the two plot areas, and the third is superimposed on the second plot area:

``` julia
scatter(y, zcolor=y, layout=2)
```

colorbar2

What is the syntax for having multiple series share one colorbar?

EDIT: I'm using the PyPlot backend with Plots 0.8.1. When I switch to GR, there is one colorbar located outside the plot area.

### PR DESCRIPTION
**Pull request by darwindarak**
This should fix #412

### CODE REVIEW

**Comment by daschw** [comment]
I think #412 is already fixed on current master. At least I cannot reproduce it.

**Comment by daschw** [comment]
It has been fixed in https://github.com/JuliaPlots/Plots.jl/pull/1084.
Thanks for the effort, though!
I think we can close #412, or can anyone still reproduce the issue reported there?

**Comment by darwindarak** [comment]
You’re right, it works just fine on master

**Comment by mkborregaard** [comment]
Thanks otherwise! Should work on the release version too - sorry for not closing the issue in time!

**Pull request closed without merging**
