### PR TITLE
Re-integrate HDF5 plots.

### PR DESCRIPTION
**Pull request by ma-laforge**
Made code compatible with Julia v0.6.
Parametric types no longer <: DataType (now <: Type).
Add workaround to initialize Dict with "Type" keys.

### CODE REVIEW

**Comment by ma-laforge** [comment]
Re-tested on v0.6 as per https://github.com/JuliaPlots/Plots.jl/pull/747

### Cause of problem
In v0.5, parametric types are no longer <: DataType (now <: Type).

### Comments
  - Much easier to test in v0.5.  There seems to be alot of (partially) broken plotting backends in v0.6.

> @mkborregaard : Nice. I don't think the normal test/example system for Plots backends will apply to this, but can you write some tests that will ensure the integrity of the produced objects? And add a description on PlotDocs under the backends tab?

PR - description in PlotDocs: https://github.com/JuliaPlots/PlotDocs.jl/pull/21

### Regarding tests:
Maybe we could pick a favorite backend that (ex: GR.jl), and just verify that the reference plots will display properly if first stored to .hdf5 file before loading it back in.  What do you think @mkborregaard ?

**Comment by ma-laforge** [comment]
## Reiterating:

Works surprisingly well, with a few limitations

- SeriesAnnotations & GridLayout support known to be missing.

### Write to .hdf5 file:
```
p = plot(...)
Plots.hdf5plot_write(p, "plotsave.hdf5")
```

### Read from .hdf5 file:
```
pyplot() #Must first select backend
pread = Plots.hdf5plot_read("plotsave.hdf5")
display(pread)
```

**Comment by ma-laforge** [comment]
## Re-iterating
## Fun test (Plots.jl samples): Violin plot

```
using Plots
using StatPlots #For 25 & 30

hdf5() #Select HDF5-Plots "backend"
TMPFILE = "myplot.hdf5"
idx = 30 #Which "example" plot to display

ex = Plots._examples[idx]
srand(1234) #Make consistent "random" plots.
plotvector = map(eval, ex.exprs)
curplot = plotvector[1]

#Write to HDF5:
Plots.hdf5plot_write(curplot, TMPFILE)

#Read back from HDF5:
#*****************************************************
inspectdr()
p = Plots.hdf5plot_read(TMPFILE)
display(p)

pyplot()
p = Plots.hdf5plot_read(TMPFILE)
display(p)

gr()
p = Plots.hdf5plot_read(TMPFILE)
display(p)

#...
```

**Comment by mkborregaard** [comment]
Great, thanks for updating this. I think it's fine to test the results against GR on 0.6 for now.

**Comment by ma-laforge** [comment]
Improved robustness a bit.  Now supports ColorGradient.

### Important
I had to move when backends.jl gets `included` to ensure key types were visible by the HDF5 plots module.

Hopefully this does not cause unexpected issues.

**Comment by mkborregaard** [comment]
Great. We are working on getting the tests working again, so we can use them to test PRs. It is probably safest to wait with merging this until we have had a chance to test it properly (especially on 0.6 which should be the target of this IMO).

**Comment by mkborregaard** [comment]
This looks like it's ready to merge - the tests are passing :-) Thanks @ma-laforge

**Pull request merged**
