### PR TITLE
Add 2D marker_z and line_z with Functions

### PR DESCRIPTION
**Pull request by SebastianM-C**

### CODE REVIEW

**Comment by mkborregaard** [comment]
Great, have you tested it?
If it works, it'd be nice to have a test using it added to the test, and the description of the zcolor argument updated in the arg_desc.jl file

**Comment by SebastianM-C** [comment]
I am not sure how should I test it. Should I just locally modify the Plots.jl file and try it?

**Comment by mkborregaard** [comment]
Hey, have you tested this code out?

**Comment by SebastianM-C** [comment]
I think that I tested locally some time ago, but I am not sure. I will try to finish this properly these days.
Sorry for the huge delay.

**Comment by SebastianM-C** [comment]
I tested it locally and I also added the analogue function to `line_z`. The only thing remaining should be adding tests.

**Comment by SebastianM-C** [comment]
Should I add another `PlotExample` or should I add something more to the one starting on line 419?
I was thinking of something like
```julia
 scatter(rand(10), rand(10), marker_z=(x,y)->x^2)
 plot(1:10, rand(10), line_z=(x,y)->x^2)
```

**Comment by mkborregaard** [comment]
Just replacing `t` with a 2-d function to the scatter example on line 419 should be great :-) If it looks good, but I think it will

**Comment by SebastianM-C** [comment]
Locally the example looks like this:
image

**Comment by mkborregaard** [comment]
Perfect!

**Comment by mkborregaard** [comment]
Thank you @SebastianM-C !

**Pull request merged**
