### PR TITLE
WIP: Actually use PlotsDisplay()

### PR DESCRIPTION
**Pull request by pfitzseb**
instead of overloading display for REPLDisplay.

This unfortunately doesn't work yet because the `@init` block apparently is never executed.

### CODE REVIEW

**Comment by mkborregaard** [comment]
👍 
The non-executed `init` block is probably also the cause of https://github.com/JuliaPlots/Plots.jl/issues/1661
Could it be related to https://github.com/JuliaPlots/Plots.jl/pull/1601 ?

**Comment by pfitzseb** [comment]
Turns out that Plots.jl now actually has a `__init__` function, so the `@init` macro doesn't make any sense any more. This works mostly fine now, I think.

**Comment by pfitzseb** [comment]
Note: This only works with GR if you overwrite `GR.isatom` with `GR.isatom() = false`.

**Comment by mkborregaard** [comment]
Nice!

**Comment by mkborregaard** [comment]
It works fine in the REPL with GR for me - it doesn't work in Atom, but then again I don't think Plots master works for me in Atom either - it's always been flaky.

**Comment by pfitzseb** [comment]
In Atom you might need https://github.com/JunoLab/Atom.jl/commit/234890134f24f1a8e2bb7d3a3ee281f653c1b7cf for Plots to appear in the Plot Pane and possibly also overwrite GR's `isatom` method with `isatom() = false`.

Ping @jheinen for coordination with your efforts to get GR working in Atom.

**Comment by daschw** [comment]
It works perfectly on my system :tada: thanks a lot @pfitzseb

**Comment by mkborregaard** [comment]
So we don't need `isatom`?

**Comment by daschw** [comment]
Oh, was I too fast? I didn't need to overwrite anything.

**Comment by mkborregaard** [comment]
I need to overwrite `GR.isatom` for this to work - which @jheinen says can be done automatically if we somehow define an `isplots` function in GR (I guess it could just evaluate to `false` in GR and to `true` in Plots).

**Comment by daschw** [comment]
So, should we revert this until there is an `isplots` in GR?

**Comment by mkborregaard** [comment]
No let me make a quick PR and then just wait with doing a release?

**Comment by mkborregaard** [comment]
Wait :mind_blown: Now it works on master of GR and Plots with no problem even on my machine. I wonder if my machine was in some weird state when I tried it? But at least I now have branches here and on GR that would solve the problem if there was one...

**Comment by EricForgy** [comment]
This is still breaking plots in VS Code. Any thoughts?

**Pull request merged**
