### PR TITLE
honour `html_output_format` in Juno

### PR DESCRIPTION
**Pull request by pfitzseb**
Requires https://github.com/JunoLab/Atom.jl/commit/a939fcf908aa5afb6b2ef4465430e4341502a78f.

### CODE REVIEW

**Comment by pfitzseb** [comment]
Yeah, I think that's the best we can do.
For reference: https://github.com/JuliaLang/METADATA.jl/pull/18437

**Comment by pfitzseb** [comment]
Ok, new Atom.jl version is out, so this should be good to go.

**Comment by mkborregaard** [comment]
Does the atom plotting depend on this, i.e. do we need to tag a new version immediately?

**Comment by pfitzseb** [comment]
No, the new Atom version doesn't introduce any problems without this patch.

Would still be nice to get this out so people can plot many data points in Atom tho :)

**Pull request merged**
