### PR TITLE
Fix small issues with response to :dpi value.

### PR DESCRIPTION
**Pull request by ma-laforge**
Now line widths, etc are in pixels (like I assume was the intent for Plots.jl).

:dpi now only affects font sizes (because they are in points - not pixels)...  And grid line widths, I guess... because we don't seem to do the size mapping for those.

...But the main thing that :dpi changes is the size (in inches) of the image metadata...

As with other backends (presumably), the user must use the `size=(w,h)` keyword to control the saved image dimension.

### CODE REVIEW

**Comment by ma-laforge** [comment]
Here is a bit of sample code you can use to see how PyPlot now responds:

```
y = rand(10)
x = 1:length(y)
y = ones(x) #Overwrite
y[1] = 0; y[end] *= 2

using Plots
pyplot()
default(overwrite_figure=false)

for dpi in [50, 72, 300]
	@show dpi
	global p = Plots.plot(x, y, linewidth=2, dpi=dpi)
	display(p)
	fname = "pyplot_dpitests_$dpi.png"
	png(fname)
end
```

Notice that the plot line is fixed @ 2 pixels irrespective of the value of dpi....

...But since we don't rescale the grid line widths, those do vary with DPI...

I'm not sure what the point of the DPI setting was in the first place - because most of the input values to Plots.jl are in pixels - so changing the DPI value should simply change the physical image size in the metadata (Ignoring, of course the font sizes - which are typically specified in "points").

**Comment by mkborregaard** [comment]
I think the ability to change the look of the plot with a single call to dpi (as. eg. here https://github.com/JuliaPlots/Plots.jl/issues/739) is a good reason for having it  - would that ability not be lost with this PR?

**Comment by ma-laforge** [comment]
@mkborregaard: This PR will probably do what you want it to:

Fonts will get bigger as you change DPI because I don't actually scale fonts (ie font sizes are in "points" - not pixels).

**However** (and it's a big however :) )

I don't think that we actually want this to be the behaviour.  Instead, we should be implementing what is described in issues:
 - DPI proposal: https://github.com/JuliaPlots/Plots.jl/issues/742
 - Set default fonts/sizes: https://github.com/JuliaPlots/Plots.jl/issues/555

(That said, I have no objection to merging in this solution for now).

**Comment by ma-laforge** [comment]
New implementation now matches much better expected behaviour described in Issue https://github.com/JuliaPlots/Plots.jl/issues/742.

Missing:
 - DPI setting affects both on-screen and saved plots (not certain how to re-structure plots for this).

That said, I don't see this re-structuring to happen any tie soon.

Ready for merge, pending review...

**Comment by ma-laforge** [comment]
@mkborregaard: This new implementation should make it easier to get what you wanted.

For example, you could add the following to your `.juliarc` file:
```
pscale = 2
PLOTS_DEFAULTS = Dict(:size=>(600/pscale,400/pscale), :dpi=>72*pscale)
```

If I understood all the automatic (strange) re-interpretations happening in the background, this should make plots look the same on the retina display as it does with other displays.

To make lines & fonts larger relative to the plot size, you can further increase `pscale`.  Using integer values of `pscale` will result in whole (non-fractional) pixels being used.

**Comment by ma-laforge** [comment]
@mkborregaard: Though I got the plot ouput to look good, the matplotlib GUI seems to ignore the plot size values.

Do you have any input here?
 - Output .png looks good.
 - On-screen GUI is displayed with any size it sees fit (user must manually re-size).

**Comment by mkborregaard** [comment]
I'll be unable to work on julia now and for the next three weeks, but maybe @tbreloff or @pkofod can have a look

**Comment by ma-laforge** [comment]
FYI: These changes altered the definition of "pixel" to something that better matches how images should be defined.

## To all other backend maintainers:

Your layout code might have to be tweaked to adjust for the new size/meaning of "pixel".

**Comment by mkborregaard** [comment]
To all open PRs: Due to the change to 0.6 it appears that all PRs will have to be rebased onto master for Travis tests to run. - also, @ma-laforge sorry for delaying looking at this. What is the current status? Can this be merged regardless of our larger dpi-scaling-discussion?

**Comment by ma-laforge** [comment]
Status:
This PR actually does match the intent on the larger dpi-scaling discussion.

In other words: It is ready to merge.

Just tell me if I need to rebase this first - and if yes: Does it need to be a new PR, or will a `push --force` propagate correctly back to this PR right here?

**Comment by ma-laforge** [comment]
Oh, I get it, I DO have to rebase.  Pending...

**Comment by ma-laforge** [comment]
Ok rebase done.  Everything appears to work as expected.

Travis fails: the :dpi behaviour was changed - meaning the reference images no longer match.

**Comment by ma-laforge** [comment]
*Bump.*  I just want to know if there is something that must be done to maintain working tests.

Technically, I should be updating the images in PlotReferenceImages.jl - but since I cannot do both in a single commit... the checks ***will*** fail.

**Comment by mkborregaard** [comment]
I'm not adressing this because I think we need to have the whole dpi discussion first. This is something where opinion is divided also within Plots, and I don't have the time to take it now, but we'll revisit for sure. 
The approach is to update PlotReferenceImages on your own fork, verify that tests pass, then submit a PR to PlotReferenceImages first remarking that it's linked to this one.

**Comment by ma-laforge** [comment]
> @mkborregaard [...] we need to have the whole dpi discussion first [...]

Fair enough.  I Just did not know what the status was.  I will try to keep an ear out for when the time comes.

&rArr; At least we have a alternative working model for the DPI problem here that people can try out.

NOTE: I also re-defined a few constants - for example:
  - `PX_PER_INCH = DPI = 100` are no longer constants.  They are replaced by `DTPPOINTS_PER_INCH = 72 #Typography (desktop publishing) "points per inch"` - because DPI should be a user-defined quantity - not a constant.

RE: PlotReferenceImages:  Good to know as well.  I will have to do that when it comes time.

**Comment by asinghvi17** [comment]
Bump

**Comment by daschw** [comment]
I think this can be closed. Superceded by #1561

**Pull request closed without merging**
