### PR TITLE
Fix plotting ribbons as 2-tuples

### LINKED ISSUE #2185: Plotting a ribbon with a tuple of vectors no longer works
MWE:
```julia
using Plots
plot([0, 1], [1, 1]; ribbon = ([1, 2], [3, 4]))

ERROR: Cannot convert Tuple{Array{Int64,1},Array{Int64,1}} to series data for plotting
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] prepareSeriesData(::Tuple{Array{Int64,1},Array{Int64,1}}) at /Users/anshul/.julia/dev/Plots/src/series.jl:15
 [3] convertToAnyVector(::Tuple{Array{Int64,1},Array{Int64,1}}, ::Dict{Symbol,Any}) at /Users/anshul/.julia/dev/Plots/src/series.jl:26
 [4] process_ribbon(::Tuple{Array{Int64,1},Array{Int64,1}}, ::Dict{Symbol,Any}) at /Users/anshul/.julia/dev/Plots/src/series.jl:62
 [5] macro expansion at /Users/anshul/.julia/dev/Plots/src/series.jl:139 [inlined]
 [6] apply_recipe(::Dict{Symbol,Any}, ::Type{Plots.SliceIt}, ::Array{Int64,1}, ::Array{Int64,1}, ::Nothing) at /Users/anshul/.julia/packages/RecipesBase/zBoFG/src/RecipesBase.jl:275
 [7] _process_userrecipes(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{Int64,1},Array{Int64,1}}) at /Users/anshul/.julia/dev/Plots/src/pipeline.jl:83
 [8] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{Int64,1},Array{Int64,1}}) at /Users/anshul/.julia/dev/Plots/src/plot.jl:178
 [9] #plot#133(::Base.Iterators.Pairs{Symbol,Tuple{Array{Int64,1},Array{Int64,1}},Tuple{Symbol},NamedTuple{(:ribbon,),Tuple{Tuple{Array{Int64,1},Array{Int64,1}}}}}, ::typeof(plot), ::Array{Int64,1}, ::Vararg{Array{Int64,1},N} where N) at /Users/anshul/.julia/dev/Plots/src/plot.jl:57
 [10] (::RecipesBase.var"#kw##plot")(::NamedTuple{(:ribbon,),Tuple{Tuple{Array{Int64,1},Array{Int64,1}}}}, ::typeof(plot), ::Array{Int64,1}, ::Array{Int64,1}) at /Users/anshul/.julia/dev/Plots/src/plot.jl:51
 [11] top-level scope at REPL[17]:100:
```

cc @daschw @yha (since you seem to have worked with that code recently)

### PR DESCRIPTION
**Pull request by asinghvi17**
…e{Any,Any}, plottatributes)

@ChrisRackauckas @daschw 

Fixes #2185

### CODE REVIEW

**Comment by fredcallaway** [comment]
I'm still hitting an error trying to plot ribbons (using the MWE from the original issue)

```
(v1.2) pkg> status Plots
    Status `/mnt/bucket/people/flc2/.julia/environments/v1.2/Project.toml`
  [682c06a0] JSON v0.21.0
  [91a5bcdd] Plots v0.27.0
  [2913bbd2] StatsBase v0.32.0
```

```
julia> plot([0, 1], [1, 1]; ribbon = ([1, 2], [3, 4]))
ERROR: Cannot convert Tuple{Array{Int64,1},Array{Int64,1}} to series data for plotting
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] prepareSeriesData(::Tuple{Array{Int64,1},Array{Int64,1}}) at /usr/people/flc2/.julia/packages/Plots/Iuc9S/src/series.jl:15
 [3] convertToAnyVector(::Tuple{Array{Int64,1},Array{Int64,1}}, ::Dict{Symbol,Any}) at /usr/people/flc2/.julia/packages/Plots/Iuc9S/src/series.jl:26
 [4] process_ribbon(::Tuple{Array{Int64,1},Array{Int64,1}}, ::Dict{Symbol,Any}) at /usr/people/flc2/.julia/packages/Plots/Iuc9S/src/series.jl:62
 [5] macro expansion at /usr/people/flc2/.julia/packages/Plots/Iuc9S/src/series.jl:139 [inlined]
 [6] apply_recipe(::Dict{Symbol,Any}, ::Type{Plots.SliceIt}, ::Array{Int64,1}, ::Array{Int64,1}, ::Nothing) at /usr/people/flc2/.julia/packages/RecipesBase/zBoFG/src/RecipesBase.jl:275
 [7] _process_userrecipes(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{Int64,1},Array{Int64,1}}) at /usr/people/flc2/.julia/packages/Plots/Iuc9S/src/pipeline.jl:83
 [8] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{Int64,1},Array{Int64,1}}) at /usr/people/flc2/.julia/packages/Plots/Iuc9S/src/plot.jl:178
 [9] #plot#137(::Base.Iterators.Pairs{Symbol,Tuple{Array{Int64,1},Array{Int64,1}},Tuple{Symbol},NamedTuple{(:ribbon,),Tuple{Tuple{Array{Int64,1},Array{Int64,1}}}}}, ::typeof(plot), ::Array{Int64,1}, ::Vararg{Array{Int64,1},N} where N) at /usr/people/flc2/.julia/packages/Plots/Iuc9S/src/plot.jl:57
 [10] (::getfield(RecipesBase, Symbol("#kw##plot")))(::NamedTuple{(:ribbon,),Tuple{Tuple{Array{Int64,1},Array{Int64,1}}}}, ::typeof(plot), ::Array{Int64,1}, ::Array{Int64,1}) at ./none:0
 [11] top-level scope at REPL[31]:1
```

**Comment by fredcallaway** [comment]
Any chance we can get this fixed?

**Comment by daschw** [comment]
For me `plot([0, 1], [1, 1]; ribbon = ([1, 2], [3, 4]))` works on v0.27.1

**Comment by fredcallaway** [comment]
Apologies, that is correct.

**Pull request merged**
