### PR TITLE
add text/plain default, fix #1515

### LINKED ISSUE #1515: All backends should have a fallback for "text/plain"
Similar to https://github.com/JuliaPlots/Plots.jl/blob/49f4773e81c6a69881c14bdcbc3d146e8d92086a/src/output.jl#L326

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
@daschw I think I have a fix for the failures you observed in #1538 but it is a bit involved... Would you mind testing this branch? I can not set up Juno and the different backends correctly.

**Comment by daschw** [comment]
Sure!

**Comment by daschw** [comment]
OK, with this PR everything seems to work except unicodeplots() in IJulia, but that's expected (will be fixed by a later commit), right?

**Comment by fredrikekre** [comment]
> that's expected (will be fixed by a later commit), right?

Yes.

**Comment by mkborregaard** [comment]
Awesome!

**Comment by daschw** [comment]
1st step ;-)
Do you want me to check #1536 and #1537 right now too, or do they need some edits from your side @fredrikekre ?

**Comment by mkborregaard** [comment]
Ha ha I'm easily excited.

**Pull request merged**
