### PR TITLE
Added support for discrete contour plots

### PR DESCRIPTION
**Pull request by jheinen**
requires GR 0.36.0

### CODE REVIEW

**Comment by mkborregaard** [comment]
Awesome. Closes #1024

**Comment by mkborregaard** [comment]
@jheinen this PR broke Plots Travis tests because it makes test example 22 look different. Are you set up so you can put a new image in PlotReferenceImages for this test? Otherwise I might do it, but I think actually Travis will error on pngs generated on mac...

**Comment by juliohm** [comment]
I've came across this inconsistency between plots generated in different platforms multiple times while using GR. I thought the issue had been solved. :cry:

**Comment by mkborregaard** [comment]
It's got nothing to do with Plots, it's just that different platforms save different pngs.

**Comment by juliohm** [comment]
Got it, thanks for clarifying. I've heard loading/saving images across platforms is a nightmare.

**Pull request merged**
