### PR TITLE
WIP - fix 32-bit errors

### PR DESCRIPTION
**Pull request by mkborregaard**
This branch is an attempt to address 32 bit errors in Plots. So far just based on appveyor. It is possible to build a 32 bit julia for testing on a 64-bit linux but I don't have that at the moment.

### CODE REVIEW

**Comment by pkofod** [comment]
What is the problem here? That `Int32` overflows?

**Comment by mkborregaard** [comment]
No idea :joy: I just opened the PR because the 32-bit version fails and I thought I could fix it easily.

**Comment by pkofod** [comment]
I was just wondering if `Int64(n)` would fix it as well...

**Comment by mkborregaard** [comment]
Good idea. It would be nice to have Plots working on 32-bit, especially if it's just a few adjustments. Though the fact that this only shows up  in Appveyor and has exactly 0 issues tells me not that many are currently running the package on a 32-bit system.

**Comment by pkofod** [comment]
Is there a link to the failing 32bit output?

**Comment by mkborregaard** [comment]
Just follow the appveyor badge - we've allowed 32-bit failures.

**Comment by mkborregaard** [comment]
This should not be necessary anymore

**Pull request closed without merging**
