### PR TITLE
add compat entries for backends

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
This adds compat entries for PyPlot, PGFPlotsX, PlotlyJS and PlotlyBase.

Actually a reaction to #4105, since we can then tag a version that requires PlotlyBase 0.7 and make a version that is compatible with 0.8.

The pitfall here is that people will complain if their dependencies get hold back by compat requirements of a backend that they don't use.

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
@t-bltg you should know best, what the lower bound for Unicode plots is these days

**Comment by t-bltg** [comment]
> @t-bltg you should know best, what the lower bound for Unicode plots is these days

The current mentioned version (`2.8`) is fine.

Regarding this PR, I guess some user won't be happy about added dependencies (especially, if I remember about `Plotly`) there are some pretty big dependencies (Kaleido_jll ? https://juliahub.com/ui/Packages/Kaleido_jll/8Y3bT/0.1.0+0) which blows up the download / update / install time for not very fast internet connections. But I understand the need for narrowing versions ...

**Comment by BeastyBlacksmith** [comment]
We don't actually add the dependencies. They are added to the `test` target and only added when testing Plots.

**Comment by t-bltg** [comment]
Ha sorry, I misread the changes.

**Pull request merged**
