### PR TITLE
remove FixedSizeArrays fix #1802

### LINKED ISSUE #1802: Precompiling Plots fails: FixedSizeArrays not defined
Hi,

I just updated packages, which updated GR to 0.35.0. Now I cannot import Plots. This seems to happen on both master and version 0.20.6.

I tried installing FixedSizeArrays, but it has unsatisfiable requirements.

Thanks!
Andy

```
using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
WARNING: StaticArrays.FixedSizeArrays is deprecatedStaticArrays.FixedSizeArrays is deprecated. Use StaticArrays directly.
  likely near /home/andi/.julia/packages/Plots/14Jpf/src/Plots.jl:8
ERROR: LoadError: LoadError: UndefVarError: FixedSizeArrays not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1041
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /home/andi/.julia/packages/Plots/14Jpf/src/Plots.jl:1
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1041
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:319 [inlined]
 [12] eval(::Expr) at ./client.jl:389
 [13] top-level scope at ./none:3
in expression starting at /home/andi/.julia/packages/Plots/14Jpf/src/utils.jl:290
in expression starting at /home/andi/.julia/packages/Plots/14Jpf/src/Plots.jl:167
ERROR: Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to /home/andi/.julia/compiled/v1.0/Plots/ld3vC.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1187
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:855
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:837
```

```

(v1.0) pkg> add FixedSizeArrays
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package FixedSizeArrays [e220cda7]:
 FixedSizeArrays [e220cda7] log:
 ├─possible versions are: [0.0.1-0.0.10, 0.1.0-0.1.2, 0.2.0-0.2.5] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.10, 0.1.0-0.1.2, 0.2.0-0.2.5]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

### PR DESCRIPTION
**Pull request by daschw**

### CODE REVIEW

**Comment by mkborregaard** [comment]
Awesome - and tests pass - but I don't think we have any tests for these recipes though. Looks like it should work though.

**Comment by mkborregaard** [comment]
Also, this comment: https://github.com/JuliaLang/METADATA.jl/pull/19050#issuecomment-432324269

**Comment by daschw** [comment]
Should we tag a release with this?

**Comment by mkborregaard** [comment]
Yes 👍 I'm putting kids to bed right now but can tag when don't if you haven't :-D

**Pull request merged**
