### PR TITLE
replace d by plotattributes inside recipes

### PR DESCRIPTION
**Pull request by jw3126**
See  #1107. Please tag a new release after merging.

### CODE REVIEW

**Comment by jw3126** [comment]
There is some `PyPlot` related CI failure. Is this related to my changes?

**Comment by mkborregaard** [comment]
No, that happened before. We'll inspect manually to see whether the gr tests pass.

**Comment by jw3126** [comment]
So all gr tests pass on Travis. On some AppVeyor setups all tests fail. My impression is that the failures are unrelated to this PR. Do I see this correctly? Should I change something or is this ready for merge?

**Comment by mkborregaard** [comment]
Ready :-)

**Comment by jw3126** [comment]
Is it possible to tag a new release of Plots in the next days? So I can PR downstream packages?

**Comment by mkborregaard** [comment]
Yes, I'm doing it

**Pull request merged**
