### PR TITLE
Make tickmarks the same length for both axes in GR 2D plots

### PR DESCRIPTION
**Pull request by daschw**
Avoid too short ticks for one axis in very wide or narrow plots. This changes
```
plot(rand(10), size=(200, 400))
```
from
portrait_old

to
portrait_new

and
```julia
plot(rand(10), size=(600, 100))
```
from
wide_old

to
wide_new

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
Thats definetly an improvement, I would argue that the ticklength should be the same irrespective of the size of the window.
For example are the ticks on the second figure much longer than on the first

**Comment by isentropic** [comment]
Oh my god, this been bothering me since forever. I could never get it fixed myself

**Review by isentropic — COMMENTED** [review]
looks really good to me

**Comment by isentropic** [comment]
I actually think it should be like 
```
max(ticksize_x_axis, ticksize_y_axis)

```
where ticksize_y_axis is the old way of calculating it. So it would scale as before

**Comment by daschw** [comment]
OK, how about this?
regular
minorticks
portrait_update
wide_update
tiny

**Comment by isentropic** [comment]
I think it looks a little to long compared to pyplot, maybe scale down by factor of 1.25 or 1.5?

**Comment by isentropic** [comment]
Overall, whatever you decide i support it. This is already much better than before

**Comment by daschw** [comment]
Thanks for the feedback! 
next suggestion:

regular
minorticks
portrait
wide
tiny
big

**Comment by isentropic** [comment]
This looks perfect to me.

**Review by t-bltg — APPROVED** [review]

**Pull request merged**
