### PR TITLE
Recipe for GeometryBasics.Point

### PR DESCRIPTION
**Pull request by yha**
since `GeometryTypes` is now deprecated

### CODE REVIEW

**Comment by yha** [comment]
Looks like tests with Julia 1.0 fail because `GeometryBasics` requires Julia 1.2.
Not sure what to do about that. Is it possible to depend on `GeometryBasics` conditionally based on Julia version? 
Otherwise, if `Plots` should continue supporting 1.0 and `GeometryBasics` doesn't, maybe the `Point` recipe needs to go inside `GeometryBasics` or to a different package?

**Comment by mkborregaard** [comment]
I'm not against capping at 1.2. I don't think backward compatibility is awfully important at this stage - what do yuo say @daschw ?

**Comment by daschw** [comment]
I agree, our tests on 1.0 don't pass anyway ...

**Comment by yha** [comment]
In this case, I think this can be merged as-is.
I don't think it's necessary to explicitly require 1.2 in `Plots` when it's already required by a dependency. And the failures on nightly seem unrelated.

**Pull request merged**
