### PR TITLE
Update Plots to use color libraries

### PR DESCRIPTION
**Pull request by mkborregaard**
Here is a first stab at a recipe to show color libraries

### CODE REVIEW

**Comment by mkborregaard** [comment]
```julia
showlibrary(:colorbrewer)
```
skaermbillede 2017-02-21 kl 22 47 35

**Comment by tbreloff** [comment]
:+1: !! But... maybe this should be in PlotRecipes?  What do you think?

**Comment by mkborregaard** [comment]
On top of my head I would say it belongs here? Color gradients are central to Plots, and the recipe does not interface with any other packages. But I don't feel strongly about it. What are the pros of putting it in PlotRecipes - that it is called with a special name rather than `plot`?

**Comment by tbreloff** [comment]
Just in the name of keeping Plots minimal (easier to keep out new stuff than remove old stuff)

**Comment by tbreloff** [comment]
But I don't feel so strongly... feel free to merge

**Comment by mkborregaard** [comment]
The recipe fails on GR with
"MethodError: no method matching length(::Symbol)
Closest candidates are:
  length(!Matched::SimpleVector) at essentials.jl:168
  length(!Matched::Base.MethodList) at reflection.jl:256
  length(!Matched::MethodTable) at reflection.jl:322
  ...
 in gr_text(::Float64, ::Float64, ::Symbol) at gr.jl:186
 in gr_display(::Plots.Subplot{Plots.GRBackend}, ::Measures.Length{:mm,Float64}, ::Measures.Length{:mm,Float64}, ::Array{Float64,1}) at gr.jl:706
 in gr_display(::Plots.Plot{Plots.GRBackend}) at gr.jl:494
 in _display(::Plots.Plot{Plots.GRBackend}) at gr.jl:1114
 in gui(::Plots.Plot{Plots.GRBackend}) at output.jl:123
 in gui() at output.jl:123
 in include_string(::String, ::String) at sys.dylib:?
 in include_string(::String, ::String) at sys.dylib:?
 in eval(::Module, ::Any) at sys.dylib:?
 in eval(::Module, ::Any) at sys.dylib:?
 in (::Atom.##65#68)() at eval.jl:102
 in withpath(::Atom.##65#68, ::Void) at utils.jl:30
 in withpath(::Function, ::Void) at eval.jl:38
 in macro expansion at eval.jl:101 [inlined]
 in (::Atom.##64#67{Dict{String,Any}})() at task.jl:60
"

**Comment by mkborregaard** [comment]
I fixed the GR error

**Comment by tbreloff** [comment]
Is this ready for merge?  You can do it whenever

**Comment by mkborregaard** [comment]
Yes, I'd say so, I just wanted to give @pkofod the chance to comment. Note that I merged all Plots colorlibrary related changes into this branch, so this is now the PR for color libraries, together with https://github.com/JuliaPlots/PlotUtils.jl/pull/7 and https://github.com/JuliaPlots/PlotThemes.jl/pull/15 and a WIP PR on PlotDocs. They must all be merged at the same time. I'll do it tomorrow if there are no comments before then.

**Comment by mkborregaard** [comment]
Finally. I have one more thing to add - more flexible setting defaults. And I'll document all this in the colors section in PlotDocs.

**Comment by pkofod** [comment]
Great stuff - sorry for my absence.

**Pull request merged**
