### PR TITLE
 Add outer legend for Plotly

### LINKED ISSUE #2775: [FR] Implement outer legend positions for plotly backend
Implement `outertop`, `outerright` ... `outerbottomleft` positions for plotly.
Relevant code [here](https://github.com/JuliaPlots/Plots.jl/blob/c2df99cc6600f7fc0c6564d98fc3473c1c77519f/src/backends/plotly.jl#L340)

### PR DESCRIPTION
**Pull request by RashikaKarki**
Fix #2775 
I have added the outer legend position: outertop, outerbottom, outerleft, outerright, outertopleft, outertopright, outerbottomleft and finally outerbottomright

`plot(rand(100), label = "item", legend = :outertopright )`
image

### CODE REVIEW

**Comment by daschw** [comment]
Nice, thanks!

**Comment by RashikaKarki** [comment]
Yes, of course. I will make the changes.

**Comment by isentropic** [comment]
@RashikaKarki please feel free to ask questions either here or zulip or slack

**Comment by RashikaKarki** [comment]
Sure. Thanks @isentropic

**Pull request merged**
