### PR TITLE
Added legend_title attribute for Pylot backend

### PR DESCRIPTION
**Pull request by daschw**
This implements the feature request of #882 for the PyPlot backend.
```julia
using Plots; pyplot()
plot(rand(10, 3), legend_title = "My Awesome Title")
```
now produces:
pyplot_legend_title

@jheinen Would this also be possible for GR?

### CODE REVIEW

**Comment by daschw** [comment]
... or should the attribute rather be named `legendtitle`, `labeltitle` or `label_title`

**Comment by mkborregaard** [comment]
Great! 👍 for `legendtitle`, though the others could/should be added as aliases.

**Comment by daschw** [comment]
Now the default attribute is `legendtitle` and the aliases are:
`legend_title`, `labeltitle`, `label_title`, `leg_title`, `key_title`

**Comment by lazarusA** [comment]
Is there a way to change the size of the legend title?

**Comment by daschw** [comment]
> Is there a way to change the size of the legend title?

No, that's not (yet) implemented in Plots.

**Pull request merged**
