### PR TITLE
fix IJulia integration (fix #1365)

### LINKED ISSUE #1365: nbconvert --latex can not handle Plots plots
When converting to tex, nbconvert does not undertand this construct (in the .ipynb file)
```
   "outputs": [
    {
     "data": {
      "text/html": [
       "<img src=\"data:image/png;base64,iVBORw0KGgoAAAANh...EUgAAlNuQmCC\" />"
```

Hence, one gets
```
$ jupyter nbconvert --to latex foo.ipynb
[NbConvertApp] Converting notebook foo.ipynb to latex
/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/nbconvert/filters/datatypefilter.py:41:
UserWarning: Your element with mimetype(s) [u'text/html'] is not able to be represented.
  mimetypes=output.keys())
[NbConvertApp] Writing 15455 bytes to foo.tex
```
and the image is dropped.

Seemingly the mime type magic happens here;
https://github.com/JuliaPlots/Plots.jl/blob/master/src/output.jl#L177

Related; jupyter/nbconvert/issues/740.
ipynb example; https://github.com/jupyter/nbconvert/files/1642959/bla.ipynb.txt

### PR DESCRIPTION
**Pull request by massemanet**
warning; this is the first julia code I've ever written.

 This patch fixes the problem described here; https://github.com/JuliaPlots/Plots.jl/issues/1365
  Basic problem is that ```IJulia.display_dict(plt::Plot)``` is supposed to return a dict ```{mimetype::String,image::String}```. Instead it returns ```{"text/html"=>{mime::String,image::String}}```  (by calling ```show("text/html",plt::Plot)```.
  jupyter is clever enough to display this correctly, but nbconvert fails, which means the "convert to pdf" menu item in jupyter generates a pdf without the plots.
  This patch probably means the ```show(io::IO, ::MIME"text/html", plt::Plot)``` function is dead code, but I'm not confident enough to act accordingly.

### CODE REVIEW

**Comment by daschw** [comment]
Hi massemanet, thanks for your contribution!
Unfortunately, with this branch checked out, when I do `File`->`Download as`->`PDF via LaTeX (.pdf)` in jupyter I get
```
500 : Internal Server Error

The error was:

nbconvert failed: global name 'FileNotFoundError' is not defined
```
Any ideas? Am I doing something wrong here? (I'm really not used to IJulia, jupyter, etc.)

**Comment by massemanet** [comment]
Might be a problem with your env I guess. Here's some more context.
  I get the Plots.jl code is from here;
```
julia$ (cd /root/.julia/v0.6/Plots ; git remote -v ; git status)                   
masse   https://github.com/massemanet/Plots.jl.git (fetch)
masse   https://github.com/massemanet/Plots.jl.git (push)
origin  https://github.com/JuliaPlots/Plots.jl.git (fetch)
origin  https://github.com/JuliaPlots/Plots.jl.git (push)
HEAD detached at masse/fix-ijulia-integration
nothing to commit, working tree clean
```
I start jupyter like this;
```
jupyter notebook --allow-root --no-browser --ip=0.0.0.0 --NotebookApp.token=''                                                           
```
The notebook has three cells like this;
```
using Plots ; using CSV ; using DataFrames ; pyplot() ; a= [0,1,2,3,4,5]
plot(a)
plot(a,html_output_format=:svg)
```
I see this in the jupyter logs;
```
[I 15:51:36.766 NotebookApp]B Support files will be in 
[I 15:51:36.766 NotebookApp]B Making directory /opt/wrk
[I 15:51:36.775 NotebookApp]B Making directory /opt/wrk
[I 15:51:36.792 NotebookApp]B Making directory /opt/wrk
[I 15:51:36.800 NotebookApp]B Writing 17441 bytes to /opt/wrk/notebook.tex
[I 15:51:36.805 NotebookApp]B Building PDF
[I 15:51:36.805 NotebookApp]B Running xelatex 3 times: [u'xelatex', u'/opt/wrk/note
book.tex']                                                                        
[I 15:51:39.323 NotebookApp]B Running bibtex 1 time: [u'bibtex', u'/opt/wrk/noteboo
k']                                                                               
[W 15:51:39.363 NotebookApp]B bibtex had problems, most likely because there were n
o citations                                                                       
[I 15:51:39.365 NotebookApp]B PDF successfully created
```
I do get a PDF with two plots.

**Comment by daschw** [comment]
I'm on Windows 10 and I use Jupyter from Conda.jl
I am creating a notebook with one cell containing:
```julia
using Plots
plot(rand(10))
```
With current Plots master I get a pdf without a plot and:
```
[W 10:35:14.392 NotebookApp] Terminals not available (error was No module named terminado)
[I 10:35:14.484 NotebookApp] Serving notebooks from local directory: C:\Users\Daniel
[I 10:35:14.484 NotebookApp] 0 active kernels
[I 10:35:14.484 NotebookApp] The Jupyter Notebook is running at:
[I 10:35:14.484 NotebookApp] http://localhost:8888/?token=27b64fbc070818182d2d37f45af1c1a254fc556ef76ca8f7
[I 10:35:14.484 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:35:14.500 NotebookApp]
Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=27b64fbc070818182d2d37f45af1c1a254fc556ef76ca8f7
[I 10:35:14.782 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 10:35:17.933 NotebookApp] Creating new notebook in
[I 10:35:18.993 NotebookApp] Kernel started: b3bb1b7e-9cb4-401d-b911-d9ffa5562e34
Starting kernel event loops.
C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\dateutil\parser.py:605: UnicodeWarning:
Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
elif res.tzname and res.tzname in time.tzname:
[I 10:35:27.181 NotebookApp] Adapting to protocol v5.0 for kernel b3bb1b7e-9cb4-401d-b911-d9ffa5562e34
[I 10:36:21.131 NotebookApp] Saving file at /Untitled17.ipynb
C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\filters\datatypefilter.py:41:
UserWarning: Your element with mimetype(s) [u'text/html'] is not able to be represented.
mimetypes=output.keys()
[I 10:36:21.476 NotebookApp] Writing 16093 bytes to C:\Users\Daniel\notebook.tex
[I 10:36:21.476 NotebookApp] Building PDF
[I 10:36:21.496 NotebookApp] Running xelatex 3 times: ['xelatex', 'C:\\Users\\Daniel\\notebook.tex']
[I 10:36:26.039 NotebookApp] Running bibtex 1 time: ['bibtex', 'C:\\Users\\Daniel\\notebook']
[W 10:36:26.691 NotebookApp] b had problems, most likely because there were no citations
[I 10:36:26.691 NotebookApp] PDF successfully created
```
With this branch checked out I get no pdf and:
```
[W 10:16:21.003 NotebookApp] Terminals not available (error was No module named terminado)
[I 10:16:21.096 NotebookApp] Serving notebooks from local directory: C:\Users\Daniel
[I 10:16:21.098 NotebookApp] 0 active kernels
[I 10:16:21.098 NotebookApp] The Jupyter Notebook is running at:
[I 10:16:21.098 NotebookApp] http://localhost:8888?token=f6871392a5b233c2c1341f4b5be46c1b039c037563503be1
[I 10:16:21.098 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:16:21.099 NotebookApp]
                                                                                                                                                                                                                        Copy/paste this URL into your browser when you connect for the first time,                                              to login with a token:
http://localhost:8888/?token=f6871392a5b233c2c1341f4b5be46c1b039c037563503be1
[I 10:16:21.309 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 10:16:25.121 NotebookApp] Creating new notebook in
[I 10:16:26.305 NotebookApp] Kernel started: c7c2ec91-92df-4267-aa30-227f97fe0c52
Starting kernel event loops.
C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\dateutil\parser.py:605: UnicodeWarning:
Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being
unequa
elif res.tzname and res.tzname in time.tzname:
[I 10:16:34.549 NotebookApp] Adapting to protocol v5.0 for kernel c7c2ec91-92df-4267-aa30-227f97fe0c52
[I 10:17:56.966 NotebookApp] Saving file at /Untitled15.ipynb
[E 10:17:57.173 NotebookApp] nbconvert failed: global name 'FileNotFoundError' is not defined                               Traceback (most recent call last):
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\notebook\nbconvert\handlers.py", line 122, in get
resources=resource_dict
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\exporters\pdf.py", line 162, in from_notebook_node
nb, resources=resources, **kw
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\exporters\latex.py", line 82, in from_notebook_node
return super(LatexExporter, self).from_notebook_node(nb, resources, **kw)
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\exporters\templateexporter.py", line 280, in from_notebook_node
nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\exporters\exporter.py", line 134, in from_notebook_node
nb_copy, resources = self._preprocess(nb_copy, resources)
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\exporters\exporter.py", line 311, in _preprocess
nbc, resc = preprocessor(nbc, resc)
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
return self.preprocess(nb, resources)
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\preprocessors\base.py", line 69, in preprocess
nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\preprocessors\convertfigures.py", line 46, in preprocess_cell
self.from_format, output.data[self.from_format])
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 91, in convert_figure
shell = self.command.format(from_filename=input_filename,
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\traitlets\traitlets.py", line 556, in __get__          return self.get(obj, cls)
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\traitlets\traitlets.py", line 535, in get              value = self._validate(obj, dynamic_default())
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 55, in _command_default
return self.inkscape + \
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\traitlets\traitlets.py", line 556, in __get__          return self.get(obj, cls)
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\traitlets\traitlets.py", line 535, in get              value = self._validate(obj, dynamic_default())
File "C:\Users\Daniel\.julia\v0.6\Conda\deps\usr\lib\site-packages\nbconvert\preprocessors\svg2pdf.py", line 69, in _inkscape_default
except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
[W 10:17:57.190 NotebookApp] 500 GET /nbconvert/pdf/Untitled15.ipynb?download=true (::1): nbconvert failed: global name 'FileNotFoundError' is not defined 
[E 10:17:57.197 NotebookApp] {
"Accept-Language": "de,en-US;q=0.7,en;q=0.3",
"Accept-Encoding": "gzip, deflate",
"Host": "localhost:8888",
"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0",
"Dnt": "1",
"Connection": "keep-alive",
"Referer": "http://localhost:8888/notebooks/Untitled15.ipynb?kernel_name=julia-0.6",
"Cookie": "_xsrf=2|7e984b07|e4f870ffa2eb88abcbd95a6d8af4b385|1519033266; username-localhost-8889=\"2|1:0|10:1519204562|23:username-localhost-8889|44:NDMxMmIwNjUyM2VkNDhkYzgyZTMwMzVjYmU2ODFiNGI=|378f827e0a65380706793ce4a4b6fcf75f6207eab7822639eede1e0975ee4515\"; username-localhost-8888=\"2|1:0|10:1519204581|23:username-localhost-8888|44:M2JiZDlkMWExYzM5NDc5NTkwMmQ0ZDZhNDc4NGYzNmI=|a7b2c302f07ec73725a7df8ea2d637e7fb6c2edb88d0206445957fdd246e81cb\"",
"Upgrade-Insecure-Requests": "1"
}
[E 10:17:57.198 NotebookApp] 500 GET /nbconvert/pdf/Untitled15.ipynb?download=true (::1) 180.00ms referer=http://localhost:8888/notebooks/Untitled15.ipynb?kernel_name=julia-0.6
```
(Wow, copying from Windows cmd is terrible ...)

**Comment by massemanet** [comment]
could it be as simple as you not having inkscape installed? it's needed in order to render svg.
perhaps you could try installing inkscape, alternatively remove the svg plot from the notebook.

**Comment by daschw** [comment]
Yes, that was it. Thanks a lot @massemanet and shame on me!

**Comment by massemanet** [comment]
it's strange that nbconvert is so unhelpful for this, probably pretty common, problem.

**Comment by daschw** [comment]
LGTM IMHO, @mkborregaard, @piever? Not sure who feels the most competent to review this ...

**Comment by mkborregaard** [comment]
Let's merge

**Comment by daschw** [comment]
Thanks again @massemanet and also @jleugeri for testing!

**Comment by ajkeller34** [comment]
This commit appears to have broken interactivity for the PlotlyJS backend in an IJulia notebook. If I checkout the previous commit, interactivity comes back.

**Comment by piever** [comment]
PlotlyJS is being forced to use `svg` instead of `html`, I'll make a PR to fix it.

**Comment by piever** [comment]
@ajkeller34 can you see if #1408 fixes it for you?

Also, I'm afraid that somehow [this code](https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/plotly.jl#L94) for `plotly` doesn't get called any more and plotly's plots no longer show up.

**Pull request merged**
