### PR TITLE
wip: Add NaNmath and NaN-friendly functions (fix #796)

### LINKED ISSUE #796: xlim and ylim defaults are incorrect on 0.6
On 0.5, the defaults for `xlim` and `ylim` take into account all elements of the plot and try to accommodate them all; on 0.6, they seem to default to (0, 1).

### PR DESCRIPTION
**Pull request by mkborregaard**

### CODE REVIEW

**Comment by mkborregaard** [comment]
Can't be merged, as the maximum function does not accept a generator.

**Comment by daschw** [comment]
How about
```julia
NaNMath.maximum(gen::Base.Generator) = NaNMath.maximum(collect(gen))
NaNMath.minimum(gen::Base.Generator) = NaNMath.minimum(collect(gen))
```
?

**Comment by mkborregaard** [comment]
Worth a try, ill give it a shot tomorrow :)

**Comment by mkborregaard** [comment]
Currently I'm investigating creating a local function that overrides the Base only for certain argument types:
```julia
import NaNMath
for fun in (:extrema, :minimum, :maximum, :mean)
       @eval $(Symbol(string("_",fun)))(x...) = Base.$(fun)(x...)
       @eval $(Symbol(string("_",fun))){F <: AbstractFloat}(x::AbstractVector{F}) = NaNMath.$(fun)(x)
end
```
It doesn't work, though, yet, for some reason :-/
Another major issue is that NaNMath don't have methods for higher-dimension arrays than Vectors, so e.g. heatmaps with matrices with NaNs in them (something I use every day in fact) are off too.

**Pull request closed without merging**
