### PR TITLE
Remove cache-busting from gif animation. Should be done by the frontend.

### PR DESCRIPTION
**Pull request by OliverEvans96**
Solves #1447 on the Plots.jl end.

### CODE REVIEW

**Comment by daschw** [comment]
Thanks a lot for this @OliverEvans96 !
I just checked out this branch and it seems to work in Jupyter notebook too. Can anyone confirm that? In that case I don't see a reason for keeping the old hack.

**Comment by OliverEvans96** [comment]
I'm actually seeing it not working without doing cache busting in Plots.jl. In the classic notebook, if you do somethings like:
```julia
@gif for i=1:3
    plot(rand(4),rand(4))
end
```
it produces the plot as expected.

If you then try to run
```julia
@gif for i=1:3
    heatmap(rand(4,4)
end
```
the first line plot appears, again, not the heatmap. Upon inspecting the HTML, I see `` with no cache busting.

I think that this is an outstanding issue with the classic notebook jupyter/notebook#1369

**Comment by daschw** [comment]
Yes, I can confirm the issue you described and I agree that it's probably best to wait for a fix on the jupyter side.

**Comment by mkborregaard** [comment]
Can this be merged now?

**Comment by mkborregaard** [comment]
Thanks @OliverEvans96

**Comment by mkborregaard** [comment]
We'll see if people have problems

**Pull request merged**
