### PR TITLE
increase default `(minor)gridalpha`

### PR DESCRIPTION
**Pull request by t-bltg**
The grid lines are barely visible (if not invisible), where they should be (and they were before according to https://github.com/JuliaPlots/Plots.jl/issues/1486), because of the very low transparency level:
https://docs.juliaplots.org/stable/gallery/gr/generated/gr-ref1/#gr_demo_1
https://docs.juliaplots.org/stable/gallery/gr/generated/gr-ref24/#gr_demo_24

Fix https://github.com/JuliaPlots/Plots.jl/issues/1486.

PR: arbitrary increase of `alpha` channel (might need new ref imgs).

- [x] ref imgs (https://github.com/JuliaPlots/PlotReferenceImages.jl/pull/122).

### CODE REVIEW

**Review by BeastyBlacksmith — COMMENTED** [review]
It seems the situation has improved already since 2018 (ref: https://github.com/JuliaPlots/Plots.jl/issues/1483#issuecomment-381418743) and in my opinion we could close #1486 without this.

**Comment by t-bltg** [comment]
Frankly, between `gr`, `pgfplotsx` and `pyplot`:

https://docs.juliaplots.org/stable/gallery/gr/generated/gr-ref1/#gr_demo_1,
https://docs.juliaplots.org/stable/gallery/pyplot/generated/pyplot-ref1/#pyplot_demo_1,
https://docs.juliaplots.org/stable/gallery/pgfplotsx/generated/pgfplotsx-ref1/#pgfplotsx_demo_1,

`gr` is the only backend where you cannot distinguish the grid.

**Comment by BeastyBlacksmith** [comment]
I am fine with increasing the default gridline intensity, despite changing default values being a breaking change, since the difference is barely visible and on average an improvement.
Note, that if there are differences between backends increasing the default value for all backends will magnify the difference. I consider it harmless in this case though.

**Comment by t-bltg** [comment]
Thanks, let's test this now.
If the docs build for `1.32.0` is not satisfactory, the PR and ref images is trivial to revert.

**Comment by t-bltg** [comment]
I think all the examples for all backends on https://docs.juliaplots.org/dev now have discrete but visible grids.

**Comment by BeastyBlacksmith** [comment]
> Why did the docs not deploy to `1.32` ?

You did write `skip ci` on the commit. You need to run the workflow manually on the tag now.

**Pull request merged**
