### PR TITLE
[WIP] Rewrite and extract the pipeline 

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by daschw** [comment]
I can't rebuild the travis tests here.

**Comment by asinghvi17** [comment]
Travis and Appveyor restart if you turn the pull request off and on again 😄

**Comment by mkborregaard** [comment]
Hi @daschw what about rebasing the ds/rewrite branch on current master, making a new pull request (so you get credited), merging and tagging a new Plots release? RecipesPipeline is out.

**Comment by daschw** [comment]
Yeah I still have to port https://github.com/JuliaPlots/Plots.jl/pull/2548 to RecipesPipeline and check that everything works on this branch. I can do that today.

**Pull request closed without merging**
