### PR TITLE
New PlotTheme type

### PR DESCRIPTION
**Pull request by daschw**
This is required by https://github.com/JuliaPlots/PlotThemes.jl/pull/21 and vice versa.

### CODE REVIEW

**Comment by daschw** [comment]
I also added a recipe to quickly preview a theme:
`Plots.showtheme(:solarized)`:
shotheme_solarized

`Plots.showtheme(:solarized, :protanopic)`:
shotheme_solarized_protanopic

**Comment by mkborregaard** [comment]
That's great! If one were to change other things than colors in the themes, how would that play together with Plots' default system?

**Comment by daschw** [comment]
I'm not sure I understand your question correctly. Is your question related to the new PlotTheme type or to showtheme? In the new PlotTheme type the default of any Plots attribute can be changed and showtheme shows the figures above with the defaults specified by the theme:
```julia
using Plots
add_theme(:mytheme, PlotThemes.PlotTheme(framestyle = :none, linestyle = :dot))
Plots.showtheme(:mytheme)
```
mytheme

**Comment by mkborregaard** [comment]
To the new PlotTheme type and how it relates to defaults set with `default()` (I think they should override the theme) and with those set by the `PLOTS_DEFAULTS` environmental variable. Right now there's some tricky behavior:
```
Plots.showtheme(:mytheme, color = :redsblues)
```
I'd hoped this would change the color gradient for the bottom row and leave the top row intact, but:
skaermbillede 2017-12-14 kl 11 15 56

**Comment by daschw** [comment]
Ah, I see.
- I think the top row is expected: Just try `plot(rand(10, 4), color = :redsblues)` without any theme.
- The second row is an issue with the `showtheme` recipe. I explicitely use the theme's gradient colors here, to be able to modify them for different visions (protanopic, etc...). In praxis, `theme(:dark); heatmap(rand(10, 10), color = :redsblues)` works as expected. But there's definitely room for improvement in the `showtheme` recipe ...
- `theme()` in Plots uses `default()` so default value specified by `PLOTS_DEFAULTS` or a call to `default()` earlier which is also specified by a theme is overwritten by the theme's default. This has also been this way with the old PlotTheme type. Calling `default()` after calling `theme()` overwrites the theme's default values again.

**Comment by daschw** [comment]
Maybe `theme()` really should ignore the attributes set in `PLOTS_DEFAULTS`. I think this could be implemented quite easily.

**Comment by mkborregaard** [comment]
Ah OK. I think it's actually unfortunate that `color` covers both gradient and single color, whereas `palette` is distinct. Maybe we should split `color` into `color` and `gradient`? Maybe not.
Also look at the weird gridlines I get in showtheme when specifying color???

Great about the interaction with defaults.

Not sure about your last suggestion - maybe we should replace `PLOTS_DEFAULTS` by the `theme` functionality altogether.

**Comment by daschw** [comment]
The grid line colors issue in 3D plots really is weird.

**Pull request merged**
