### PR TITLE
Add areaplot example to gallery

### PR DESCRIPTION
**Pull request by briochemc**
Not sure this is the right way to add example to the gallery but hopefully this is helpful :)

### CODE REVIEW

**Comment by t-bltg** [comment]
@BeastyBlacksmith, what is the criterion for orienting contributions to the new `gallery` (old examples) or the `user gallery` ?

**Comment by johnnychen94** [comment]
Here's my understanding:

- For examples that can be fit into the docstring, it goes here (the old examples); these examples have no differences from the examples listed in `?startswith` and it simply indicates that these functionalities work or don't work for certain backends.
- The new gallery is more of a "how to make a beautiful plot result" collection; it doesn't necessarily work for every backend.

**Comment by briochemc** [comment]
FWIW, I submitted this because [someone on StackOverflow](https://stackoverflow.com/questions/71794565/how-to-draw-a-proportion-graph-in-julia/71828494#71828494) "looked at all of the examples in the documentation and could not find a similar graph" (similar to an `areaplot`).

**Comment by t-bltg** [comment]
Good point for the docstring. We could say that the examples working with all major backends `GR`, `Plotly`, `PyPlot`, `PGFPlotsX` are allowed to go into the regular `Gallery`.

So @briochemc for this PR to go in you'd need to:
1. stick to the format (run `using JuliaFormatter; format(["src", "test"])`)
2. generate the new reference images for `gr` by running the test suite, and submitting a pr to https://github.com/JuliaPlots/PlotReferenceImages.jl (see also https://docs.juliaplots.org/stable/contributing/#VisualRegressionTests).

**Pull request merged**
