### PR TITLE
Replace artifact by scratchspace

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
In https://github.com/JuliaPlots/Plots.jl/pull/3023#discussion_r505772221 it was pointed out that this path is never taken, this PR fixes that.

Question is open if that works out or if more needs to be done/ revert the artifact stuff.

Should close https://github.com/JuliaPlots/Plots.jl/issues/3071

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
@fredrikekre I replaced the artifact by the scratchspace. Could you have a look on this, if this is how it is supposed to be used?

**Comment by fredrikekre** [comment]
Looks ok. For packaging purposes it would of course be nice to repack it as an artifact since you would not have to load Plots etc in order to instantiate it.

**Comment by BeastyBlacksmith** [comment]
I can't quite follow. Where would that artifact be hosted?

**Comment by fredrikekre** [comment]
Anywhere public.

**Pull request merged**
