### PR TITLE
Add ability to place series legend labels next to final series datapoint in GR

### PR DESCRIPTION
**Pull request by wfrgra**
eg.  plot(rand(5,5),legend=:label)

See [](https://www.eugenewei.com/blog/2017/11/13/remove-the-legend) for inspiration

### CODE REVIEW

**Comment by mkborregaard** [comment]
Sorry see what for inspiration?

**Comment by wfrgra** [comment]
Sorry, markdown fail. This was the inspiration: [https://www.eugenewei.com/blog/2017/11/13/remove-the-legend](https://www.eugenewei.com/blog/2017/11/13/remove-the-legend)

**Comment by mkborregaard** [comment]
It looks nice. Can you post an example plot?
I think `label` as a term is confusing, as we also have a `label` keyword. Maybe `:inline`?

**Comment by wfrgra** [comment]
Happy to change the name. Here are some examples

example1
example2

**Comment by mkborregaard** [comment]
Nice. Happy to merge once we have a good name

**Comment by daschw** [comment]
The name is fine for me, but maybe we should handle these cases differntly:
```julia
plot(rand(10, 4), legend = :inline, xflip = true)
```
inline_xflip

```julia
plot(rand(10, 4), legend = :inline, ymirror = true)
```
inline_ymirror

**Comment by mkborregaard** [comment]
oh yes!

**Comment by wfrgra** [comment]
This commit should have fixed the issues with xflip and ymirror

**Comment by mkborregaard** [comment]
sweet

**Pull request merged**
