### PR TITLE
Deprecate inspectDR

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
Its not working on julia 1.10 and there is little activity. 

xref: https://github.com/ma-laforge/InspectDR.jl/issues/34

cc: @ma-laforge 

## Attribution
- [x] I am listed in [.zenodo.json](https://github.com/JuliaPlots/Plots.jl/blob/2463eb9f8065c52ed8314f6e541664c5b9db88d2/.zenodo.json) (see https://github.com/JuliaPlots/Plots.jl/issues/3503)

## Things to consider
- [ ] Does it work on log scales?
- [ ] Does it work in layouts?
- [ ] Does it work in recipes?
- [ ] Does it work with multiple series in one call?
- [ ] PR includes or updates tests?
- [ ] PR includes or updates documentation?

### CODE REVIEW

**Comment by ma-laforge** [comment]
Hi @BeastyBlacksmith. Sorry: I haven't had much time to maintain things lately.

I probably could get InspectDR running again - but I don't know if my lack of feature support is a problem.

I'm guessing not that many people were using the tool - so the extra effort might not be worth it.

Thank you to the team for all the help!
(I know some maintenance had to be done on my integration as Plots evolved)

**Comment by BeastyBlacksmith** [comment]
Well, if you get it working I am happy to revert this.

**Comment by ma-laforge** [comment]
It should work now.

Apparently had something to do with `precompile()` no longer allowed an argument coming from the main module due to side effect issues.

**Comment by ma-laforge** [comment]
Thanks.

**Pull request merged**
