### PR TITLE
Fix annotate! API, add test coverage

### LINKED ISSUE #4306: [BUG] Recent breaking change in `annotate!` API
Until recently, this was a valid way to provide an annotation:

```
annotate!(p2, fkd.nframes / 2, 1, text("failed filter", :top, 8, :red)) # p2 is a plot
```

Recently, I started to get this error:
```
MethodError: no method matching process_annotation(::Plots.Subplot{Plots.GRBackend}, ::Float64)

Closest candidates are:
process_annotation(::Plots.Subplot, ::Any, !Matched::Any, !Matched::Any) at ~/.julia/packages/Plots/0MO2T/src/components.jl:618
process_annotation(::Plots.Subplot, ::Any, !Matched::Any, !Matched::Any, !Matched::Any) at ~/.julia/packages/Plots/0MO2T/src/components.jl:618
process_annotation(::Plots.Subplot, !Matched::Union{Symbol, Tuple, AbstractVector{Symbol}}, !Matched::Any) at ~/.julia/packages/Plots/0MO2T/src/components.jl:632
...

_update_subplot_periphery(::Plots.Subplot{Plots.GRBackend}, ::Vector{Any})@args.jl:1928
_update_subplot_args(::Plots.Plot{Plots.GRBackend}, ::Plots.Subplot{Plots.GRBackend}, ::Dict{Symbol, Any}, ::Int64, ::Bool)@args.jl:2061
_subplot_setup(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol, Any}, ::Vector{Dict{Symbol, Any}})@pipeline.jl:290
plot_setup!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol, Any}, ::Vector{Dict{Symbol, Any}})@pipeline.jl:151
recipe_pipeline!(::Any, ::Any, ::Any)@RecipesPipeline.jl:87
_plot!(::Plots.Plot, ::Any, ::Any)@plot.jl:209
var"#plot!#154"(::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}}, ::typeof(RecipesBase.plot!), ::Plots.Plot)@plot.jl:199
var"#annotate!#530"(::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, ::typeof(Plots.annotate!), ::Plots.Plot{Plots.GRBackend}, ::Float64, ::Vararg{Any})@Plots.jl:249
annotate!(::Plots.Plot{Plots.GRBackend}, ::Float64, ::Int64, ::Vararg{Any})@Plots.jl:249
```

I was able to resolve it by wrapping the data in a vector instead:
```
annotate!(p2, [fkd.nframes / 2, 1, text("failed filter", :top, 8, :red)]) # p2 is a plot
```

However, the vector form doesn't work in the earlier version either, resulting in another method error:

```
MethodError: no method matching process_annotation(::Plots.Subplot{Plots.GRBackend}, ::Vector{Any})

Closest candidates are:
process_annotation(::Plots.Subplot, ::Any, !Matched::Any, !Matched::Any) at ~/.julia/packages/Plots/1KWPG/src/components.jl:593
process_annotation(::Plots.Subplot, ::Any, !Matched::Any, !Matched::Any, !Matched::Any) at ~/.julia/packages/Plots/1KWPG/src/components.jl:593
process_annotation(::Plots.Subplot, !Matched::Union{Symbol, Tuple, AbstractVector{Symbol}}, !Matched::Any) at ~/.julia/packages/Plots/1KWPG/src/components.jl:607
...

_update_subplot_periphery(::Plots.Subplot{Plots.GRBackend}, ::Vector{Any})@args.jl:1956
_update_subplot_args(::Plots.Plot{Plots.GRBackend}, ::Plots.Subplot{Plots.GRBackend}, ::Dict{Symbol, Any}, ::Int64, ::Bool)@args.jl:2073
_subplot_setup(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol, Any}, ::Vector{Dict{Symbol, Any}})@pipeline.jl:288
plot_setup!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol, Any}, ::Vector{Dict{Symbol, Any}})@pipeline.jl:149
recipe_pipeline!(::Any, ::Any, ::Any)@RecipesPipeline.jl:87
_plot!(::Plots.Plot, ::Any, ::Any)@plot.jl:208
var"#plot!#146"(::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}}, ::typeof(RecipesBase.plot!), ::Plots.Plot)@plot.jl:198
annotate!#520@Plots.jl:267[inlined]
annotate!(::Plots.Plot{Plots.GRBackend}, ::Vector{Any})@Plots.jl:267
```

Change happened sometime after 1.25.5

### PR DESCRIPTION
**Pull request by BioTurboNick**
Fixes #4306, should be added into a ~1.36.x~ 1.31.x release.

### CODE REVIEW

**Review by t-bltg — APPROVED** [review]

**Comment by t-bltg** [comment]
I assume you meant `1.32.x` for breaking according to semver.

**Comment by BioTurboNick** [comment]
> I assume you meant `1.32.x` for breaking according to semver.

No, because this fixes a breaking change that occurred in 1.31.x, restoring how it worked before. This is a backwards-compatible bug fix.

https://docs.npmjs.com/about-semantic-versioning

(Breaking would have to wait for 2.x by semver)

**Comment by t-bltg** [comment]
Why the `1.36.x` in https://github.com/JuliaPlots/Plots.jl/pull/4307#issue-1337417905 then ?

All packages registered in https://github.com/JuliaRegistries/General/pulls are marked breaking when incrementing minor.

According to [semver](https://semver.org/#spec-item-6) this would be a `patch` release.

**Comment by BioTurboNick** [comment]
Ah, meant 1.31.x; the 6 from the current patch slipped in.

Minor releases are only marked breaking when in v0.x. See for example https://github.com/JuliaRegistries/General/pull/65173

**Comment by t-bltg** [comment]
> Minor releases are only marked breaking when in v0.x

Ha, thanks for the clarification.

**Comment by t-bltg** [comment]
Let's merge https://github.com/JuliaPlots/Plots.jl/pull/4310 (when CI is green) before releasing `1.31.7`.

**Pull request merged**
