### PR TITLE
Allow Date and DateTime as ticks (fix: #1026)

### PR DESCRIPTION
**Pull request by daschw**
This allows
```julia
days = Date(2015,1,1):Date(2015,12,31)
tickdays = Date(2015,1,1):Dates.Month(1):Date(2015,12,31)
plot(days, rand(length(days)), xticks = tickdays)
```
and
```julia
days = DateTime(2015,1,1):DateTime(2015,12,31)
tickdays = DateTime(2015,1,1):Dates.Month(1):DateTime(2015,12,31)
plot(days, rand(length(days)), xticks = (tickdays, Date.(tickdays)))
```
cf #1026

### CODE REVIEW

**Comment by mkborregaard** [comment]
Crazy idea, feel free to ignore/laugh: could it also allow
```julia
days = Date(2015,1,1):Date(2015,12,31)
plot(days, rand(length(days)), xticks = :Months)
```
?

**Comment by daschw** [comment]
That would definitely be nice. I think I would have to think a little longer, how this could be done in detail, though. So I won't add it here.

**Comment by mkborregaard** [comment]
Good point.

**Comment by mbeltagy** [comment]
This works fine, however if you try 
```julia
xticks!(tickdays)
```
you get 
```
MethodError: no method matching xticks!(::StepRange{Date,Month})
Closest candidates are:
  xticks!(!Matched::Union{AbstractArray{T,1}, Symbol, Tuple{AbstractArray{T,1},AbstractArray{S,1}}} where S<:AbstractString where T<:Real; kw...) where T<:Real at /home/elbeltagy/.julia/packages/Plots/47Tik/src/shorthands.jl:414
  xticks!(!Matched::AbstractArray{T<:Real,1}, !Matched::AbstractArray{S<:AbstractString,1}; kw...) where {T<:Real, S<:AbstractString} at /home/elbeltagy/.julia/packages/Plots/47Tik/src/shorthands.jl:420
  xticks!(!Matched::Union{Plot, Subplot}, !Matched::Union{AbstractArray{T,1}, Symbol, Tuple{AbstractArray{T,1},AbstractArray{S,1}}} where S<:AbstractString where T<:Real; kw...) where T<:Real at /home/elbeltagy/.julia/packages/Plots/47Tik/src/Plots.jl:202
  ...
top-level scope at none:0

```

**Pull request merged**
