### PR TITLE
import plot! placeholder from RecipesBase

### PR DESCRIPTION
**Pull request by daschw**
Requires https://github.com/JuliaPlots/RecipesBase.jl/pull/26

### CODE REVIEW

**Comment by mkborregaard** [comment]
so this should be merged now?

**Comment by daschw** [comment]
I think as soon as a new RecipesBase version is tagged, right?

**Comment by daschw** [comment]
I guess it can also be merged now. Then you'll get a warning in the tests that `RecipesBase.plot!` could not be imported.

**Comment by daschw** [comment]
So yes, I think this should be merged before we tag a new RecipesBase release and we also should also tag a new Plots release before that. Right?

**Comment by mkborregaard** [comment]
I'll roll the releases tomorrow if you don't get to it tonight

**Comment by daschw** [comment]
I do Plots tonight and we can do RecipesBase after Plots is tagged.

**Pull request merged**
