### PR TITLE
Use Base.require workaround in IJuliaExt

### PR DESCRIPTION
**Pull request by oschulz**
Addresses issue #4719.

### CODE REVIEW

**Comment by oschulz** [comment]
Don't merge yet, still adding an improvement.

**Review by t-bltg — COMMENTED** [review]
I'm a bit reluctant in making Plots messier than it already is.

That being said, we can have a work around if it is the only solution left, since it affects multiple end users.

At the very least, we should address 
https://github.com/JuliaPlots/Plots.jl/issues/4719#issuecomment-1554061512 so that we can link to an upstream issue in this PR.

**Comment by oschulz** [comment]
Ok, should be good now.

**Comment by oschulz** [comment]
TTFP doesn't seem to be increased noticeably, compared to "extension-mode".

**Pull request merged**
