### PR TITLE
fix extra blank space in GR with log axis and engineering notation

### LINKED ISSUE #2316: Extra blank space in engineering notation
Extra blank space appear in tick labels in engineering notation. For instance:
```
using Plots
using Formatting
gr()
x=[0.001,0.1,1]; y=x

scatter(x,y,
    xaxis=:log10,
    xformatter=x->sprintf1("%1.0e",x),
    yformatter=y->sprintf1("%1.0e",y))
```
The y axis format seems to be fine while in the x axis (logarithmic one) an extra blank space appears after "e-". It seems to happen just in the negative exponents only on logarithmic scales.

### PR DESCRIPTION
**Pull request by daschw**
fix #2316

### CODE REVIEW

**Comment by miguelfm** [comment]
Thanks for the hack, but unfortunately doesn't seem to work this time.  I've tested it with the same code and the extra blank space after the "-" is still there :(.

**Comment by daschw** [comment]
I'll check again soon, but when I tested it, it worked.

**Comment by daschw** [comment]
```julia
using Plots, Formatting
x = y = [0.001, 0.1, 1]
scatter(x, y,
    xaxis = :log10,
    xformatter = x -> sprintf1("%1.0e", x),
    yformatter = y -> sprintf1("%1.0e", y),
    xtickfont = 15,
)
```
on master:
xticks_master

with this change:
xticks_fix

**Comment by miguelfm** [comment]
It is working now. I don't know what I did yesterday, sorry. Now runs perfectly! Thanks.

**Comment by miguelfm** [comment]
> ```julia
> using Plots, Formatting
> x = y = [0.001, 0.1, 1]
> scatter(x, y,
>     xaxis = :log10,
>     xformatter = x -> sprintf1("%1.0e", x),
>     yformatter = y -> sprintf1("%1.0e", y),
>     xtickfont = 15,
> )
> ```
> 
> on master:
> xticks_master
> 
> with this change:
> xticks_fix

Sorry, but the fix seems still broken for pdf output (working fine for png).
```
using Plots, Formatting
x = y = [0.001, 0.1, 1]
scatter(x, y,
    xaxis = :log10,
    xformatter = x -> sprintf1("%1.0e", x),
    yformatter = y -> sprintf1("%1.0e", y),
    xtickfont = 15,
)
savefig("test.pdf")
```
test
[test.pdf](https://github.com/JuliaPlots/Plots.jl/files/3979539/test.pdf)

**Pull request merged**
