### PR TITLE
gr: clamp rgb values

### PR DESCRIPTION
**Pull request by jheinen**

### CODE REVIEW

**Comment by mkborregaard** [comment]
For greyscale values I solved this centrally in #1901 and #1900 . I guess the same could be done for rgb's - do you not think it's more sustainable to do it in the common pipeline?

**Comment by jheinen** [comment]
> For greyscale values I solved this centrally in #1901 and #1900 . I guess the same could be done for rgb's - do you not think it's more sustainable to do it in the common pipeline?

Yes, I'd prefer a central solution.

**Comment by mkborregaard** [comment]
Hi @jheinen just to understand - why did you add the volume code to this PR? I thought we'd decided to supersede this with central functionality?

**Comment by jheinen** [comment]
@mkborregaard : GR provides bindings for C, Python, Ruby and Julia. I have no idea how to add this functionality with central (Julia) code.

**Comment by mkborregaard** [comment]
No I meant should the rgb clamping not be done here: https://github.com/mkborregaard/Plots.jl/blob/877811979295f9b8200f5a7d0fc160fa7be71f41/src/series.jl#L351-L365 rather than in Plots/backends/gr.jl?

**Comment by mkborregaard** [comment]
I'm just confused why rgb clamping and the volume functionality are in the same PR. Is it just because you made it on your own master branch?

**Comment by jheinen** [comment]
yes - I think that is/was the problem - my fault.

**Pull request closed without merging**
