### PR TITLE
Changed spy recipe and added spy example to tests (fix #883)

### LINKED ISSUE #883: feature request: spy function for matrices
There was a feature request for a ``spy`` function to graphically represent matrices (especially useful for sparse matrices): [issue 40](https://github.com/JuliaPlots/Plots.jl/issues/40). It was closed a while back. Is that spy function available? Is there a preferred alternative? Thanks.

### PR DESCRIPTION
**Pull request by daschw**
as discussed in #883

### CODE REVIEW

**Comment by mkborregaard** [comment]
Hm, I disagree. I think the reason I didn't notice the markersize before is that the grid was covering them. I think we should just set grid --> false in the recipe, but not be too noisy in the terminal.

**Comment by mkborregaard** [comment]
One thing the documentation really needs is a folder with a page for each of the (groups of) seriestypes. That would be a nice place to have this info. And perhaps we should add a `spy` example to the examples/tests?

**Comment by daschw** [comment]
Yes, that's a better solution.

**Comment by daschw** [comment]
I removed the command line info, turned the colorbar off for matrices with unique nonzeros and added an example. This now requires https://github.com/JuliaPlots/PlotReferenceImages.jl/pull/2 to pass.

**Comment by mkborregaard** [comment]
Nice touch with the superquick response here and with legendtitle :-)

**Pull request merged**
