### PR TITLE
Make legend=:outertopright work for GR

### PR DESCRIPTION
**Pull request by 8uurg**
Plot showing legend being positioned outside of the plotarea

As the plotarea's bounding box had to be changed depending on the legend's size, the code for computing the legend's size had to be moved upwards.
Constants were taken from [GR's own plotting functions](https://github.com/jheinen/GR.jl/blob/master/src/jlgr.jl#L525) where the legend is positioned outside of the plotarea (positions 11, 12 and 13).

### CODE REVIEW

**Comment by daschw** [comment]
This is so awesome! We've had so many questions about how to position the legend outside with GR and could only provide hacky workarounds. Thanks @8uurg!

**Comment by mkborregaard** [comment]
Yes, great! 
What's the behaviour like when you have multiple subplots?

**Comment by daschw** [comment]
legend_out

It's what you would expect for GR, IMO. Plotly(JS) is the only backend with a shared legend.

**Comment by mkborregaard** [comment]
Yes that looks great

**Comment by Jo-Fleck** [comment]
Thanks a lot for this feature @8uurg ! Was truly missed.

**Comment by Jo-Fleck** [comment]
btw: I cannot find this in the manual yet. Would be helpful to update.

**Pull request merged**
