### PR TITLE
baseline fix for bar plots using log scales

### PR DESCRIPTION
**Pull request by t-bltg**
Fix https://github.com/JuliaPlots/Plots.jl/issues/4502.

At least values within the same decade are unified to the same value (decade start).
Would that be better @giordano ?

```julia
bar([1 2 3], [11 25 85]; yscale=:log10)
```

**pr**
pr

**master**
master

The problem lies in the way we process series.
Can we preprocess a common minimal value before mapping to [bar series](https://github.com/JuliaPlots/Plots.jl/blob/master/src/recipes.jl#L408-L504) ?

- [x] check performance

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
Can't we just set `fillrange --> 1` in the bar recipe if the yscale is a logscale?

**Comment by t-bltg** [comment]
Could be a cheap solution too.

**Comment by giordano** [comment]
For what is worth, the original data in my example span multiple decades (10 and 100 mainly), reason why I was trying to use logscale

**Comment by t-bltg** [comment]
We could compute global series extrema somewhere here https://github.com/JuliaPlots/Plots.jl/blob/master/RecipesPipeline/src/series_recipe.jl#L10-L29 ...

If we choose an arbitrary default value of `1`, we'll get the same issue for e.g. `bar([1 2 3], [0.01 10 100]; yscale=:log10)`.

**Comment by t-bltg** [comment]
Computing extrema along all series now allow the following:

```julia
bar([1 2 3], [0.02 125 10_000]; yscale=:log10)
```

**pr**
pr

**master**
master

**Comment by giordano** [comment]
Looks great! And I can still tweak it with fillto if I need, right?

**Comment by t-bltg** [comment]
Yes, as long as positive. Can also be an vector of positive values.

**Pull request merged**
