### PR TITLE
 Allow vectors of markers for pyplot scatter

### PR DESCRIPTION
**Pull request by djsegal**
Can be a little slow, but I tried to do some basic batching where possible (to speed it up)

### CODE REVIEW

**Comment by daschw** [comment]
I'm sorry that you have to wait so long for feedback. It looks great! I will check and test this soon.

**Comment by daschw** [comment]
With this branch checked out and the command
```julia
using Plots
pyplot()
scatter(rand(10), markershape = [:circle, :diamond, :square])
```
I get the following warning on my linux machine:
```julia
/usr/lib/python3.7/site-packages/matplotlib/legend.py:937: UserWarning: Legend does not support [<matplotlib.collections.PathCollection object at 0x7f8f5b10d320>, <matplotlib.collections.PathCollection object at 0x7f8f5b10d710>, <matplotlib.collections.PathCollection object at 0x7f8f5b10dd68>, <matplotlib.collections.PathCollection object at 0x7f8f5b0aa278>, <matplotlib.collections.PathCollection object at 0x7f8f5b0aa5f8>, <matplotlib.collections.PathCollection object at 0x7f8f5b0aaac8>, <matplotlib.collections.PathCollection object at 0x7f8f5b0aaf98>, <matplotlib.collections.PathCollection object at 0x7f8f5b0ab4a8>, <matplotlib.collections.PathCollection object at 0x7f8f5b0ab978>] instances.
A proxy artist may be used instead.
See: http://matplotlib.org/users/legend_guide.html#creating-artists-specifically-for-adding-to-the-legend-aka-proxy-artists
  "aka-proxy-artists".format(orig_handle)
/usr/lib/python3.7/site-packages/matplotlib/legend.py:937: UserWarning: Legend does not support [<matplotlib.collections.PathCollection object at 0x7f8f5b052748>, <matplotlib.collections.PathCollection object at 0x7f8f5b052c18>, <matplotlib.collections.PathCollection object at 0x7f8f5b052eb8>, <matplotlib.collections.PathCollection object at 0x7f8f5afdd518>, <matplotlib.collections.PathCollection object at 0x7f8f5afdd978>, <matplotlib.collections.PathCollection object at 0x7f8f5afddc18>, <matplotlib.collections.PathCollection object at 0x7f8f5afddeb8>, <matplotlib.collections.PathCollection object at 0x7f8f5afe9518>, <matplotlib.collections.PathCollection object at 0x7f8f5afe9978>] instances.
A proxy artist may be used instead.
See: http://matplotlib.org/users/legend_guide.html#creating-artists-specifically-for-adding-to-the-legend-aka-proxy-artists
  "aka-proxy-artists".format(orig_handle)
```
and it produces the following plot:
pyplot_markershape_vec

So there's definitely an issue with the legend and the first two markershapes are repeated, which also is not expected. Do you have an idea, what causes this, or how this can be fixed?

**Comment by daschw** [comment]
On this branch I now get
```julia
julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
ERROR: LoadError: LoadError: UndefVarError: Display not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1041
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /home/dani/.julia/dev/Plots/src/Plots.jl:3
 [6] top-level scope at none:0
 [7] top-level scope at none:2
in expression starting at /home/dani/.julia/dev/Plots/src/types.jl:9
in expression starting at /home/dani/.julia/dev/Plots/src/Plots.jl:155
ERROR: Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to /home/dani/.julia/compiled/v1.0/Plots/ld3vC.ji.
```
But maybe I did something wrong with updating your branch. I will check again tomorrow.

**Comment by djsegal** [comment]
I went back to v0.6 😬

**Comment by djsegal** [comment]
Done. Sorry for the delay! (kind of forgot about it.)

**Comment by daschw** [comment]
Great, thanks!

**Pull request merged**
