### PR TITLE
Fix #1799

### LINKED ISSUE #1799: 'c' argument issue in pyplot
With this code:
```julia
using Plots
pyplot()
p=plot(rand(2), rand(2), rand(2), seriestype=:path)
plot!(p, [1.0], [0.5], [1.0], seriestype=:scatter)
```
I get this warning:
```
'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.
```
It doesn't seem to happen with ``gr()``.  Any insights on what the issue is or how to avoid it without switching to another backend?

Thanks!

### PR DESCRIPTION
**Pull request by mauro3**
This may fix #1799.  Although, note, I have no deeper understanding of this code...

### CODE REVIEW

**Comment by mauro3** [comment]
No, this does not work

**Comment by mkborregaard** [comment]
Damn, I was already running the tests (Travis only checks on GR)

**Comment by mauro3** [comment]
Ok, maybe this works. (Also added `"off"->false` to remove other deprecations)

**Comment by mkborregaard** [comment]
Oooh, it's an actual fix now! :-D Let me see if it works

**Comment by mauro3** [comment]
Yep, I had to roll out emacs...

**Comment by mkborregaard** [comment]
It works :heart:

**Comment by mkborregaard** [comment]
Thank you @mauro3 !

**Comment by daschw** [comment]
That's great, thanks @mauro3 !

**Pull request merged**
