### PR TITLE
Fix PlotlyJS backend and prepare for PlotDocs update

### PR DESCRIPTION
**Pull request by daschw**
I had to move all the supported attribute dicts out of the (`@required`) backend code so that they are available for PlotDocs to build the html tables.

### CODE REVIEW

**Comment by sglyon** [comment]
hmm I can't get this to render with plotlyjs backend from REPL. Are you able to get it to work there, or perhaps you are testing in a different environment?

**Comment by daschw** [comment]
You're right, I did not test thoroughly in the REPL. It works perfectly in Atom, but there we only display a png. In the REPL for me only the first plot works, unfortunately (as reported in https://github.com/JuliaPlots/Plots.jl/issues/1721#issuecomment-418620996).

**Comment by BoundaryValueProblems** [comment]
@daschw and @sglyon , I am wondering what is the status of the ```plotlyjs``` backend of ```Plots.jl```. With today's update of ```PlotlyJS.jl``` (v0.11.2), now ```PlotlyJS.jl``` genuine functions work under Juno/Atom. Yet, as the backend of ```Plots.jl``` (v0.20.5), it still doesn't work under Juno/Atom. Under REPL using Terminal, it doesn't work either. In both case, it generates the following error: ```ERROR: type SyncPlot has no field view```, especially when I try to plot something twice. Thanks!

**Comment by daschw** [comment]
I did not proceed here. PlotlyJS still is not working from the REPL.
Still, I will go ahead and merge the changes from here in a new clean PR.
We will have to fix plotlyjs in a separate PR.

**Pull request closed without merging**
