### PR TITLE
include precompile_includer.jl

### PR DESCRIPTION
**Pull request by daschw**
See https://github.com/JuliaPlots/Plots.jl/issues/2838

### CODE REVIEW

**Comment by aminya** [comment]
@daschw Could you edit this line instead to the following:
https://github.com/JuliaPlots/Plots.jl/blob/master/.github/workflows/SnoopCompile.yml#L77
```
(git diff -w --no-color || (git diff -w --no-color | git apply --cached --ignore-whitespace && git checkout -- . && git reset && git add -p)) || echo done

```

**Comment by daschw** [comment]
ok, will do, thanks!

**Comment by aminya** [comment]
Let me know if the bot adds `include("precompile_includer.jl")` automatically.

**Comment by aminya** [comment]
@daschw I have decided to write a Julia script instead of a Bash script. So if this failed, please include the file manually, until I make a PR.

**Comment by daschw** [comment]
OK, thanks

**Pull request merged**
