### PR TITLE
GR: add support for mesh3d

### PR DESCRIPTION
**Pull request by t-bltg**
Add GR support for mesh3d since, for now, [GR](https://github.com/sciapp/gr) does not support drawing arbitrary points using a triangle connectivity array.
The error check code was copied from the `pgfplotsx` backend: https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/pgfplotsx.jl 

The test for this case already exists [here](https://github.com/JuliaPlots/Plots.jl/blob/ef93aa87be11f30837c87089d9f8e5c1f73c1baf/src/examples.jl#L1001) as example `47`, and is run e.g. for `pgfplotsx`: https://docs.juliaplots.org/latest/generated/pgfplotsx/#pgfplotsx-ref47.

Needs https://github.com/JuliaPlots/RecipesPipeline.jl/pull/90 patch.

Output of example 47
----------------------------
ref47

- [x] generate `ref47.png` for GR 
https://github.com/JuliaPlots/PlotReferenceImages.jl/pull/101

Linked https://github.com/JuliaPlots/Plots.jl/issues/392

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
This is missing the faces of the triangles though. Also some legend figure would be good.

**Comment by t-bltg** [comment]
> This is missing the faces of the triangles though. Also some legend figure would be good.

OK I will change the example then.

**Comment by BeastyBlacksmith** [comment]
You could also add a warning, that the GR backend doesn't support 3D mesh's with faces at the moment

**Comment by t-bltg** [comment]
New output

ref47

**Comment by bernd1995** [comment]
Quick question.
Could this `mesh3d` function be used to get a nicely working `histogram3d` (#3379)?
I started a PR (#3507) a few months ago but currently don't have any time to work on that 😕

So maybe my initial work on that could be finished with that PR being merged.

**Comment by t-bltg** [comment]
> Quick question.
> Could this `mesh3d` function be used to get a nicely working `histogram3d` (#3379)?
> I started a PR (#3507) a few months ago but currently don't have any time to work on that confused
> 
> So maybe my initial work on that could be finished with that PR being merged.

I don't think so since this is only for triangles.

However you mentioned in https://github.com/JuliaPlots/Plots.jl/pull/3507#issue-645996631 that surface didn't have a mesh option:

I've pushed this PR which allows to use GR options when using surface https://github.com/JuliaPlots/Plots.jl/pull/3591

Is that of any help ?

**Comment by bernd1995** [comment]
Thanks for the suggestions.
I somehow completely missed that this PR is only for triangles. 😅

I'll think about your suggestions, and if you happen to have another good idea comment on my PR #3507.

**Comment by t-bltg** [comment]
@BeastyBlacksmith, if you don't see anything against, can I merge this ?

**Review by BeastyBlacksmith — APPROVED** [review]

**Pull request merged**
