### PR TITLE
Handling Deprecation warnings for HDF5 backend

### PR DESCRIPTION
**Pull request by wg030**
I have updated hdf5.jl so that all deprecations warnings should be gone now!

Fix: #3157

### CODE REVIEW

**Review by BeastyBlacksmith — APPROVED** [review]
Great! Thank you

**Comment by ranocha** [comment]
Thanks! It would be nice to have a new release of Plots.jl, since these warning still show up in the latest release (from November). We use Plots.jl and would like to run some tests with `@test_nowarn` which currently fails (and the only warnings we see are related to Plots.jl and HDF5).

**Comment by wg030** [comment]
@ranocha I can't help you with a new release, but have you tried `add Plots#master`, works like a charm for me!

**Comment by ranocha** [comment]
Thanks for that hint, @wg030. I have used `add Plots#master` locally, but we would like to be able to run these tests using a released version of Plots.jl such that everything works reliably also on standard installations (CI, users of our packages etc.).

**Pull request merged**
