### PR TITLE
Barplot fix

### LINKED ISSUE #799: Passing strings as x values to bar plot no longer working
With
```julia
using Plots
bar(["a", "b"], [1, 2])
```
I now get
```julia
MethodError: Cannot `convert` an object of type Type{Any} to an object of type AbstractFloat
This may have arisen from a call to the constructor AbstractFloat(...),
since type constructors fall back to convert methods.
 in _preprocess_binlike(::Dict{Symbol,Any}, ::Array{String,1}, ::Array{Int64,1}) at recipes.jl:426
 in macro expansion at recipes.jl:326 [inlined]
 in apply_recipe(::Dict{Symbol,Any}, ::Type{Val{:bar}}, ::Array{String,1}, ::Array{Int64,1}, ::Void) at RecipesBase.jl:238
 in _process_seriesrecipe(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}) at pipeline.jl:404
 in _plot!(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{String,1},Array{Int64,1}}) at plot.jl:227
 in #plot#263(::Array{Any,1}, ::Function, ::Array{String,1}, ::Vararg{Any,N}) at plot.jl:52
 in (::Plots.#kw##plot)(::Array{Any,1}, ::Plots.#plot, ::Array{String,1}, ::Array{Int64,1}, ::Vararg{Array{Int64,1},N}) at <missing>:0
 in #bar#369(::Array{Any,1}, ::Function, ::Array{String,1}, ::Vararg{Any,N}) at Plots.jl:143
 in bar(::Array{String,1}, ::Vararg{Any,N}) at Plots.jl:143
 in include_string(::String, ::String) at loading.jl:441
 in include_string(::String, ::String, ::Int64) at eval.jl:30
 in include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N}) at eval.jl:34
 in (::Atom.##53#56{String,Int64,String})() at eval.jl:50
 in withpath(::Atom.##53#56{String,Int64,String}, ::String) at utils.jl:30
 in withpath(::Function, ::String) at eval.jl:38
 in macro expansion at eval.jl:49 [inlined]
 in (::Atom.##52#55{Dict{String,Any}})() at task.jl:60
```
@oschulz I think this is caused by https://github.com/JuliaPlots/Plots.jl/pull/787

### PR DESCRIPTION
**Pull request by oschulz**
Improve data preprocessing for bar and histogram plots
    
Fixes #799.

### CODE REVIEW

**Comment by mkborregaard** [comment]
This, and #787 , markedly increases the complexity of bar diagrams, though #787 was only intended to change the histogram implementation. Is this just to improve log `:scale`?

**Comment by oschulz** [comment]
> This, and #787 , markedly increases the complexity of bar diagrams, though #787 was only intended to change the histogram implementation. Is this just to improve log :scale

It's mostly due to log scale - but I wouldn't say "just to improve log :scale". Log scale (esp. on the y-axis) is *very* important for histograms in many, many situations, and it was completely broken (meaning unusable) before. But it turns out that doing this properly isn't fully trivial, so it needs a bit of code.

**Comment by mkborregaard** [comment]
I mean just in the 'exclusively' sense, not 'unimportant' sense.

**Comment by mkborregaard** [comment]
Hit the wrong button

**Comment by oschulz** [comment]
:-)

**Pull request merged**
