### PR TITLE
Example for vspan and hspan

### LINKED ISSUE #4051: [FR] Filling horizontal regions across whole vertical axis range
I was looking to achieve something very similar to [this example from matplotlib](https://matplotlib.org/stable/gallery/lines_bars_and_markers/fill_between_demo.html#selectively-marking-horizontal-regions-across-the-whole-axes), whereby one can shade some horizontal extent.

I came up with the following:

```julia
function fill_xrange!(xmin, xmax; kwargs...)
    ymin, ymax = ylims()
    result = plot!([xmin, xmax], [ymin, ymin]; fillrange=[ymax, ymax], lw=0, kwargs...)
    ylims!((ymin, ymax))
    return result
end
```

... but this only is guaranteed to work if it is the last thing to be plotted (and even then it requires the rather dubious call to `ylims!` to undo the automatic zooming-out that will occur)

Is something better possible with the existing `Plots.jl` API, or would additional functionality be required?

(I marked this as a 'feature request', as I think even if it is possible, it'd be a useful example to add to the documentation!)

### PR DESCRIPTION
**Pull request by tpgillam**
Closes #4051.

Provide example of using vspan and hspan.

### CODE REVIEW

**Comment by tpgillam** [comment]
Looks like I would need to add a new image to https://github.com/JuliaPlots/PlotReferenceImages.jl — what's the usual workflow for doing a PR like this? I'm happy to make a PR there now if we're happy with the example, which generates the following:
ref57

**Comment by t-bltg** [comment]
> what's the usual workflow for doing a PR like this?

https://docs.juliaplots.org/latest/contributing/#VisualRegressionTests

**Comment by tpgillam** [comment]
I've opened a PR on PlotReferenceImages.jl — but that PR will obviously need tweaking if anyone would like the example tweaked :)

**Comment by t-bltg** [comment]
Looks good.
Please format your pr using `$ julia -e 'using JuliaFormatter; format(["src", "test"])'` in your `Plots.jl` fork.

**Comment by BeastyBlacksmith** [comment]
Also as a first time contributor check out https://github.com/JuliaPlots/Plots.jl/issues/3503 and consider adding your information to our `.zenodo.json` file

**Pull request merged**
