### PR TITLE
bump GR version

### PR DESCRIPTION
**Pull request by jheinen**
Bump GR version to 0.69.1

### CODE REVIEW

**Comment by t-bltg** [comment]
Don't bother about the benchmarks.

1.6 ubuntu is stale, I'm going to cancel it and restart.

**Comment by t-bltg** [comment]
I'm trying to fix the conda related issues in https://github.com/JuliaPlots/Plots.jl/pull/4386, before we re-run ci here.

**Review by t-bltg — APPROVED** [review]

**Comment by t-bltg** [comment]
CI is green.

**Comment by jheinen** [comment]
> CI is green (again).

Should we merge?

**Comment by t-bltg** [comment]
> Should we merge?

Certainly go ahead, the question is should we release a new `Plots` version ?

**Comment by jheinen** [comment]
> Certainly go ahead, the question is should we release a new `Plots` version ?

I'd like to merge and then make some tests with `Plots#master`. If everything is fine, we should release a new `Plots` version.

**Comment by jheinen** [comment]
LGTM - even on Windows :astonished:

**Comment by jheinen** [comment]
I'm now on `Plots#master` and `GR` 0.69.1 - everything looks fine. IMO, you can tag a new version.

**Pull request merged**
