### PR TITLE
Revert constant legend box

### PR DESCRIPTION
**Pull request by t-bltg**
Revert https://github.com/JuliaPlots/Plots.jl/pull/3855 (through https://github.com/JuliaPlots/Plots.jl/pull/4055), until an acceptable solution is found.

Ref: https://github.com/JuliaPlots/Plots.jl/issues/4092.

### CODE REVIEW

**Review by BeastyBlacksmith — APPROVED** [review]

**Comment by isentropic** [comment]
I think we should finish the discussion in the linked issue, prior to merging.

**Review by isentropic — CHANGES_REQUESTED** [review]
Let's agree on what all people think first. This is not urgent

**Comment by t-bltg** [comment]
> I think we should finish the discussion in the linked issue, prior to merging.

I don't want to throw oil on the fire, but the discussion had to be made in https://github.com/JuliaPlots/Plots.jl/pull/3855, before being merged to master and released.

> Let's agree on what all people think first. This is not urgent

I disagree, since users seem to complain about the changes, making the reversal a wished for thing .

**Comment by BeastyBlacksmith** [comment]
> we had the discussion in Plots maintainers call...

Well that doesn't mean that decision is set in stone. We all make wrong decisions from time to time and it's easy to miss cases when making a change, since one is biased on the things one whish to improve.
So we did some tests in the call and it turns out we missed some pretty bad ones, especially with different plot sizes.
I know it's a bad feeling when your changes need to get reverted, but in this case it's the right thing to do, especially since the user doesn't have any way to compensate (other than not using a legend at all).
We'll find another way to improve this, heads up.

**Comment by isentropic** [comment]
Alright, I have no problem with that. Im sorry I just got emotional when I felt that I'm being blamed for this. After all this is all volunteering work. I guess it got personal to me. But hey at least we fixed the testing suite

**Comment by isentropic** [comment]
Let's keep the issue open, we should arrive at a better solution somehow.

**Comment by t-bltg** [comment]
> Let's keep the issue open, we should arrive at a better solution somehow.

Agreed.

@BeastyBlacksmith, given the friction in the discussions, I leave the decision of merging this PR up to you. The reference images [have been updated](https://github.com/JuliaPlots/PlotReferenceImages.jl/pull/115) against this PR. Feel free to merge when ready.

**Pull request merged**
