### PR TITLE
0.6 deprecations

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by dpsanders** [comment]
To fix deprecations with `abstract` type declarations, I will need to use `Compat.jl`. Is that acceptable?

**Comment by mkborregaard** [comment]
We'll push a new release in a few days, and then master and future releases will be 0.6 only. So there is no reason for Compat. We'll just merge this after the release. 
And thanks a lot for this!

**Comment by daschw** [comment]
It is really only line 9 in series.jl. Changing that back to `typealias ...` allows precompilation again.

**Comment by daschw** [comment]
cf. #823 and #824

**Pull request merged**
