### PR TITLE
Fix/Extend pgfplots functions

### PR DESCRIPTION
**Pull request by sebastianpech**
As I wrote in #647 I started to fix/extend some features of the pgfplots backend. The changes provide the following:

- Enable histograms, Fix fillcolor bug
- Fix yshift of subplots
- Add annotations and series_annotations
- Add support for polar axis
- Add support for ticks rotation

### CODE REVIEW

**Comment by pkofod** [comment]
Cool stuff, good to see some more features added. For reference, could you post some small examples? Code+output

**Comment by sebastianpech** [comment]
Basically I used the examples from the doc and tried getting them to work as expected. I have a [jupyter notebook](https://github.com/sebastianpech/share/blob/master/julia/PGFExamples.ipynb) with my tests (It's large so it takes a while to show up).  Every change in the example code is documented above the cell.

**Comment by pkofod** [comment]
That notebook is exactly what I had in mind, will have a look. Thanks

**Comment by sebastianpech** [comment]
For comparison this is what the current master produces: [notebook](https://github.com/sebastianpech/share/blob/master/julia/PGFExamples-master.ipynb)

**Comment by pkofod** [comment]
Looks great. I was sure I added histogram at some point, but it might have been removed at some point by mistake.

**Comment by KristofferC** [comment]
Very nice

**Comment by sebastianpech** [comment]
I thought so, because to enable the bar and histogram I only needed to add :shape and except for the fillcolor everything was working.

**Comment by tbreloff** [comment]
Thanks :+1:

**Comment by haampie** [comment]
Great work! Really appreciated

**Pull request merged**
