### PR TITLE
only show plotly plots as html in Juno

### PR DESCRIPTION
**Pull request by pfitzseb**
Should help with https://github.com/JuliaPlots/Plots.jl/issues/2297#issuecomment-582341068 and generally be more correct.

### CODE REVIEW

**Comment by mkborregaard** [comment]
sweet

**Comment by daschw** [comment]
Nice

**Comment by BoundaryValueProblems** [comment]
@pfitzseb and @daschw ; as I just mentioned in #2297, the problem somehow reoccurrs now in Plots.jl v0.28.4. Something must have changed since you merged, especially in terms of setting `Base.showable(::MIME"application/prs.juno.plotpane+html", plt::Plots.Plot)`. I would greatly appreciate it if you could check this and fix this problem again! Thanks a lot!

**Comment by BoundaryValueProblems** [comment]
@pfitzseb and @daschw ; please ignore my previous post. I updated Plots.jl to the current master v0.29.5. Then, the problem went away. Somehow simply doing `pkg> up` didn't update Plots.jl from v0.28.4 to v0.29.5. Some other packages must have specified Plots v0.28.4... Anyways, it works again now!

**Comment by daschw** [comment]
Great 🙂

**Pull request merged**
