### PR TITLE
Avoid non-positive heatmap edges for log axis on GR and PyPlot

### PR DESCRIPTION
**Pull request by daschw**
```julia
using Plots
x = y = 1:3:30
heatmap(x, y, x * y', xscale = :log10, yscale = :log10)
```
used to return a `log10` `DomainError`, although all input data is positve. That is because the first calculated heatmap edge is `-0.5` (cf. #920).

PlotlyJS solves this by removing the first values of `x` and `y` as well as the first row and column of the data matrix:
heatmap_log10_plotlyjs

PyPlot and GR now increase the first heatmap edge values to a positive value to avoid `DomainError`s and keep all matrix data.
PyPlot:
heatmap_log10_pyplot_new
GR still has some issues:
heatmap_log10_gr_new
On GR heatmaps are drawn as images with the uniformly sized rectangles, so the log scale does not affect the heatmap edge positions. Instead the colorbar ticks are affected. (cc: @jheinen )

### CODE REVIEW

**Comment by jebej** [comment]
Thanks for this. I'll check it out soon (on vacation), and like I  mentionned on #920 there might be two different ways of doing this, so it might be worth it to discuss it briefly.

**Comment by mkborregaard** [comment]
cf https://github.com/JuliaPlots/Plots.jl/issues/942 and this PR https://github.com/JuliaPlots/Plots.jl/pull/835 which adresses a different issue - that axis widening on log axes can also cause the value to go sub-zero.

**Comment by jebej** [comment]
The change looks good and the PyPlot examples looks fine! Is it possible to keep the full matrix with Plotly as well, or is it something done by the js library itself?

**Comment by oschulz** [comment]
A question related to this: Which backends support z-log-scale for heatmap now?

**Comment by daschw** [comment]
@oschulz I don't think any backend does.

**Pull request merged**
