### PR TITLE
Fix #1531, Let xlims be set to Dates or DateTimes

### LINKED ISSUE #1531: xlim does not work with DateTimes
Similar to #1026,

```julia
> plot([DateTime(2016), DateTime(2017)], [3,2], xlim=(DateTime(2015), DateTime(2018)))

MethodError: no method matching optimize_datetime_ticks(::DateTime, ::DateTime; k_min=2, k_max=4)
```

and, like #1026, using `Dates.value` solves the issue.

### PR DESCRIPTION
**Pull request by ThatcherC**
Resolves #1531, allowing xlims to be set to Date or DateTime values. Also adds two unit tests that show xlims working with both Date and DateTime.

### CODE REVIEW

**Comment by daschw** [comment]
Thanks! Sorry I merged your other PR before this now we have a conflict here. Could you rebase this PR on current master? I think ideally, we should somehow call type recipes on axes attributes like ylims (or ticks - where we special case for Dates types). However, until we come up with a clear general interface for that, I think special casing for Dates types here for lims ony is an improvement.

**Comment by ThatcherC** [comment]
No problem! I'll rebase soon and push it back up. I agree there's probably a better way to solve the issue - hopefully this is helpful for now. One problem I noticed with this fix is that you can't use DateTimes for `xlims` if the series x data is Date objects, since Dates get converted to integer days while DateTimes get converted to integer milliseconds. Maybe an eventual solution could convert Dates and DateTimes both to the same numerical representation (like milliseconds)?

Also - should I worry about the Julia nightly CI checks? f6627f3 passed the Julia night/macos_latest check, but 9ba633b did not, even though there were no changes in the 9ba633b commit.

**Comment by daschw** [comment]
Thanks! I don't think the nightly errors are related to the changes here. I like the idea of converting Dates and DateTimes to the same value internally.

**Comment by nathanrboyer** [comment]
Can you also add support for the `Dates.Time` type?

**Pull request merged**
