### PR TITLE
RFC: New spy implementation

### PR DESCRIPTION
**Pull request by mkborregaard**

### CODE REVIEW

**Comment by mkborregaard** [comment]
@alanedelman (https://github.com/JuliaPlots/Plots.jl/issues/40) and @dpsanders both asked for a heatmap-based version of spy, close to what's in Gadfly. This actually represents the pre-0.9.4 Plots implementation if `spy`. 
I prefer this too, so I've made a quick PR (it mab do too much unnecessary copying at the moment). This reimplements `spy` as a y-flipped heatmap, with no gridlines, transparent (white) areas for zero values (and undefined values of sparse matrices), aspect_ratio 1.

```julia
a = sprand(100, 200, 0.01)
spy(a)
```
skaermbillede 2017-10-09 kl 21 17 10

(note @daschw that the x-labels dont follow the ticks up when the y axis is flipped ).

Comments welcome.

**Comment by daschw** [comment]
I like it!
I will look into the xtick labels (this is GR, right?)

**Comment by mkborregaard** [comment]
yes.
The reason I make a new copy of the matrix is that I assume that matrix being passed in is often sparse - so if I want to replace all zero-elements with NaN I think it is better to just initialize a new dense matrix. Of course we could specialcase sparse matrices instead.

**Comment by daschw** [comment]
Do we want both, tick marks and tick labels, up or down?

**Comment by daschw** [comment]
All other backends (PyPlot, PlotlyJS, PGFPlots and GLVisualize) have them down ... So I guess this answers my question.

**Comment by daschw** [comment]
fixed in #1163

**Comment by mkborregaard** [comment]
Nice. I think I'll merge this unless there are any complaints about inefficient code?

**Comment by daschw** [comment]
Fine with me. If anyone wants a more efficient implementation they are welcome to submit a PR 😄

**Pull request merged**
