### PR TITLE
passing of extra keywords to pgfplotsx

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
This showcases how extra keyword passing could be realized, by populating the existing `extra_kwargs` and pass it in the pgfplots backend.

Partially fixes https://github.com/JuliaPlots/Plots.jl/issues/2197.

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
Currently the interface is take all arguments, warn if it is an unsupported Plots argument, pass it to the backend otherwise.
E.g.: `plot(x, y, arrow = true)` would warn and
`plot(x, y, texlabel="what a label")` would pass `texlabel` on.
The alternative would be the more explicit `plot(x,y, xlimits=(0,10), extra_kwargs=Dict(:do=>"that"))` or `plot(x,y, xlimits=(0,10), extra_kwargs=(do = "that"))` and keep warning about usupported keyword arguments. Preferences?

**Comment by BeastyBlacksmith** [comment]
Also while this works for something like `plot(1:5, texlabel="test")` it does not work at the moment if you do `plot!(x->x^2, 1,5)` afterwards.
I think this is due to `extra_kwargs` being in `Plot.attr` rather than `Subplot.attr`.

**Comment by BeastyBlacksmith** [comment]
@mkborregaard , @daschw: this works for me. Would be good to get some feedback regarding the interface (https://github.com/JuliaPlots/Plots.jl/pull/2200#issuecomment-535960763).
Have not checked yet how difficult it would be for the other backends.

**Comment by daschw** [comment]
> Would be good to get some feedback regarding the interface (#2200 (comment)).

I would go with the current implementation. `kwarg = val` just feels more user-friendly than `extra_kwargs = (kwarg = val)`.

**Comment by BeastyBlacksmith** [comment]
After my experience with https://github.com/JuliaPlots/Plots.jl/pull/2252 I can say, that this would need `extra_kwargs` dict on every layer: Plot, Subplot, Axis, Series(, Segments).

**Comment by daschw** [comment]
> After my experience with #2252 I can say, that this would need extra_kwargs dict on every layer: Plot, Subplot, Axis, Series(, Segments).

Does this mean that this PR would have to be changed to have `extra_plot_kwargs`, `extra_subplot_kwargs`, `extra_axis_kwargs` and `extra_series_kwargs`?

I think that's a little much. IMO Plots does not have to provide all the functionality of each backend. The idea is rather to have a common interface for the plotting utilities most used and demanded by the community. For special, detailed tweaking of plots going beyond Plots attributes I'd point the users to use the backend directly.

**Comment by daschw** [comment]
However, that's just my opinion and I can also see the point of having these `extra_kwargs`. If we really need them on different layers, I think my previous statement regarding `kwarg = val` vs `extra_kwargs = (kwarg = val)` is no longer valid. In that case the `kwarg = val` is no longer possible, right? So we'd have to go with the second option.

**Comment by mkborregaard** [comment]
I agree with Daniel. 

But, what about allowing passing a `Dict` of `Dicts`, eg `Dict(:Subplot => Dict(:colorbar => :extend))`, it would be terribly clunky but allow people with highly particular needs a workaround to resolve stuff?

**Comment by daschw** [comment]
That's a good idea.

**Comment by BeastyBlacksmith** [comment]
Turned it into Dict of Dicts and collect unsupported kwargs into the series-dict, since that is probably the most useful.
Alternatively could only allow passing them explicitly.

**Comment by BeastyBlacksmith** [comment]
@mkborregaard, @daschw I just change the interface a bit as you can see in the added tests and I think it is quite okay from the user perspective.
Its a bit annoying for the backends that extra keywords for the plot is stored in `extra_plot_kwargs` and the others in `extra_kwargs`.
So happy to hear what you think.

**Comment by BeastyBlacksmith** [comment]
Demo:
```julia
    plot(plot(1:5, title="Line"), scatter(1:5, title="Scatter", extra_kwargs=Dict(:subplot=>Dict("axis line shift" => "10pt"))))
```
image

**Comment by daschw** [comment]
Looks good! I don't have a better idea than `extra_plot_kwargs`. Does this really require a 2.0 release?

**Comment by BeastyBlacksmith** [comment]
No, it was more a "should be done before 2.0"
Probably minor version bump?

**Pull request merged**
