### PR TITLE
lazily load Pkg

### PR DESCRIPTION
**Pull request by KristofferC**
This is a bit of a hack to work around the fact that depending on Pkg is quite expensive in 1.11. Here, we only load it when checking the compatibility / install status of a backend and also skipping that when the backend is GR.jl (since we know that is compatible due to resolving together with Plots).

I'll admit this is kind of ugly and a bit of "TTFP hacking". However, I don't think Plots.jl should depend on a package manager at all so 🤷.

TTFP change 2.1s to 1.7s

### CODE REVIEW

**Comment by KristofferC** [comment]
PlotsBase does the same: https://github.com/JuliaPlots/Plots.jl/blob/f32247a819bc938a133bb3403770814194821408/PlotsBase/src/backends.jl#L45

**Comment by isentropic** [comment]
I dont think this function is needed at all now https://github.com/JuliaPlots/Plots.jl/blob/f32247a819bc938a133bb3403770814194821408/PlotsBase/src/backends.jl#L27
but lets wait for @BeastyBlacksmith to confirm

**Comment by BeastyBlacksmith** [comment]
Thats true, that code can go in `v2`. However for the 1.x series we would need to up the julia compat, since `pkgversion` requires julia 1.9+

**Comment by KristofferC** [comment]
> since pkgversion requires julia 1.9+

It is easy to read the project file of the package and extract the version. I just didn't remember when `pkgversion` was introduced.

**Comment by KristofferC** [comment]
(Looking forward to v2 which seems to have a great design avoiding these "hacks")

**Pull request merged**
