### PR TITLE
Implement title_location for GR

### PR DESCRIPTION
**Pull request by pearlzli**
```julia
julia> using Plots; gr();

julia> x = -π:0.1:π; y = sin.(x);

julia> plot(x, y, title = "Title", title_location = :left)
```
left

```julia
julia> plot(x, y, title = "Title", title_location = :right)
```
right

```julia
julia> plot(x, y, title = "Title", title_location = :center)
```
center

### CODE REVIEW

**Comment by mkborregaard** [comment]
Nice - can you compare to how those same plots look like with pyplot? And maybe add `title_location` to one of the examples?

Also, those GR plots look terrible, what is your GR version?

Finally, that plot is more succintly plotted with `plot(sin, -π, π)` :-)

**Comment by pearlzli** [comment]
New commit 9ea78af handles right-aligned titles better:

```julia
julia> plot(sin, -π, π, title = "My Slightly Longer Title")
```
right

I'm having some trouble generating the equivalent plot in PyPlot right now. There is a title location [example](http://docs.juliaplots.org/latest/examples/gr/#layouts-margins-label-rotation-title-location) for GR in the documentation, although it doesn't show the feature actually working - do you want me to regenerate the image and update it there?

Finally, the plots probably look terrible because I'm working over SSH, so these example images are screenshots, not actual plots saved from GR.

**Comment by mkborregaard** [comment]
OK, all good then. Here are the pyplot plots on your branch:
```julia
plot([sin, sin, sin], layout = (3,1), title = "My awesome title", title_location = [:left :center :right], size = (300, 600))
```
pyplot_titleloc

Given that there's a GR example in the examples, I'm very surprised that the Travis tests pass. It's supposed to fail whenever an example looks differently. The approach is then to make a linked PR in PlotReferenceImages that updates the image. But before trying that, could you checkout "PlotReferenceImages.jl" and run `Pkg.test("Plots")` locally on this branch? Thanks!

**Comment by mkborregaard** [comment]
I like it that the pyplot titles are aligned with the plot area. I'm guessing that there's no default setting in GR for that, though.

**Comment by pearlzli** [comment]
Hmm I wasn't able to build ImageMagick on the current machine I'm working on. I'll try again when I get home, on a laptop where I have root access.

I don't think I know enough about GR at the moment to align the title with the plot area, but I'll take another look through!

**Comment by mkborregaard** [comment]
Right - never mind about the local test run if that's complicated.

**Comment by jheinen** [comment]
Sorry - I didn't realize that there was already an incomplete PR. Fixed in #1206

**Comment by mkborregaard** [comment]
Sorry about that @pearlzli but thanks a lot for the high-quality PR. Interestingly, Josef's implementation is more or less identical to yours :-)

**Comment by mkborregaard** [comment]
@pearlzli are you on Hacktoberfest? You could open a really small PR (e.g. add this new feature to the News.md file) so you get credit for the PR.

**Comment by jheinen** [comment]
@pearlzli thanks for the PR - I saw it too late. The implementation was just missing the alignment settings ...

**Comment by pearlzli** [comment]
@mkborregaard @jheinen I'm not doing Hacktoberfest, and definitely no worries! I'm just happy to be able to left-align my titles :)

**Pull request closed without merging**
