### PR TITLE
Partial fix for plotlyjs backend, for IJulia

### PR DESCRIPTION
**Pull request by lwabeke**
Tries to address #1793 and https://github.com/sglyon/PlotlyJS.jl/issues/221

IJulia and REPL plotting seems to work again, however from REPL plot! creates a new empty window in addition to updating existing window (this behaviour seems to be similar to master), but only if run on a separate line, running plot(rand(10));plot!(rand(5)) doesn't create the extra window

### CODE REVIEW

**Comment by mkborregaard** [comment]
There are some conflicts - could you rebase your pr on current master?

**Comment by mkborregaard** [comment]
Thanks. It looks sensible - what's "partial" about the fix?

**Comment by lwabeke** [comment]
"Partial" in terms of cutting away branches, which I can only assume had been required in certain scenarios. 
Maybe it should then be only partially tested: From REPL, from localhost using IJulia notebook() and later minimally from Juno. 
My guess is the use_remote part that I removed was for JuliaBox or some other setup of using IJulia remotely. Also is there other IDEs where plotting has been integrated, maybe it was for one of them?

Initially I added the partial also due to the fact of a blank plot window still showing up when calling plot!, however it seems that is a seperate bug also in the mainline.

**Comment by mkborregaard** [comment]
superseded by #1885 . But thanks @lwabeke !

**Pull request closed without merging**
