### PR TITLE
Various type recipe fixes

### PR DESCRIPTION
**Pull request by daschw**
This allows
```julia
struct CustomDateTime
    dt::DateTime
end

@recipe function f(::Type{T}, v::T) where T <: AbstractVector{<:CustomDateTime}
    getproperty.(v, :dt)
end

times = CustomDateTime.(DateTime.(2011:2020))

plot(times, rand(10))
```
vectorrecipes

which before used to error:
```julia
ERROR: Cannot convert CustomDateTime to series data for plotting
```

fix https://github.com/JuliaPlots/Plots.jl/issues/766

### CODE REVIEW

**Comment by mkborregaard** [comment]
Do you mean "for Dates"?

**Comment by daschw** [comment]
No, this would affect any recipe `@recipe function f(::Type{AbstractArray{T}}, v::AbstractArray{T})` where `T` is not supported by Plots. See #766.

**Comment by daschw** [comment]
The appveyor failure is related to the FixedPointNumbers pinning, by the way. I don't understand it, though.

**Comment by BeastyBlacksmith** [comment]
should be fixed

**Comment by daschw** [comment]
Nice.

**Comment by daschw** [comment]
OK, now axis arguments in type recipes are only applied to the current axis, which I think makes more sense. Overall this PR now changes
```julia
struct CustomDateTime
    dt::DateTime
    z::Symbol
end

@recipe function f(::Type{T}, v::T) where {T<:AbstractVector{<:CustomDateTime}}
    guide --> string(v[1].z)
    getproperty.(v, :dt)
end

times = CustomDateTime.(DateTime.(2011:2020), :hello)

plot(times, rand(10))
plot(rand(10), times)
```
from
```julia
ERROR: Cannot convert CustomDateTime to series data for plotting
Stacktrace:
 [1] prepareSeriesData(::CustomDateTime) at /home/daniel/.julia/dev/Plots/src/series.jl:14
```
to
vector_new1
vector_new2

and
```julia
struct MyType
    v::Float64
end

@recipe function f(::Type{T}, mt::T) where T <: MyType
    minorgrid --> true
    guide --> "MyType axis"
    (x -> x.v, x -> string(round(x, digits = 10)))
end

mts = MyType.(rand(10))

plot(mts)
```
from
typeaxisold

to
typeaxisnew

**Pull request merged**
