### PR TITLE
1.0 fixes WIP RFC

### PR DESCRIPTION
**Pull request by mkborregaard**
See #1631

### CODE REVIEW

**Comment by daschw** [comment]
There's still the
```julia
ERROR: MethodError: no method matching Array{RGBA{Float64},N} where N(::Tuple{Int64})
```
error, right?

**Comment by daschw** [comment]
I'm currently having a look.

**Comment by mkborregaard** [comment]
I don't think that's a Plots error.

**Comment by daschw** [comment]
Yep, you're right it's PlotUtils

**Comment by mkborregaard** [comment]
I fixed it then screwed up in git and lost my changes. Classic.

**Comment by daschw** [comment]
I'm on it.

**Comment by daschw** [comment]
https://github.com/JuliaPlots/PlotUtils.jl/pull/42
With this the next error is from ShowOff.jl

**Comment by daschw** [comment]
There already is an open PR:
https://github.com/JuliaGraphics/Showoff.jl/pull/12

**Comment by mkborregaard** [comment]
Thanks!

**Comment by mkborregaard** [comment]
The showoff PR got merged and I've just plotted a histogram on 1.0! Let me try to test so we can push a release today, also with the new requires framework.

**Pull request merged**
