### PR TITLE
GR: rework automatic major/minor ticks for log scales

### PR DESCRIPTION
**Pull request by t-bltg**
Superseding https://github.com/JuliaPlots/Plots.jl/pull/3547, required patch: https://github.com/JuliaPlots/PlotUtils.jl/pull/115.

Test cases:
```julia
using Plots; gr()

for (i, (start, stop)) ∈ enumerate([(-1, 2), (-6, 5)])
    x = y = Float64[1]
    for j ∈ start:stop
      append!(x, 2 * 10.0^j:10.0^j:10.0^(j + 1) |> collect)
    end
    plot(
      x, y, axis=:log10, minorgrid=true, legend=:none,
      shape=:cross, ms=2, lw=.5, dpi=200
    )
    png("loglog-$i")
end
```

Output:
loglog-1
loglog-2

Fix https://github.com/JuliaPlots/Plots.jl/issues/3318
Fix https://github.com/JuliaPlots/Plots.jl/issues/696
Fix https://github.com/JuliaPlots/Plots.jl/issues/458

### CODE REVIEW

**Comment by t-bltg** [comment]
@BeastyBlacksmith, pinging you one this one for review / merge, if we could move forward that'll be great ;)

**Comment by t-bltg** [comment]
Fixed the only minor issue with ref1:
aaa

**Comment by t-bltg** [comment]
Ok, so after merging https://github.com/JuliaPlots/PlotUtils.jl/pull/115 and triggering a new release of `PlotUtils`, the only failing test is `ref5` as expected.

@BeastyBlacksmith or @daschw if I could have your approval, we can merge https://github.com/JuliaPlots/PlotReferenceImages.jl/pull/97 and this PR.

**Comment by BeastyBlacksmith** [comment]
how did ref5 look like with minmal number of ticks = 4?

**Comment by t-bltg** [comment]
> how did ref5 look like with minmal number of ticks = 4?

```bash
$ julia ref5.jl
┌ Warning: No strict ticks found
└ @ PlotUtils [...]/PlotUtils/n4I4Q/src/ticks.jl:295
┌ Warning: No strict ticks found
└ @ PlotUtils [...]/PlotUtils/n4I4Q/src/ticks.jl:295
```

ref5

**Comment by BeastyBlacksmith** [comment]
I suppose this is because it tries to find integer exponents. Can we have some kind of look for integer exponents -> if not enough ticks present look for mulitples of 1/2 -> if not enough ticks found look for multiples of 1/4 etc. ?

**Comment by t-bltg** [comment]
> I suppose this is because it tries to find integer exponents. Can we have some kind of look for integer exponents -> if not enough ticks present look for mulitples of 1/2 -> if not enough ticks found look for multiples of 1/4 etc. ?

What's wrong with requiring less major ticks ? It is justified by the choice of log scaling.

Non-integer powers do not bring information to the plot or the user: `10^-.5` ? you need a calculator, I am not in favor of it.

**Comment by BeastyBlacksmith** [comment]
I think the plot looks a bit lost with only two ticks. But surely that is subjective, probably would look okay with minorticks. Overall I am okay with the changes

**Review by BeastyBlacksmith — APPROVED** [review]

**Comment by t-bltg** [comment]
> I think the plot looks a bit lost with only two ticks. But surely that is subjective, probably would look okay with minorticks. Overall I am okay with the changes

It is subjective, see also the examples in https://fr.mathworks.com/help/matlab/ref/loglog.html.

Don't count on minor-ticks there, we need at least 3 major ticks because of this https://github.com/JuliaPlots/Plots.jl/blob/6f4400411ee68ade1f1d916a5e70be58d628e894/src/axes.jl#L340.

**Comment by t-bltg** [comment]
@BeastyBlacksmith 

Ok this has be bothering me not to be able to have minogrids if we have 2 major ticks, I dislike un-finished things.
I reworked the logic and here is the result:
bbb

Note that we have `3` major ticks not because of `optimize_ticks` in PlotsUtils which returned `2` but because of the phantom ticks added in `get_minor_ticks`.

Would that be ok ?

**Pull request merged**
