### PR TITLE
Conform to changes in InspectDR.PlotLayout.

### PR DESCRIPTION
**Pull request by ma-laforge**
InspectDR needed structural changes to improve how layouts are controlled/allow for user-defined stylesheets/presets.

Waiting for METADATA tag so users don't get error messages:
https://github.com/JuliaLang/METADATA.jl/pull/9843

### CODE REVIEW

**Comment by mkborregaard** [comment]
Hey, do you want me to add you as a collaborator so you can commit freely to backends/inspectdr.jl?

**Comment by ma-laforge** [comment]
Sure, but is it be possible to limit my privileges to merging in pull requests, or something?

I would rather not have the ability to accidentally break more things than I need to.

**Comment by mkborregaard** [comment]
No, the system does not allow such fine-grained control. If you're not comfortable with we'll just continue as now.

**Comment by ma-laforge** [comment]
Well, if you want me to take on a bit of responsibility because you have too much to do, than I guess I'm ok becoming a collaborator.

Otherwise: I find the team is already pretty responsive at the moment - so I don't *personally* really see the need to become a collaborator at this point in time.

**Comment by ma-laforge** [comment]
PS: New version of InspectDR is tagged in METADATA.  Ready to merge whenever the team wishes.

**Comment by mkborregaard** [comment]
There's something wrong with Travis at the moment. Does `Pkg.test()` succeed locally for you on this?

**Comment by ma-laforge** [comment]
I see...  Regarding `Pkg.test()`:

It seems successful for me, but only if I manually:

```
Pkg.add("VisualRegressionTests")
#and/or
Pkg.clone("https://github.com/JuliaPlots/PlotReferenceImages.jl.git")
```
Before running the tests.

...But apparently, InspectDR is not tested against in these tests anyhow (so it is probably not the cause of the test failures).

**Pull request merged**
