### PR TITLE
change NaNMath implementation

### PR DESCRIPTION
**Pull request by mkborregaard**
So fallback referred to Base methods

### CODE REVIEW

**Comment by daschw** [comment]
That was fast :-)

**Comment by mkborregaard** [comment]
@daschw would you look at this before I merge?

**Comment by mkborregaard** [comment]
Oh we cross-posted. Let me merge this so we can get on with the tests.

**Comment by daschw** [comment]
sorry, I was too slow, but it looks good

**Comment by mkborregaard** [comment]
You were hardly too slow :-) I know I was too fast - I just thought you'd already looked at it.

**Pull request merged**
