### PR TITLE
Fix CI + Use the triggering branch name in the SnoopCompile branch

### PR DESCRIPTION
**Pull request by aminya**
This will use separate SnoopCompile branches for separate triggering branches.

Fixes https://github.com/timholy/SnoopCompile.jl/issues/145#issuecomment-713086937

Running action: https://github.com/aminya/Plots.jl/actions/runs/386271477

### CODE REVIEW

**Comment by aminya** [comment]
This is ready if you want to merge.

**Comment by BeastyBlacksmith** [comment]
I can see you comment that this is ready in the feed, but not here... Are there issues or is it good to go?

**Comment by aminya** [comment]
No, this is ready to go now. 😃 I applied a few minor patches to CompileBot. Now, they are registered.

**Comment by BeastyBlacksmith** [comment]
Great! Thank you <3

**Pull request merged**
